"use client";
import {useEffect,useState} from "react";
import {ArrowLeft,LoaderCircle,Printer,Truck} from "lucide-react";
import Link from "next/link";
import styles from "./packing-slip.module.css";

type PackingSlipData={orderNumber:string;dispatchId:string;packedAt:string;customerName:string;fulfilmentMethod:string|null;shippingAddress:{recipient:string;line1:string;line2:string;city:string;region:string;postalCode:string;countryCode:string}|null;items:{name:string;sku:string|null;variantName:string|null;variantOptions:{name:string;value:string}[];quantity:number;orderedQuantity:number}[]};
export default function PackingSlip({orderId}:{orderId:string}){
 const[data,setData]=useState<PackingSlipData|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(true);
 useEffect(()=>{let active=true;void fetch(`/api/orders/${orderId}/packing-slip`,{cache:"no-store"}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error||"Packing slip could not be loaded.");if(active)setData(body.packingSlip)}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:"Packing slip could not be loaded.")}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[orderId]);
 return <main className={styles.page}><nav className={styles.toolbar}><Link href="/orders"><ArrowLeft/>Back to orders</Link>{data&&<button onClick={()=>window.print()}><Printer/>Print packing slip</button>}</nav>{busy?<div className={styles.state}><LoaderCircle className="spin"/>Loading packing slip…</div>:error?<div className={styles.error} role="alert">{error}</div>:data&&<article className={styles.sheet}><header className={styles.header}><div className={styles.brand}><span className={styles.mark}><i/><i/><i/><i/></span><b>commerce<span>desk</span></b></div><div className={styles.docType}><small>FULFILMENT DOCUMENT</small><h1>Packing slip</h1></div></header><section className={styles.summary}><div><small>ORDER</small><b>{data.orderNumber}</b></div><div><small>DISPATCH</small><b>{data.dispatchId.slice(-8).toUpperCase()}</b></div><div><small>PACKED</small><b>{new Date(data.packedAt).toLocaleString()}</b></div></section><section className={styles.addresses}><div><small>{data.fulfilmentMethod==="pickup"?"PICKUP FOR":"SHIP TO"}</small>{data.shippingAddress?<address><b>{data.shippingAddress.recipient}</b><span>{data.shippingAddress.line1}</span>{data.shippingAddress.line2&&<span>{data.shippingAddress.line2}</span>}<span>{[data.shippingAddress.city,data.shippingAddress.region,data.shippingAddress.postalCode].filter(Boolean).join(", ")}</span><span>{data.shippingAddress.countryCode}</span></address>:<address><b>{data.customerName}</b><span>{data.fulfilmentMethod==="pickup"?"Customer pickup":"No delivery address is saved on this order."}</span></address>}</div><div className={styles.method}><Truck/><span>{data.fulfilmentMethod==="pickup"?"PICKUP":data.fulfilmentMethod==="delivery"?"DELIVERY":"FULFILMENT"}</span></div></section><table><thead><tr><th>ITEM</th><th>SKU</th><th>QTY TO PACK</th></tr></thead><tbody>{data.items.map((item,index)=><tr key={`${item.name}-${index}`}><td><b>{item.name}</b>{item.variantName&&<small>{item.variantName}</small>}{item.variantOptions.map(option=><small key={`${option.name}-${option.value}`}>{option.name}: {option.value}</small>)}</td><td>{item.sku||"—"}</td><td><b>{item.quantity}</b></td></tr>)}</tbody></table><footer><b>Thank you</b><span>Please verify all items and quantities before sealing the package.</span></footer></article>}</main>
}
