import {randomBytes} from "node:crypto";
import mongoose from "mongoose";
import {NextResponse} from "next/server";
import {z} from "zod";
import {isSameOrigin,readJsonLimited} from "@/server/request-security";
import {requireTenantAccess} from "@/server/tenant-scope";
import {CatalogueItem} from "@/server/models/CatalogueItem";
import {CatalogueVariant} from "@/server/models/CatalogueVariant";
import {AuditEvent} from "@/server/models/AuditEvent";

type Context={params:Promise<{id:string}>};
const optionSchema=z.object({name:z.string().trim().min(1).max(40),value:z.string().trim().min(1).max(80)}).strict();
const optionsSchema=z.array(optionSchema).min(1).max(8).superRefine((options,ctx)=>{
 const keys=options.map(option=>option.name.normalize("NFKC").trim().toLowerCase());
 if(new Set(keys).size!==keys.length)ctx.addIssue({code:"custom",message:"Each option name must be unique."});
});
const createSchema=z.object({name:z.string().trim().min(1).max(100),options:optionsSchema,sku:z.string().trim().max(80).nullable().default(null),unitPriceMinor:z.number().int().safe().min(0).nullable().default(null)}).strict();
const updateSchema=z.object({variantId:z.string().regex(/^[a-f\d]{24}$/i),name:z.string().trim().min(1).max(100).optional(),options:optionsSchema.optional(),sku:z.string().trim().max(80).nullable().optional(),unitPriceMinor:z.number().int().safe().min(0).nullable().optional(),active:z.boolean().optional()}).strict().refine(value=>Object.keys(value).length>1,"Provide a variant change.");
function optionKey(options:{name:string;value:string}[]){return JSON.stringify(options.map(option=>[option.name.normalize("NFKC").trim().toLowerCase(),option.value.normalize("NFKC").trim().toLowerCase()]).sort(([a],[b])=>a.localeCompare(b)));}
function errorResponse(error:unknown){if(error instanceof Error&&error.message==="PERMISSION_DENIED")return NextResponse.json({error:"You do not have permission to manage catalogue variants."},{status:403});return NextResponse.json({error:"Variant service is temporarily unavailable."},{status:503});}
export async function GET(_request:Request,context:Context){
 let access;try{access=await requireTenantAccess("catalogue:read")}catch(error){return errorResponse(error)}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});
 const{id}=await context.params;if(!mongoose.isValidObjectId(id))return NextResponse.json({error:"Product not found."},{status:404});
 try{const item=await CatalogueItem.findOne({_id:id,tenantId:access.scope.tenantId,kind:"physical"}).select("_id").lean();if(!item)return NextResponse.json({error:"Product not found."},{status:404});const variants=await CatalogueVariant.find({tenantId:access.scope.tenantId,itemId:id}).sort({name:1,_id:1}).lean();return NextResponse.json({variants},{headers:{"Cache-Control":"private, no-store"}})}catch(error){return errorResponse(error)}
}
export async function POST(request:Request,context:Context){
 if(!isSameOrigin(request))return NextResponse.json({error:"Request origin could not be verified."},{status:403});let access;try{access=await requireTenantAccess("catalogue:write")}catch(error){return errorResponse(error)}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});if(access.tenant.commerceMode!=="native")return NextResponse.json({error:"Variants for this connected store are managed in WooCommerce."},{status:409});
 const{id}=await context.params;if(!mongoose.isValidObjectId(id))return NextResponse.json({error:"Product not found."},{status:404});const body=await readJsonLimited(request,12000);if(body.kind==="too-large")return NextResponse.json({error:"Request is too large."},{status:413});const parsed=createSchema.safeParse(body.kind==="ok"?body.value:null);if(!parsed.success)return NextResponse.json({error:"Review the variant options and price.",issues:parsed.error.issues.map(issue=>({field:issue.path.join("."),message:issue.message}))},{status:400});
 const session=await mongoose.startSession();let result:unknown;try{await session.withTransaction(async()=>{const item=await CatalogueItem.findOne({_id:id,tenantId:access.scope.tenantId,kind:"physical"}).session(session).lean();if(!item)throw new Error("ITEM_NOT_FOUND");if(!item.trackInventory)throw new Error("VARIANT_STOCK_REQUIRED");const count=await CatalogueVariant.countDocuments({tenantId:access.scope.tenantId,itemId:item._id}).session(session);if(count>=100)throw new Error("VARIANT_LIMIT");const key=optionKey(parsed.data.options);if(await CatalogueVariant.exists({tenantId:access.scope.tenantId,itemId:item._id,optionKey:key}).session(session))throw new Error("OPTION_SET_EXISTS");const[variant]=await CatalogueVariant.create([{tenantId:access.scope.tenantId,itemId:item._id,name:parsed.data.name,options:parsed.data.options,optionKey:key,sku:parsed.data.sku?.trim()?parsed.data.sku.trim().toUpperCase():null,unitPriceMinor:parsed.data.unitPriceMinor,stockOnHand:0,stockReserved:0,active:true}],{session});await AuditEvent.create([{tenantId:access.scope.tenantId,actorId:access.scope.userId,action:"catalogue.variant_created",entityType:"catalogue_variant",entityId:String(variant._id),requestId:randomBytes(12).toString("hex"),metadata:{itemId:String(item._id),optionKey:key}}],{session});result=variant.toObject()})}catch(error){if(error instanceof Error&&error.message==="ITEM_NOT_FOUND")return NextResponse.json({error:"A physical product in this workspace is required."},{status:404});if(error instanceof Error&&error.message==="VARIANT_STOCK_REQUIRED")return NextResponse.json({error:"Enable stock tracking for this product before creating variants."},{status:409});if(error instanceof Error&&error.message==="VARIANT_LIMIT")return NextResponse.json({error:"A product can have at most 100 variants."},{status:409});if(error instanceof Error&&error.message==="OPTION_SET_EXISTS"||(error as {code?:number})?.code===11000)return NextResponse.json({error:"That option combination or SKU already exists in this workspace."},{status:409});return errorResponse(error)}finally{await session.endSession()}return NextResponse.json({variant:result},{status:201,headers:{"Cache-Control":"private, no-store"}})
}
export async function PATCH(request:Request,context:Context){
 if(!isSameOrigin(request))return NextResponse.json({error:"Request origin could not be verified."},{status:403});let access;try{access=await requireTenantAccess("catalogue:write")}catch(error){return errorResponse(error)}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});if(access.tenant.commerceMode!=="native")return NextResponse.json({error:"Variants for this connected store are managed in WooCommerce."},{status:409});
 const{id}=await context.params;if(!mongoose.isValidObjectId(id))return NextResponse.json({error:"Product not found."},{status:404});const body=await readJsonLimited(request,12000);if(body.kind==="too-large")return NextResponse.json({error:"Request is too large."},{status:413});const parsed=updateSchema.safeParse(body.kind==="ok"?body.value:null);if(!parsed.success)return NextResponse.json({error:"Review the variant change.",issues:parsed.error.issues.map(issue=>({field:issue.path.join("."),message:issue.message}))},{status:400});
  const{variantId,...patch}=parsed.data;const session=await mongoose.startSession();let result:unknown;try{await session.withTransaction(async()=>{const variant=await CatalogueVariant.findOne({_id:variantId,itemId:id,tenantId:access.scope.tenantId}).session(session);if(!variant)throw new Error("VARIANT_NOT_FOUND");if(patch.active===false&&variant.stockReserved>0)throw new Error("VARIANT_RESERVED");if(patch.options){const key=optionKey(patch.options);if(await CatalogueVariant.exists({tenantId:access.scope.tenantId,itemId:id,optionKey:key,_id:{$ne:variant._id}}).session(session))throw new Error("OPTION_SET_EXISTS");variant.options=patch.options as typeof variant.options;variant.optionKey=key}if(patch.name!==undefined)variant.name=patch.name;if(patch.sku!==undefined)variant.set("sku",patch.sku?.trim()?patch.sku.trim().toUpperCase():null);if(patch.unitPriceMinor!==undefined)variant.set("unitPriceMinor",patch.unitPriceMinor);if(patch.active!==undefined)variant.active=patch.active;await variant.save({session});await AuditEvent.create([{tenantId:access.scope.tenantId,actorId:access.scope.userId,action:"catalogue.variant_updated",entityType:"catalogue_variant",entityId:String(variant._id),requestId:randomBytes(12).toString("hex"),metadata:{itemId:id,fields:Object.keys(patch),active:variant.active}}],{session});result=variant.toObject()})}catch(error){if(error instanceof Error&&error.message==="VARIANT_NOT_FOUND")return NextResponse.json({error:"Variant not found in this product."},{status:404});if(error instanceof Error&&error.message==="VARIANT_RESERVED")return NextResponse.json({error:"Release or fulfil the reserved quantity before disabling this variant."},{status:409});if(error instanceof Error&&error.message==="OPTION_SET_EXISTS"||(error as {code?:number})?.code===11000)return NextResponse.json({error:"That option combination or SKU already exists in this workspace."},{status:409});return errorResponse(error)}finally{await session.endSession()}return NextResponse.json({variant:result},{headers:{"Cache-Control":"private, no-store"}})
}
