export type TeamInvitationEmail={tenantName:string;role:string;acceptUrl:string;expiresAt:string};
export type PasswordResetEmail={resetUrl:string;expiresAt:string};
export type RenderedEmail={subject:string;text:string;html:string};
export function escapeHtml(value:string){return value.replace(/[&<>"']/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[character]!))}
export function renderTeamInvitationEmail(data:TeamInvitationEmail):RenderedEmail{
 const cleanTenantName=data.tenantName.replace(/[\r\n]+/g," ").trim().slice(0,120),tenantName=escapeHtml(cleanTenantName),role=escapeHtml(data.role),url=escapeHtml(data.acceptUrl),expiry=new Date(data.expiresAt);const expiryText=Number.isNaN(expiry.getTime())?"within 48 hours":expiry.toLocaleString("en-US",{dateStyle:"medium",timeStyle:"short",timeZone:"UTC"});
 return{subject:`You're invited to join ${cleanTenantName}`,text:`You have been invited to join ${cleanTenantName} as ${data.role}. Accept the invitation here: ${data.acceptUrl}\n\nThis private link expires ${expiryText} UTC. If you were not expecting this invitation, you can ignore this email.`,html:`<!doctype html><html><body style="margin:0;background:#f4f6f1;color:#384437;font-family:Arial,sans-serif"><main style="max-width:560px;margin:32px auto;padding:32px;background:#fff;border:1px solid #e5e9e1;border-radius:12px"><p style="font-size:11px;letter-spacing:1.5px;color:#829178">COMMERCE DESK · WORKSPACE ACCESS</p><h1 style="font-size:25px;line-height:1.2">You're invited to join ${tenantName}</h1><p>You've been invited to join <strong>${tenantName}</strong> as <strong>${role}</strong>.</p><p><a href="${url}" style="display:inline-block;padding:13px 18px;background:#607a53;border-radius:6px;color:#fff;text-decoration:none">Accept invitation</a></p><p style="font-size:13px;color:#788276">This private link expires ${escapeHtml(expiryText)} UTC. If you were not expecting this invitation, you can ignore this email.</p><p style="font-size:11px;color:#929b90">For security, this email is intended only for the invited recipient.</p></main></body></html>`};
}

export function renderPasswordResetEmail(data:PasswordResetEmail):RenderedEmail{
 const url=escapeHtml(data.resetUrl),expiry=new Date(data.expiresAt),expiryText=Number.isNaN(expiry.getTime())?"within 30 minutes":expiry.toLocaleString("en-US",{dateStyle:"medium",timeStyle:"short",timeZone:"UTC"});
 return{subject:"Reset your CommerceDesk password",text:`A password reset was requested for your CommerceDesk account. Reset it here: ${data.resetUrl}\n\nThis private link expires ${expiryText} UTC and can only be used once. If you did not request a reset, you can ignore this email.`,html:`<!doctype html><html><body style="margin:0;background:#f4f6f1;color:#384437;font-family:Arial,sans-serif"><main style="max-width:560px;margin:32px auto;padding:32px;background:#fff;border:1px solid #e5e9e1;border-radius:12px"><p style="font-size:11px;letter-spacing:1.5px;color:#829178">COMMERCE DESK · ACCOUNT SECURITY</p><h1 style="font-size:25px;line-height:1.2">Reset your password</h1><p>A request was made to reset the password for this CommerceDesk account.</p><p><a href="${url}" style="display:inline-block;padding:13px 18px;background:#607a53;border-radius:6px;color:#fff;text-decoration:none">Set a new password</a></p><p style="font-size:13px;color:#788276">This private link expires ${escapeHtml(expiryText)} UTC and can only be used once. If you did not request a reset, you can ignore this email.</p></main></body></html>`};
}
