import {hashSessionToken} from "./secrets";
import {connectDatabase} from "./db";
import {Order} from "./models/Order";
import {Tenant} from "./models/Tenant";
import {StripeConnection} from "./models/StripeConnection";
import {Payment} from "./models/Payment";
import {nextStorefrontPaymentMinor} from "./domain/storefront-payments";
export async function loadPublicOrderReceipt(token:string){if(!/^[A-Za-z0-9_-]{43}$/.test(token))return null;await connectDatabase();const order=await Order.findOne({receiptTokenHash:hashSessionToken(token),source:{$in:["storefront","quote"]},receiptTokenExpiresAt:{$gt:new Date()}}).select("orderNumber customerSnapshot lines currency subtotalMinor taxMinor shippingFeeMinor totalMinor depositDueMinor source status paymentStatus fulfilmentStatus fulfilmentMethod shippingAddress paymentMethod paymentInstructionsSnapshot storefrontTermsSnapshot storefrontPrivacySnapshot reservationExpiresAt cancelReason createdAt tenantId").lean();if(!order)return null;const[tenant,stripe,paymentMethods,totals]=await Promise.all([Tenant.findOne({_id:order.tenantId}).select("name slug storefrontContactEmail").lean(),StripeConnection.findOne({tenantId:order.tenantId,status:"connected",chargesEnabled:true}).select("_id").lean(),Payment.distinct("method",{tenantId:order.tenantId,orderId:order._id,direction:"capture"}),Payment.aggregate<{direction:string;total:number}>([{$match:{tenantId:order.tenantId,orderId:order._id}},{$group:{_id:"$direction",total:{$sum:"$amountMinor"}}}])]);if(!tenant)return null;const captured=totals.find(item=>item.direction==="capture")?.total??0,refunded=totals.find(item=>item.direction==="refund")?.total??0,depositDueMinor=order.depositDueMinor||order.totalMinor;let amountDueNow=0;try{amountDueNow=nextStorefrontPaymentMinor(order.totalMinor,captured,refunded,depositDueMinor)}catch{amountDueNow=0}return{order:{orderNumber:order.orderNumber,source:order.source,customerName:order.customerSnapshot?.name||"Customer",lines:order.lines.map(line=>({name:line.name,kind:line.kind,sku:line.sku,quantity:line.quantity,discountPercentBps:line.discountPercentBps||0,discountAmountMinor:line.discountAmountMinor||0,grossMinor:line.grossMinor})),currency:order.currency,subtotalMinor:order.subtotalMinor,taxMinor:order.taxMinor,shippingFeeMinor:order.shippingFeeMinor,totalMinor:order.totalMinor,amountDueNow,depositDueMinor,depositRemaining:captured-refunded<depositDueMinor,status:order.status,paymentStatus:order.paymentStatus,fulfilmentStatus:order.fulfilmentStatus,fulfilmentMethod:order.fulfilmentMethod,shippingAddress:order.shippingAddress,paymentMethod:order.paymentMethod,paymentInstructions:order.paymentInstructionsSnapshot,terms:order.storefrontTermsSnapshot,privacy:order.storefrontPrivacySnapshot,reservationExpiresAt:order.reservationExpiresAt,cancelReason:order.cancelReason,createdAt:order.createdAt},store:{name:tenant.name,slug:tenant.slug,contactEmail:tenant.storefrontContactEmail||null},stripeReady:Boolean(stripe),paymentMethods:paymentMethods as string[]}}

