import {randomBytes} from "node:crypto";
import mongoose from "mongoose";
import {NextResponse} from "next/server";
import {z} from "zod";
import {requireTenantAccess} from "@/server/tenant-scope";
import {isSameOrigin,readJsonLimited} from "@/server/request-security";
import {Customer} from "@/server/models/Customer";
import {Deal} from "@/server/models/Deal";
import {DealEvent} from "@/server/models/DealEvent";
import {AuditEvent} from "@/server/models/AuditEvent";
import {Tenant} from "@/server/models/Tenant";
import {User} from "@/server/models/User";
import {Membership} from "@/server/models/Membership";
import {salesStagesFor} from "@/server/domain/deals";

export const dynamic="force-dynamic";
const createSchema=z.object({customerId:z.string().regex(/^[a-f\d]{24}$/i),title:z.string().trim().min(2).max(180),valueMinor:z.number().int().safe().min(0).max(Number.MAX_SAFE_INTEGER).default(0),dueAt:z.string().datetime({offset:true}).nullable().optional(),ownerId:z.string().regex(/^[a-f\d]{24}$/i).optional()}).strict();
function failure(error:unknown){if(error instanceof Error&&error.message==="PERMISSION_DENIED")return NextResponse.json({error:"You do not have permission to view or manage sales deals."},{status:403});return NextResponse.json({error:"Sales pipeline is temporarily unavailable."},{status:503})}
function escapeRegex(value:string){return value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}
export async function GET(request:Request){
 let access;try{access=await requireTenantAccess("deals:write")}catch(error){return failure(error)}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});const url=new URL(request.url),stage=url.searchParams.get("stage"),query=(url.searchParams.get("q")||"").trim().slice(0,100),page=Math.max(1,Number.parseInt(url.searchParams.get("page")||"1",10)||1),limit=Math.min(100,Math.max(1,Number.parseInt(url.searchParams.get("limit")||"100",10)||100));
 const filter:Record<string,unknown>={tenantId:access.scope.tenantId};if(access.scope.role==="sales")filter.ownerId=access.scope.userId;try{const tenant=await Tenant.findById(access.scope.tenantId).select("salesStages baseCurrency").lean(),stages=salesStagesFor(tenant?.salesStages as {key:string;label:string;position:number}[]|undefined);if(stage){if(!stages.some(item=>item.key===stage))return NextResponse.json({error:"Choose a valid pipeline stage."},{status:400});filter.stage=stage}if(query){const rx={$regex:escapeRegex(query),$options:"i"},matching=await Customer.find({tenantId:access.scope.tenantId,$or:[{name:rx},{company:rx},{email:rx}]}).select("_id").limit(500).lean();filter.$or=[{title:rx},{customerId:{$in:matching.map(customer=>customer._id)}}]}const[deals,total]=await Promise.all([Deal.find(filter).sort({updatedAt:-1,_id:1}).skip((page-1)*limit).limit(limit).lean(),Deal.countDocuments(filter)]);const[customers,users]=await Promise.all([Customer.find({tenantId:access.scope.tenantId,_id:{$in:deals.map(deal=>deal.customerId)}}).select("name company email").lean(),User.find({_id:{$in:deals.map(deal=>deal.ownerId)}}).select("name").lean()]);const byId=new Map(customers.map(customer=>[String(customer._id),customer])),owners=new Map(users.map(user=>[String(user._id),user.name]));return NextResponse.json({deals:deals.map(deal=>({...deal,_id:String(deal._id),customer:byId.get(String(deal.customerId))||null,ownerName:owners.get(String(deal.ownerId))||"Former team member"})),stages,currency:tenant?.baseCurrency||access.tenant.baseCurrency,total,page,limit},{headers:{"Cache-Control":"private, no-store"}})}catch(error){return failure(error)}
}
export async function POST(request:Request){
 if(!isSameOrigin(request))return NextResponse.json({error:"Request origin could not be verified."},{status:403});let access;try{access=await requireTenantAccess("deals:write")}catch(error){return failure(error)}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});const body=await readJsonLimited(request,12000);if(body.kind==="too-large")return NextResponse.json({error:"Request is too large."},{status:413});const parsed=createSchema.safeParse(body.kind==="ok"?body.value:null);if(!parsed.success)return NextResponse.json({error:"Choose a customer and enter a deal title and value."},{status:400});if(parsed.data.ownerId&&access.scope.role!=="owner")return NextResponse.json({error:"Only owners can assign a deal to another teammate."},{status:403});const customer=await Customer.findOne({_id:parsed.data.customerId,tenantId:access.scope.tenantId}).select("_id").lean();if(!customer)return NextResponse.json({error:"Customer not found in this workspace."},{status:404});
 try{const session=await mongoose.startSession();let created:unknown;try{await session.withTransaction(async()=>{const tenant=await Tenant.findById(access!.scope.tenantId).select("baseCurrency salesStages").session(session).lean(),stages=salesStagesFor(tenant?.salesStages as {key:string;label:string;position:number}[]|undefined);if(!stages.some(item=>item.key==="new")||!tenant)throw new Error("NEW_STAGE_MISSING");let ownerId=access!.scope.userId;if(parsed.data.ownerId){const[member,activeUser]=await Promise.all([Membership.findOne({tenantId:access!.scope.tenantId,userId:parsed.data.ownerId,revokedAt:null}).session(session).lean(),User.findOne({_id:parsed.data.ownerId,disabledAt:null}).select("_id").session(session).lean()]);if(!member||!activeUser)throw new Error("OWNER_NOT_FOUND");ownerId=parsed.data.ownerId}const[deal]=await Deal.create([{tenantId:access!.scope.tenantId,customerId:customer._id,title:parsed.data.title,valueMinor:parsed.data.valueMinor,currency:tenant.baseCurrency,ownerId,dueAt:parsed.data.dueAt?new Date(parsed.data.dueAt):null,stage:"new"}],{session});await DealEvent.create([{tenantId:access!.scope.tenantId,dealId:deal._id,actorId:access!.scope.userId,action:"created",details:{stage:deal.stage,valueMinor:deal.valueMinor,ownerId:String(deal.ownerId),dueAt:deal.dueAt}}],{session});await AuditEvent.create([{tenantId:access!.scope.tenantId,actorId:access!.scope.userId,action:"deal.created",entityType:"deal",entityId:String(deal._id),requestId:randomBytes(12).toString("hex"),metadata:{customerId:String(customer._id),stage:deal.stage,ownerId:String(deal.ownerId)}}],{session});created=deal.toObject()})}finally{await session.endSession()}return NextResponse.json({deal:created},{status:201,headers:{"Cache-Control":"private, no-store"}})}catch(error){if(error instanceof Error&&error.message==="OWNER_NOT_FOUND")return NextResponse.json({error:"The chosen owner is not an active member of this workspace."},{status:400});return failure(error)}
}
