import {randomBytes} from "node:crypto";
import mongoose from "mongoose";
import {NextResponse} from "next/server";
import {z} from "zod";
import {requireTenantAccess} from "@/server/tenant-scope";
import {isSameOrigin,readJsonLimited} from "@/server/request-security";
import {Customer} from "@/server/models/Customer";
import {Conversation} from "@/server/models/Conversation";
import {ConversationMessage} from "@/server/models/ConversationMessage";
import {AuditEvent} from "@/server/models/AuditEvent";
import {newSessionToken,hashSessionToken} from "@/server/secrets";
const createSchema=z.object({customerId:z.string().regex(/^[a-f\d]{24}$/i),subject:z.string().trim().max(160).default("")}).strict();
function fail(error:unknown){if(error instanceof Error&&error.message==="PERMISSION_DENIED")return NextResponse.json({error:"Inbox access is not permitted."},{status:403});return NextResponse.json({error:"The inbox is temporarily unavailable."},{status:503})}
export const dynamic="force-dynamic";
export async function GET(request:Request){let access;try{access=await requireTenantAccess("conversations:reply")}catch(error){return fail(error)}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});const url=new URL(request.url),status=url.searchParams.get("status")||"active",assigned=url.searchParams.get("assigned")||"all",page=Math.max(1,Number.parseInt(url.searchParams.get("page")||"1",10)||1),limit=Math.min(100,Math.max(1,Number.parseInt(url.searchParams.get("limit")||"50",10)||50));const filter:Record<string,unknown>={tenantId:access.scope.tenantId};if(["open","awaiting_customer","closed"].includes(status))filter.status=status;else if(status==="active")filter.status={$ne:"closed"};if(assigned==="mine")filter.assignedTo=new mongoose.Types.ObjectId(access.scope.userId);if(assigned==="unassigned")filter.assignedTo=null;try{const[conversations,total]=await Promise.all([Conversation.find(filter).sort({lastMessageAt:-1,updatedAt:-1,_id:-1}).skip((page-1)*limit).limit(limit).populate({path:"customerId",match:{tenantId:access.scope.tenantId},select:"name email phone"}).lean(),Conversation.countDocuments(filter)]);return NextResponse.json({conversations,total,page,pageCount:Math.ceil(total/limit)},{headers:{"Cache-Control":"private, no-store"}})}catch(error){return fail(error)}}
export async function POST(request:Request){if(!isSameOrigin(request))return NextResponse.json({error:"Request origin could not be verified."},{status:403});let access;try{access=await requireTenantAccess("conversations:reply")}catch(error){return fail(error)}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});const limited=await readJsonLimited(request,4096);if(limited.kind==="too-large")return NextResponse.json({error:"Request is too large."},{status:413});const parsed=createSchema.safeParse(limited.kind==="ok"?limited.value:null);if(!parsed.success)return NextResponse.json({error:"Choose an active customer and provide a valid subject."},{status:400});const session=await mongoose.startSession();let result:unknown,sharePath="";try{await session.withTransaction(async()=>{const customer=await Customer.findOne({_id:parsed.data.customerId,tenantId:access.scope.tenantId,status:{$ne:"archived"}}).select("_id").session(session).lean();if(!customer)throw new Error("CUSTOMER_NOT_FOUND");const token=newSessionToken(),expiresAt=new Date(Date.now()+30*24*60*60*1000);const[conversation]=await Conversation.create([{tenantId:access.scope.tenantId,customerId:customer._id,channel:"web",subject:parsed.data.subject,status:"open",assignedTo:access.scope.userId,humanTakeover:true,takeoverBy:access.scope.userId,takeoverAt:new Date(),labels:[],customerUnreadCount:0,staffUnreadCount:0,accessTokenHash:hashSessionToken(token),accessExpiresAt:expiresAt,createdBy:access.scope.userId}],{session});await AuditEvent.create([{tenantId:access.scope.tenantId,actorId:access.scope.userId,action:"conversation.created",entityType:"conversation",entityId:String(conversation._id),requestId:randomBytes(12).toString("hex"),metadata:{channel:"web",customerId:String(customer._id),accessExpiresAt:expiresAt.toISOString()}}],{session});const safe=conversation.toObject() as Record<string,unknown>;delete safe.accessTokenHash;result=safe;sharePath=`/conversation/${encodeURIComponent(token)}`})}catch(error){if(error instanceof Error&&error.message==="CUSTOMER_NOT_FOUND")return NextResponse.json({error:"Choose an active customer in this workspace."},{status:404});return fail(error)}finally{await session.endSession()}return NextResponse.json({conversation:result,sharePath},{status:201,headers:{"Cache-Control":"private, no-store"}})}
