import {randomBytes} from "node:crypto";
import {NextResponse} from "next/server";
import {z} from "zod";
import {requireTenantAccess} from "@/server/tenant-scope";
import {Tenant} from "@/server/models/Tenant";
import {CatalogueItem} from "@/server/models/CatalogueItem";
import {AuditEvent} from "@/server/models/AuditEvent";
import {isSameOrigin,readJsonLimited} from "@/server/request-security";
import {hasValidEncryptionKey} from "@/server/secrets";
export const dynamic="force-dynamic";
const updateSchema=z.object({storefrontEnabled:z.boolean(),storefrontDescription:z.string().trim().max(700),storefrontTerms:z.string().trim().max(3000),storefrontPrivacy:z.string().trim().max(3000),storefrontContactEmail:z.union([z.string().trim().email().max(254),z.literal("")]),deliveryEnabled:z.boolean(),deliveryFlatFeeMinor:z.number().int().safe().min(0).max(Number.MAX_SAFE_INTEGER),deliveryTaxRateBps:z.number().int().min(0).max(100000),deliveryTaxMode:z.enum(["inclusive","exclusive"]),pickupEnabled:z.boolean(),bankTransferEnabled:z.boolean(),bankTransferInstructions:z.string().trim().max(1000),storefrontPaymentMode:z.enum(["full","deposit"]),storefrontDepositPercentBps:z.number().int().min(1).max(9999),cashOnPickupEnabled:z.boolean(),reservationMinutes:z.number().int().min(5).max(1440)}).strict().superRefine((value,context)=>{
 if(value.storefrontEnabled&&(value.storefrontTerms.length<40||value.storefrontPrivacy.length<40))context.addIssue({code:"custom",path:["storefrontTerms"],message:"Publish store terms and a privacy notice before opening the storefront."});
 if(value.storefrontEnabled&&!(value.deliveryEnabled||value.pickupEnabled))context.addIssue({code:"custom",path:["pickupEnabled"],message:"Enable delivery or pickup before opening the storefront."});
 if(value.storefrontEnabled&&value.deliveryEnabled&&!value.bankTransferEnabled)context.addIssue({code:"custom",path:["bankTransferEnabled"],message:"Delivery checkout requires bank transfer while online card processing is unavailable."});
 if(value.storefrontEnabled&&!(value.bankTransferEnabled||value.cashOnPickupEnabled))context.addIssue({code:"custom",path:["bankTransferEnabled"],message:"Enable at least one manual payment method before opening the storefront."});
 if(value.storefrontEnabled&&value.bankTransferEnabled&&!value.bankTransferInstructions.trim())context.addIssue({code:"custom",path:["bankTransferInstructions"],message:"Add the bank transfer instructions shown at checkout."});
 if(value.cashOnPickupEnabled&&!value.pickupEnabled)context.addIssue({code:"custom",path:["cashOnPickupEnabled"],message:"Cash on pickup requires pickup to be enabled."});
 if(value.storefrontPaymentMode==="deposit"&&!value.bankTransferEnabled)context.addIssue({code:"custom",path:["storefrontPaymentMode"],message:"Advance deposits require bank transfer instructions. Stripe can also be offered from the private receipt."});
});
function failure(error:unknown){if(error instanceof Error&&error.message==="PERMISSION_DENIED")return NextResponse.json({error:"Only an authorised workspace administrator can change store settings."},{status:403});return NextResponse.json({error:"Store settings are temporarily unavailable."},{status:503})}
function present(tenant:Record<string,unknown>){return{storefrontEnabled:Boolean(tenant.storefrontEnabled),storefrontDescription:String(tenant.storefrontDescription||""),storefrontTerms:String(tenant.storefrontTerms||""),storefrontPrivacy:String(tenant.storefrontPrivacy||""),storefrontContactEmail:typeof tenant.storefrontContactEmail==="string"?tenant.storefrontContactEmail:"",deliveryEnabled:Boolean(tenant.deliveryEnabled),deliveryFlatFeeMinor:Number(tenant.deliveryFlatFeeMinor||0),deliveryTaxRateBps:Number(tenant.deliveryTaxRateBps||0),deliveryTaxMode:String(tenant.deliveryTaxMode||"exclusive"),pickupEnabled:Boolean(tenant.pickupEnabled),bankTransferEnabled:Boolean(tenant.bankTransferEnabled),bankTransferInstructions:String(tenant.bankTransferInstructions||""),storefrontPaymentMode:String(tenant.storefrontPaymentMode||"full"),storefrontDepositPercentBps:Number(tenant.storefrontDepositPercentBps||3000),cashOnPickupEnabled:Boolean(tenant.cashOnPickupEnabled),reservationMinutes:Number(tenant.reservationMinutes||30),storeSlug:String(tenant.slug),storeName:String(tenant.name),currency:String(tenant.baseCurrency),commerceMode:String(tenant.commerceMode)}}
export async function GET(){let access;try{access=await requireTenantAccess("tenant:settings")}catch(error){return failure(error)}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});try{const tenant=await Tenant.findById(access.scope.tenantId).lean();if(!tenant)return NextResponse.json({error:"Workspace not found."},{status:404});return NextResponse.json({settings:present(tenant as unknown as Record<string,unknown>)},{headers:{"Cache-Control":"private, no-store"}})}catch(error){return failure(error)}}
export async function PATCH(request:Request){if(!isSameOrigin(request))return NextResponse.json({error:"Request origin could not be verified."},{status:403});let access;try{access=await requireTenantAccess("tenant:settings")}catch(error){return failure(error)}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});if(Number(request.headers.get("content-length")||0)>12000)return NextResponse.json({error:"Request is too large."},{status:413});const limitedJsonBody=await readJsonLimited(request,24000);if(limitedJsonBody.kind==="too-large")return NextResponse.json({error:"Request is too large."},{status:413});const parsed=updateSchema.safeParse(limitedJsonBody.kind==="ok"?limitedJsonBody.value:null);if(!parsed.success)return NextResponse.json({error:"Review the store settings and payment instructions.",issues:parsed.error.issues.map(issue=>({field:issue.path.join("."),message:issue.message}))},{status:400});if(parsed.data.storefrontEnabled&&!hasValidEncryptionKey())return NextResponse.json({error:"Set a valid APP_ENCRYPTION_KEY before opening the store. It protects private customer receipt links."},{status:503});if(access.tenant.commerceMode!=="native"&&parsed.data.storefrontEnabled)return NextResponse.json({error:"A WooCommerce-connected tenant uses its existing storefront. CommerceDesk will not publish a second editable store."},{status:409});if(parsed.data.storefrontEnabled&&await CatalogueItem.countDocuments({tenantId:access.scope.tenantId,status:"active",kind:"physical",storefrontPublished:true})===0)return NextResponse.json({error:"Publish at least one active physical product before opening the public storefront."},{status:409});try{const tenant=await Tenant.findOneAndUpdate({_id:access.scope.tenantId},{$set:{...parsed.data,storefrontContactEmail:parsed.data.storefrontContactEmail.toLowerCase()||null}},{new:true,runValidators:true}).lean();if(!tenant)return NextResponse.json({error:"Workspace not found."},{status:404});await AuditEvent.create({tenantId:access.scope.tenantId,actorId:access.scope.userId,action:"store.settings_updated",entityType:"tenant",entityId:String(tenant._id),requestId:randomBytes(12).toString("hex"),metadata:{fields:Object.keys(parsed.data),storefrontEnabled:tenant.storefrontEnabled}});return NextResponse.json({settings:present(tenant as unknown as Record<string,unknown>)},{headers:{"Cache-Control":"private, no-store"}})}catch(error){return failure(error)}}





