import assert from "node:assert/strict";
import {randomBytes,randomUUID} from "node:crypto";
import mongoose from "mongoose";
import {connectDatabase} from "../src/server/db.ts";
import {Tenant} from "../src/server/models/Tenant.ts";
import {User} from "../src/server/models/User.ts";
import {Membership} from "../src/server/models/Membership.ts";
import {Session} from "../src/server/models/Session.ts";
import {SmtpConnection} from "../src/server/models/SmtpConnection.ts";
import {EmailDelivery} from "../src/server/models/EmailDelivery.ts";
import {PasswordResetToken} from "../src/server/models/PasswordResetToken.ts";
import {AuditEvent} from "../src/server/models/AuditEvent.ts";
import {encryptSecret,hashPassword,hashSessionToken,verifyPassword} from "../src/server/secrets.ts";
import {queuePasswordResetEmail,sweepEmailDeliveries} from "../src/server/email-delivery.ts";
import {completePasswordReset} from "../src/server/password-reset.ts";
function assertDisposableUri(uri:string){const parsed=new URL(uri);assert.ok(["127.0.0.1","localhost","::1"].includes(parsed.hostname),"MONGODB_TEST_URI must use loopback; refusing a remote database");assert.match(parsed.pathname,/_test(?:$|\?)/i,"MONGODB_TEST_URI database name must include _test")}
async function run(){const uri=process.env.MONGODB_TEST_URI;if(!uri)throw new Error("Set MONGODB_TEST_URI to a disposable loopback replica-set MongoDB database whose name includes _test.");assertDisposableUri(uri);process.env.MONGODB_URI=uri;process.env.APP_URL="http://localhost:3000";process.env.APP_ENCRYPTION_KEY=randomBytes(32).toString("base64url");await connectDatabase();const suffix=`${Date.now()}-${randomUUID().slice(0,8)}`,slug=`reset-test-${suffix.toLowerCase()}`;let userId:string|undefined,tenantId:string|undefined;try{
 const tenant=await Tenant.create({name:`Reset Acceptance ${suffix}`,slug,deploymentMode:"standalone",commerceMode:"native",baseCurrency:"USD",timezone:"UTC"});tenantId=String(tenant._id);await SmtpConnection.create({tenantId,host:"smtp.example.com",port:587,secure:false,username:"sender@example.com",passwordEncrypted:encryptSecret("test-app-password"),fromName:"Example shop",fromEmail:"security@example.com",status:"verified",lastVerifiedAt:new Date()});
 const originalPassword="old password value",originalHash=await hashPassword(originalPassword),mfaSecret=encryptSecret("existing MFA secret"),user=await User.create({name:"Reset User",email:`reset-${suffix}@example.test`,passwordHash:originalHash,mfaSecretEncrypted:mfaSecret,mfaEnabledAt:new Date(),mfaRecoveryHashes:["recovery-hash"],mfaLastCounter:42});userId=String(user._id);await Membership.create({tenantId,userId,role:"owner",permissions:[],revokedAt:null});await Session.create({tenantId,userId,tokenHash:hashSessionToken(randomBytes(32).toString("base64url")),expiresAt:new Date(Date.now()+86_400_000)});
 assert.equal(await queuePasswordResetEmail({userId,tenantId,recipient:user.email}),true);const reset=await PasswordResetToken.findOne({userId,usedAt:null}).select("+tokenHash").lean();assert.ok(reset);assert.equal(reset.tokenHash.length,64);const delivery=await EmailDelivery.findOne({tenantId,template:"password_reset"}).select("+payloadEncrypted").lean();assert.ok(delivery);const payload=JSON.parse((await import("../src/server/secrets.ts")).decryptSecret(delivery.payloadEncrypted)) as {resetUrl:string;expiresAt:string};const resetToken=new URL(payload.resetUrl).hash.slice(1);assert.match(resetToken,/^[A-Za-z0-9_-]{43}$/);assert.equal(delivery.payloadEncrypted.includes(resetToken),false,"reset URL must be encrypted in the email outbox");assert.ok(new Date(payload.expiresAt).getTime()>Date.now());
 let mailed=0;await sweepEmailDeliveries(12,{send:(async(_config:unknown,message:{to:string;subject:string;html:string})=>{mailed++;assert.equal(message.to,user.email);assert.match(message.subject,/reset your CommerceDesk password/i);assert.match(message.html,/expires/);return{messageId:"reset-accepted",accepted:[message.to]}}) as never});assert.equal(mailed,1);const sent=await EmailDelivery.findById(delivery._id).lean();assert.equal(sent?.status,"sent");
 const changed=await completePasswordReset(resetToken,"new password with twelve chars");assert.equal(changed,true);assert.equal(await verifyPassword("new password with twelve chars",(await User.findById(userId).select("+passwordHash").lean())!.passwordHash),true);assert.equal(await verifyPassword(originalPassword,(await User.findById(userId).select("+passwordHash").lean())!.passwordHash),false);const stored=await User.findById(userId).select("+mfaSecretEncrypted +mfaRecoveryHashes").lean();assert.equal(stored?.mfaEnabledAt?.getTime(),user.mfaEnabledAt?.getTime());assert.equal(stored?.mfaSecretEncrypted,mfaSecret);assert.deepEqual(stored?.mfaRecoveryHashes,["recovery-hash"]);assert.equal(await Session.countDocuments({userId,revokedAt:null}),0);assert.equal(await AuditEvent.countDocuments({tenantId,action:"account.password_reset_completed"}),1);assert.equal(await completePasswordReset(resetToken,"another new password"),false,"a used reset token cannot be reused");
 const expired=`${randomBytes(32).toString("base64url")}`;await PasswordResetToken.create({userId,tokenHash:hashSessionToken(expired),expiresAt:new Date(Date.now()-1000),usedAt:null});assert.equal(await completePasswordReset(expired,"new password with twelve chars"),false,"expired token is rejected");
 console.log("PASSWORD_RESET_ACCEPTANCE_OK: encrypted email outbox, mocked SMTP acceptance, 30-minute token, one-time consumption, password hash replacement, all-session revocation, MFA preservation, and audit event");
 }finally{if(userId){await PasswordResetToken.deleteMany({userId});await Session.deleteMany({userId});await Membership.deleteMany({userId});await AuditEvent.deleteMany({tenantId,entityId:userId})}if(tenantId){await EmailDelivery.deleteMany({tenantId});await SmtpConnection.deleteMany({tenantId});await Tenant.deleteOne({_id:tenantId})}await mongoose.disconnect()}}
run().catch(error=>{console.error(error);process.exitCode=1});
