import {randomBytes} from "node:crypto";
import mongoose from "mongoose";
import {NextResponse} from "next/server";
import {z} from "zod";
import {requireTenantAccess} from "@/server/tenant-scope";
import {isSameOrigin,readJsonLimited} from "@/server/request-security";
import {Deal} from "@/server/models/Deal";
import {DealTask} from "@/server/models/DealTask";
import {DealEvent} from "@/server/models/DealEvent";
import {AuditEvent} from "@/server/models/AuditEvent";
const schema=z.object({action:z.enum(["complete","reopen"])}).strict();
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){if(!isSameOrigin(request))return NextResponse.json({error:"Request origin could not be verified."},{status:403});let access;try{access=await requireTenantAccess("deals:write")}catch(error){if(error instanceof Error&&error.message==="PERMISSION_DENIED")return NextResponse.json({error:"You do not have permission to update this task."},{status:403});return NextResponse.json({error:"Deal task is temporarily unavailable."},{status:503})}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});const{id}=await params;if(!/^[a-f\d]{24}$/i.test(id))return NextResponse.json({error:"Task not found."},{status:404});const body=await readJsonLimited(request,8000);if(body.kind==="too-large")return NextResponse.json({error:"Request is too large."},{status:413});const parsed=schema.safeParse(body.kind==="ok"?body.value:null);if(!parsed.success)return NextResponse.json({error:"Choose a valid task action."},{status:400});const tenantId=access.scope.tenantId,session=await mongoose.startSession();let result:unknown;try{await session.withTransaction(async()=>{const task=await DealTask.findOne({_id:id,tenantId}).session(session);if(!task)throw new Error("TASK_NOT_FOUND");const filter:Record<string,unknown>={_id:task.dealId,tenantId};if(access!.scope.role==="sales")filter.ownerId=access!.scope.userId;const deal=await Deal.findOne(filter).session(session);if(!deal)throw new Error("DEAL_NOT_FOUND");const next=parsed.data.action==="complete"?"completed":"open";if(task.status===next){result=task.toObject();return}const before=task.status;task.status=next;if(next==="completed"){task.completedAt=new Date();task.completedBy=new mongoose.Types.ObjectId(access!.scope.userId)}else{task.set("completedAt",null);task.set("completedBy",null)}task.version+=1;await task.save({session});const details={taskId:String(task._id),from:before,to:next};await DealEvent.create([{tenantId,dealId:deal._id,actorId:access!.scope.userId,action:`task_${parsed.data.action}`,details}],{session});await AuditEvent.create([{tenantId,actorId:access!.scope.userId,action:`deal.task_${parsed.data.action}`,entityType:"deal",entityId:String(deal._id),requestId:randomBytes(12).toString("hex"),metadata:details}],{session});result=task.toObject()})}catch(error){if(error instanceof Error&&error.message==="TASK_NOT_FOUND")return NextResponse.json({error:"Task not found."},{status:404});if(error instanceof Error&&error.message==="DEAL_NOT_FOUND")return NextResponse.json({error:"Deal not found."},{status:404});return NextResponse.json({error:"Deal task is temporarily unavailable."},{status:503})}finally{await session.endSession()}return NextResponse.json({task:result},{headers:{"Cache-Control":"private, no-store"}})}
