import {NextResponse} from "next/server";
import {requireTenantAccess} from "@/server/tenant-scope";
import {Tenant} from "@/server/models/Tenant";
import {CatalogueItem} from "@/server/models/CatalogueItem";
import {ServiceResource} from "@/server/models/ServiceResource";
import {Appointment} from "@/server/models/Appointment";
import {hasIntervalCapacity,isValidLocalDate,slotsForLocalDate} from "@/server/domain/appointments";

export const dynamic="force-dynamic";
export async function GET(request:Request){
 let access;try{access=await requireTenantAccess("appointments:write")}catch(error){if(error instanceof Error&&error.message==="PERMISSION_DENIED")return NextResponse.json({error:"You do not have permission to view appointment availability."},{status:403});return NextResponse.json({error:"Appointment availability is temporarily unavailable."},{status:503})}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});
 const url=new URL(request.url),serviceId=url.searchParams.get("serviceId")||"",date=url.searchParams.get("date")||"";if(!/^[a-f\d]{24}$/i.test(serviceId)||!isValidLocalDate(date))return NextResponse.json({error:"Choose a valid service and date."},{status:400});
 try{const[tenant,service,resources]=await Promise.all([Tenant.findById(access.scope.tenantId).select("appointmentsEnabled appointmentHours appointmentClosures timezone").lean(),CatalogueItem.findOne({_id:serviceId,tenantId:access.scope.tenantId,status:"active",kind:"service",serviceDurationMinutes:{$gte:5}}).lean(),ServiceResource.find({tenantId:access.scope.tenantId,active:true}).sort({name:1}).lean()]);if(!tenant?.appointmentsEnabled)return NextResponse.json({error:"Appointments are not enabled for this workspace."},{status:409});if(!service)return NextResponse.json({error:"That service is unavailable."},{status:404});const weekday=new Date(`${date}T12:00:00.000Z`).getUTCDay(),hours=tenant.appointmentHours.find(day=>day.weekday===weekday);if(!hours)return NextResponse.json({date,timezone:tenant.timezone,resources:[]},{headers:{"Cache-Control":"private, no-store"}});const closures=tenant.appointmentClosures;const results=await Promise.all(resources.map(async resource=>{const candidates=slotsForLocalDate({date,timeZone:tenant.timezone,openMinute:hours.openMinute,closeMinute:hours.closeMinute,durationMinutes:service.serviceDurationMinutes!,bufferBeforeMinutes:resource.bufferBeforeMinutes,bufferAfterMinutes:resource.bufferAfterMinutes});const earliest=candidates[0]?.bufferedStartsAt,latest=candidates.at(-1)?.bufferedEndsAt;if(!earliest||!latest)return{resource:{id:String(resource._id),name:resource.name},slots:[]};const existing=await Appointment.find({tenantId:access!.scope.tenantId,resourceId:resource._id,status:{ $in:["held","confirmed"]},$or:[{status:"confirmed"},{holdExpiresAt:{$gt:new Date()}}],bufferedStartsAt:{$lt:latest},bufferedEndsAt:{$gt:earliest}}).select("bufferedStartsAt bufferedEndsAt").lean();const slots=candidates.filter(slot=>!closures.some(c=>slot.bufferedStartsAt<c.endsAt&&slot.bufferedEndsAt>c.startsAt)&&hasIntervalCapacity({startAt:slot.bufferedStartsAt,endAt:slot.bufferedEndsAt},existing.map(a=>({startAt:a.bufferedStartsAt,endAt:a.bufferedEndsAt})),resource.capacity)).map(slot=>({startsAt:slot.startsAt.toISOString(),endsAt:slot.endsAt.toISOString(),label:slot.label,offset:slot.offsetLabel}));return{resource:{id:String(resource._id),name:resource.name},slots}}));return NextResponse.json({date,timezone:tenant.timezone,service:{id:String(service._id),name:service.name,durationMinutes:service.serviceDurationMinutes},resources:results},{headers:{"Cache-Control":"private, no-store"}})}catch{return NextResponse.json({error:"Appointment availability is temporarily unavailable."},{status:503})}
}
