import {createHash,randomBytes} from "node:crypto";
import mongoose from "mongoose";
import {NextResponse} from "next/server";
import {z} from "zod";
import {requireTenantAccess} from "@/server/tenant-scope";
import {isSameOrigin,readJsonLimited} from "@/server/request-security";
import {Tenant} from "@/server/models/Tenant";
import {Customer} from "@/server/models/Customer";
import {CatalogueItem} from "@/server/models/CatalogueItem";
import {ServiceResource} from "@/server/models/ServiceResource";
import {Appointment} from "@/server/models/Appointment";
import {AppointmentEvent} from "@/server/models/AppointmentEvent";
import {AuditEvent} from "@/server/models/AuditEvent";
import {hasIntervalCapacity,isValidLocalDate,localDateInZone,slotsForLocalDate} from "@/server/domain/appointments";

export const dynamic="force-dynamic";
const createSchema=z.object({customerId:z.string().regex(/^[a-f\d]{24}$/i),serviceId:z.string().regex(/^[a-f\d]{24}$/i),resourceId:z.string().regex(/^[a-f\d]{24}$/i),startsAt:z.string().datetime({offset:true})}).strict();
function fail(error:unknown){if(error instanceof Error&&error.message==="PERMISSION_DENIED")return NextResponse.json({error:"You do not have permission to manage appointments."},{status:403});return NextResponse.json({error:"Appointments are temporarily unavailable."},{status:503})}
export async function GET(request:Request){let access;try{access=await requireTenantAccess("appointments:write")}catch(error){return fail(error)}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});const url=new URL(request.url),from=new Date(url.searchParams.get("from")||Date.now()-7*86400000),to=new Date(url.searchParams.get("to")||Date.now()+30*86400000);if(!Number.isFinite(from.getTime())||!Number.isFinite(to.getTime())||from>=to||to.getTime()-from.getTime()>93*86400000)return NextResponse.json({error:"Choose a valid date range of 93 days or less."},{status:400});try{const appointments=await Appointment.find({tenantId:access.scope.tenantId,startsAt:{$gte:from,$lt:to}}).sort({startsAt:1}).limit(500).lean();return NextResponse.json({appointments},{headers:{"Cache-Control":"private, no-store"}})}catch(error){return fail(error)}}
export async function POST(request:Request){
 if(!isSameOrigin(request))return NextResponse.json({error:"Request origin could not be verified."},{status:403});let access;try{access=await requireTenantAccess("appointments:write")}catch(error){return fail(error)}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});
 const key=request.headers.get("idempotency-key")||"";if(key.length<8||key.length>120)return NextResponse.json({error:"A valid Idempotency-Key header is required."},{status:400});if(Number(request.headers.get("content-length")||0)>12000)return NextResponse.json({error:"Request is too large."},{status:413});const body=await readJsonLimited(request,16000);if(body.kind==="too-large")return NextResponse.json({error:"Request is too large."},{status:413});const parsed=createSchema.safeParse(body.kind==="ok"?body.value:null);if(!parsed.success)return NextResponse.json({error:"Choose a customer, service, resource and available start time."},{status:400});const start=new Date(parsed.data.startsAt),fingerprint=createHash("sha256").update(JSON.stringify({...parsed.data,startsAt:start.toISOString()})).digest("hex"),tenantId=access.scope.tenantId;
 try{const replay=await Appointment.findOne({tenantId,idempotencyKey:key}).select("+requestFingerprint").lean();if(replay){if(replay.requestFingerprint!==fingerprint)return NextResponse.json({error:"That idempotency key was already used for another booking."},{status:409});return NextResponse.json({appointment:replay},{status:200,headers:{"Cache-Control":"private, no-store"}})}
 const[tenant,customer,service]=await Promise.all([Tenant.findById(tenantId).select("appointmentsEnabled appointmentHours appointmentClosures appointmentCancellationHours timezone").lean(),Customer.findOne({_id:parsed.data.customerId,tenantId}).lean(),CatalogueItem.findOne({_id:parsed.data.serviceId,tenantId,status:"active",kind:"service",serviceDurationMinutes:{$gte:5}}).lean()]);if(!tenant?.appointmentsEnabled)return NextResponse.json({error:"Appointments are not enabled for this workspace."},{status:409});if(!customer)return NextResponse.json({error:"Customer not found in this workspace."},{status:404});if(!service)return NextResponse.json({error:"Active service not found."},{status:404});const resource=await ServiceResource.findOne({_id:parsed.data.resourceId,tenantId,active:true}).lean();if(!resource)return NextResponse.json({error:"Active appointment resource not found."},{status:404});
 const date=localDateInZone(start,tenant.timezone),weekday=new Date(`${date}T12:00:00.000Z`).getUTCDay(),hours=tenant.appointmentHours.find(item=>item.weekday===weekday);if(!hours||!isValidLocalDate(date))return NextResponse.json({error:"That day is outside business appointment hours."},{status:409});const choices=slotsForLocalDate({date,timeZone:tenant.timezone,openMinute:hours.openMinute,closeMinute:hours.closeMinute,durationMinutes:service.serviceDurationMinutes!,bufferBeforeMinutes:resource.bufferBeforeMinutes,bufferAfterMinutes:resource.bufferAfterMinutes}),slot=choices.find(item=>item.startsAt.getTime()===start.getTime());if(!slot)return NextResponse.json({error:"That start time is not an offered appointment slot."},{status:409});if(tenant.appointmentClosures.some(c=>slot.bufferedStartsAt<c.endsAt&&slot.bufferedEndsAt>c.startsAt))return NextResponse.json({error:"That appointment time is closed."},{status:409});
 const session=await mongoose.startSession();let result:unknown;try{await session.withTransaction(async()=>{const locked=await ServiceResource.findOneAndUpdate({_id:resource._id,tenantId,active:true},{$inc:{version:1}},{new:true,session});if(!locked)throw new Error("RESOURCE_UNAVAILABLE");const now=new Date(),conflicts=await Appointment.find({tenantId,resourceId:resource._id,bufferedStartsAt:{$lt:slot.bufferedEndsAt},bufferedEndsAt:{$gt:slot.bufferedStartsAt},$or:[{status:"confirmed"},{status:"held",holdExpiresAt:{$gt:now}}]}).select("bufferedStartsAt bufferedEndsAt").session(session).lean();if(!hasIntervalCapacity({startAt:slot.bufferedStartsAt,endAt:slot.bufferedEndsAt},conflicts.map(a=>({startAt:a.bufferedStartsAt,endAt:a.bufferedEndsAt})),locked.capacity))throw new Error("SLOT_FULL");const[appointment]=await Appointment.create([{tenantId,customerId:customer._id,serviceItemId:service._id,serviceName:service.name,serviceDurationMinutes:service.serviceDurationMinutes,customerName:customer.name,customerEmail:customer.email,resourceId:resource._id,resourceName:resource.name,startsAt:slot.startsAt,endsAt:slot.endsAt,bufferedStartsAt:slot.bufferedStartsAt,bufferedEndsAt:slot.bufferedEndsAt,businessTimezone:tenant.timezone,status:"held",holdExpiresAt:new Date(now.getTime()+10*60_000),cancellationPolicyHours:tenant.appointmentCancellationHours,idempotencyKey:key,requestFingerprint:fingerprint,createdBy:access!.scope.userId}],{session});await AppointmentEvent.create([{tenantId,appointmentId:appointment._id,actorId:access!.scope.userId,action:"held",details:{expiresAt:appointment.holdExpiresAt,timezone:tenant.timezone}}],{session});await AuditEvent.create([{tenantId,actorId:access!.scope.userId,action:"appointment.held",entityType:"appointment",entityId:String(appointment._id),requestId:randomBytes(12).toString("hex"),metadata:{serviceId:String(service._id),resourceId:String(resource._id),startsAt:slot.startsAt.toISOString()}}],{session});result=appointment.toObject()})}finally{await session.endSession()}return NextResponse.json({appointment:result},{status:201,headers:{"Cache-Control":"private, no-store"}})
 }catch(error){if(error instanceof Error&&error.message==="SLOT_FULL")return NextResponse.json({error:"That time was just booked. Refresh availability and choose another slot."},{status:409});if((error as {code?:number})?.code===11000){const replay=await Appointment.findOne({tenantId,idempotencyKey:key}).lean();if(replay)return NextResponse.json({appointment:replay},{headers:{"Cache-Control":"private, no-store"}})}return fail(error)}
}
