import {randomBytes} from "node:crypto";
import {NextResponse} from "next/server";
import {z} from "zod";
import {requireTenantAccess} from "@/server/tenant-scope";
import {isSameOrigin,readJsonLimited} from "@/server/request-security";
import {Tenant} from "@/server/models/Tenant";
import {Deal} from "@/server/models/Deal";
import {AuditEvent} from "@/server/models/AuditEvent";
import {validSalesStageConfiguration,salesStagesFor} from "@/server/domain/deals";

const stageSchema=z.object({key:z.string().trim().toLowerCase().regex(/^[a-z][a-z0-9_-]{1,39}$/),label:z.string().trim().min(2).max(40),position:z.number().int().min(0).max(11)}).strict();
const schema=z.object({stages:z.array(stageSchema).min(3).max(12)}).strict().superRefine((value,context)=>{if(!validSalesStageConfiguration(value.stages))context.addIssue({code:"custom",path:["stages"],message:"Keep New first, Won and Lost last, with unique stage keys, names and consecutive positions."})});
export async function PATCH(request:Request){if(!isSameOrigin(request))return NextResponse.json({error:"Request origin could not be verified."},{status:403});let access;try{access=await requireTenantAccess("deals:write")}catch(error){if(error instanceof Error&&error.message==="PERMISSION_DENIED")return NextResponse.json({error:"You do not have permission to configure this pipeline."},{status:403});return NextResponse.json({error:"Pipeline settings are temporarily unavailable."},{status:503})}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});if(access.scope.role!=="owner")return NextResponse.json({error:"Only a workspace owner can configure pipeline stages."},{status:403});const body=await readJsonLimited(request,12000);if(body.kind==="too-large")return NextResponse.json({error:"Request is too large."},{status:413});const parsed=schema.safeParse(body.kind==="ok"?body.value:null);if(!parsed.success)return NextResponse.json({error:"Provide between three and twelve stages, keeping New first and Won/Lost last."},{status:400});const existing=await Tenant.findById(access.scope.tenantId).select("salesStages").lean();if(!existing)return NextResponse.json({error:"Workspace not found."},{status:404});const removed=salesStagesFor(existing.salesStages as {key:string;label:string;position:number}[]|undefined).map(stage=>stage.key).filter(key=>!parsed.data.stages.some(stage=>stage.key===key));if(removed.length){const active=await Deal.exists({tenantId:access.scope.tenantId,stage:{$in:removed}});if(active)return NextResponse.json({error:"Move all deals out of a stage before removing it."},{status:409})}try{const tenant=await Tenant.findOneAndUpdate({_id:access.scope.tenantId},{$set:{salesStages:parsed.data.stages}},{new:true,runValidators:true}).select("salesStages").lean();await AuditEvent.create({tenantId:access.scope.tenantId,actorId:access.scope.userId,action:"sales_pipeline.settings_updated",entityType:"tenant",entityId:access.scope.tenantId,requestId:randomBytes(12).toString("hex"),metadata:{stageKeys:parsed.data.stages.map(stage=>stage.key)}});return NextResponse.json({stages:tenant?.salesStages||[]},{headers:{"Cache-Control":"private, no-store"}})}catch{return NextResponse.json({error:"Pipeline settings are temporarily unavailable."},{status:503})}}
