import {randomBytes} from "node:crypto";
import mongoose from "mongoose";
import {NextResponse} from "next/server";
import {z} from "zod";
import {requireTenantAccess} from "@/server/tenant-scope";
import {isSameOrigin,readJsonLimited} from "@/server/request-security";
import {Quote} from "@/server/models/Quote";
import {QuoteCounter} from "@/server/models/QuoteCounter";
import {QuoteRevision} from "@/server/models/QuoteRevision";
import {Customer} from "@/server/models/Customer";
import {CatalogueItem} from "@/server/models/CatalogueItem";
const draftSchema=z.object({customerId:z.string().regex(/^[a-f\d]{24}$/i),lines:z.array(z.object({itemId:z.string().regex(/^[a-f\d]{24}$/i),quantity:z.number().int().safe().min(1).max(100000)}).strict()).min(1).max(50),terms:z.string().trim().max(4000).default(""),validForDays:z.number().int().min(1).max(90).default(14)}).strict().superRefine((value,ctx)=>{if(new Set(value.lines.map((line)=>line.itemId)).size!==value.lines.length)ctx.addIssue({code:"custom",path:["lines"],message:"Each item can appear once; combine its quantity."})});
function fail(error:unknown){if(error instanceof Error&&error.message==="PERMISSION_DENIED")return NextResponse.json({error:"You do not have permission to manage quotes."},{status:403});return NextResponse.json({error:"Quote service is temporarily unavailable."},{status:503})}
export const dynamic="force-dynamic";
export async function GET(request:Request){let access;try{access=await requireTenantAccess("quotes:write")}catch(error){return fail(error)}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});const url=new URL(request.url),q=(url.searchParams.get("q")||"").trim().slice(0,120),status=url.searchParams.get("status"),page=Math.max(1,Number.parseInt(url.searchParams.get("page")||"1",10)||1),limit=Math.max(1,Math.min(100,Number.parseInt(url.searchParams.get("limit")||"25",10)||25));const filter:Record<string,unknown>={tenantId:access.scope.tenantId};if(q)filter.quoteNumber={$regex:q.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),$options:"i"};if(status==="expired")filter.$or=[{status:"expired"},{status:"issued",expiresAt:{$lte:new Date()}}];else if(status==="issued"){filter.status="issued";filter.expiresAt={$gt:new Date()}}else if(["draft","accepted","declined","converted"].includes(status||""))filter.status=status;try{const[quotes,total]=await Promise.all([Quote.find(filter).sort({updatedAt:-1,_id:-1}).skip((page-1)*limit).limit(limit).populate({path:"customerId",match:{tenantId:access.scope.tenantId},select:"name email"}).populate({path:"convertedOrderId",match:{tenantId:access.scope.tenantId},select:"orderNumber"}).populate({path:"convertedOrderId",match:{tenantId:access.scope.tenantId},select:"orderNumber"}).lean(),Quote.countDocuments(filter)]);const revisions=await QuoteRevision.find({tenantId:access.scope.tenantId,quoteId:{$in:quotes.map((quote)=>quote._id)}}).sort({revision:-1}).lean();const latest=new Map<string,typeof revisions[number]>();for(const revision of revisions){const key=String(revision.quoteId);if(!latest.has(key))latest.set(key,revision)}const enriched=quotes.map((quote)=>({...quote,latestRevision:latest.get(String(quote._id))??null}));return NextResponse.json({quotes:enriched,total,page,pageCount:Math.ceil(total/limit),currency:access.tenant.baseCurrency},{headers:{"Cache-Control":"private, no-store"}})}catch(error){return fail(error)}}
export async function POST(request:Request){if(!isSameOrigin(request))return NextResponse.json({error:"Request origin could not be verified."},{status:403});let access;try{access=await requireTenantAccess("quotes:write")}catch(error){return fail(error)}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});if(access.tenant.commerceMode!=="native")return NextResponse.json({error:"Quotes for this connected WooCommerce store must be managed in that store."},{status:409});const limitedJsonBody=await readJsonLimited(request,24000);if(limitedJsonBody.kind==="too-large")return NextResponse.json({error:"Request is too large."},{status:413});const parsed=draftSchema.safeParse(limitedJsonBody.kind==="ok"?limitedJsonBody.value:null);if(!parsed.success)return NextResponse.json({error:"Review the customer and quote items.",issues:parsed.error.issues.map((issue)=>({field:issue.path.join("."),message:issue.message}))},{status:400});const session=await mongoose.startSession();let result:unknown;try{await session.withTransaction(async()=>{const customer=await Customer.findOne({_id:parsed.data.customerId,tenantId:access.scope.tenantId,status:{$ne:"archived"}}).select("_id").session(session).lean();if(!customer)throw new Error("CUSTOMER_NOT_FOUND");const itemIds=parsed.data.lines.map((line)=>line.itemId),count=await CatalogueItem.countDocuments({_id:{$in:itemIds},tenantId:access.scope.tenantId,status:"active"}).session(session);if(count!==itemIds.length)throw new Error("ITEM_UNAVAILABLE");const counter=await QuoteCounter.findOneAndUpdate({tenantId:access.scope.tenantId},{$inc:{nextNumber:1},$setOnInsert:{tenantId:access.scope.tenantId}},{upsert:true,new:true,session});const quoteNumber=`QT-${new Date().getUTCFullYear().toString().slice(-2)}-${String(counter.nextNumber).padStart(6,"0")}`;const[quote]=await Quote.create([{tenantId:access.scope.tenantId,quoteNumber,customerId:customer._id,status:"draft",draftLines:parsed.data.lines,terms:parsed.data.terms,expiresAt:new Date(Date.now()+parsed.data.validForDays*86400000),currentRevision:0,createdBy:access.scope.userId}],{session});result=quote.toObject()})}catch(error){if(error instanceof Error&&error.message==="CUSTOMER_NOT_FOUND")return NextResponse.json({error:"Choose an active customer in this workspace."},{status:404});if(error instanceof Error&&error.message==="ITEM_UNAVAILABLE")return NextResponse.json({error:"One or more quote items are unavailable in this workspace."},{status:409});if((error as {code?:number})?.code===11000)return NextResponse.json({error:"The quote number is already in use. Try again."},{status:409});return fail(error)}finally{await session.endSession()}return NextResponse.json({quote:result},{status:201,headers:{"Cache-Control":"private, no-store"}})}


