"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {CalendarDays,Check,ChevronLeft,ChevronRight,Clock3,Copy,LoaderCircle,Plus,RefreshCw,X} from "lucide-react";
import {boundsForLocalDate,localDateInZone} from "@/server/domain/appointments";
import "./appointment-calendar.css";
import "./appointment-config.css";
import "./appointment-share.css";
type Resource={_id?:string;id?:string;name:string;kind:string;capacity:number;active?:boolean;bufferBeforeMinutes:number;bufferAfterMinutes:number};type Customer={_id:string;name:string;email:string|null};type Service={_id:string;name:string;serviceDurationMinutes:number};type Appointment={_id:string;customerName:string;serviceName:string;resourceName:string;startsAt:string;endsAt:string;status:string;holdExpiresAt?:string|null};type Slot={startsAt:string;endsAt:string;label:string;offset:string};
type Closure={_id:string;startsAt:string;endsAt:string;label:string};
const todayLocal=()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const shiftDate=(value:string,days:number)=>{const date=new Date(`${value}T12:00:00.000Z`);date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10)};
const mondayFor=(value:string)=>{const day=new Date(`${value}T12:00:00.000Z`).getUTCDay();return shiftDate(value,-((day+6)%7))};
function clockMinute(instant:string,timeZone:string){const parts=new Intl.DateTimeFormat("en-GB",{timeZone,hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date(instant)),values=Object.fromEntries(parts.map(part=>[part.type,part.value]));return Number(values.hour)*60+Number(values.minute)}
function timeLabel(instant:string,timeZone:string){return new Intl.DateTimeFormat("en-US",{timeZone,hour:"numeric",minute:"2-digit"}).format(new Date(instant))}
const dayNames=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],defaultHours=[{weekday:1,openMinute:540,closeMinute:1020},{weekday:2,openMinute:540,closeMinute:1020},{weekday:3,openMinute:540,closeMinute:1020},{weekday:4,openMinute:540,closeMinute:1020},{weekday:5,openMinute:540,closeMinute:1020}];
export default function AppointmentsPanel(){const[appointments,setAppointments]=useState<Appointment[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[services,setServices]=useState<Service[]>([]),[resources,setResources]=useState<Resource[]>([]),[serviceId,setServiceId]=useState(""),[customerId,setCustomerId]=useState(""),[date,setDate]=useState(todayLocal()),[calendarDate,setCalendarDate]=useState(todayLocal()),[resourceId,setResourceId]=useState(""),[startAt,setStartAt]=useState(""),[slots,setSlots]=useState<Slot[]>([]),[settings,setSettings]=useState<any>(null),[hours,setHours]=useState(defaultHours),[closures,setClosures]=useState<Closure[]>([]),[closureStart,setClosureStart]=useState(todayLocal()),[closureEnd,setClosureEnd]=useState(todayLocal()),[closureLabel,setClosureLabel]=useState(""),[resourceName,setResourceName]=useState(""),[manageLink,setManageLink]=useState(""),[enabled,setEnabled]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(true),[saving,setSaving]=useState(false);
 const calendarInitialized=useRef(false);
 const load=useCallback(async()=>{setBusy(true);setError("");try{const monday=mondayFor(calendarDate),weekStart=new Date(`${monday}T00:00:00.000Z`),from=new Date(weekStart.getTime()-2*86400000).toISOString(),to=new Date(weekStart.getTime()+9*86400000).toISOString(),[a,c,s,r,g]=await Promise.all([fetch(`/api/appointments?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`,{cache:"no-store"}),fetch("/api/customers?limit=100",{cache:"no-store"}),fetch("/api/catalogue?kind=service&limit=100",{cache:"no-store"}),fetch("/api/appointments/resources",{cache:"no-store"}),fetch("/api/appointments/settings",{cache:"no-store"})]);const data=await Promise.all([a.json(),c.json(),s.json(),r.json(),g.json()]);for(let i=0;i<data.length;i++)if(![a,c,s,r,g][i].ok)throw new Error(data[i].error||"Appointments could not be loaded.");setAppointments(data[0].appointments||[]);setCustomers(data[1].customers||[]);const sv=(data[2].items||data[2].catalogue||data[2].products||[]).filter((x:Service)=>x.serviceDurationMinutes);setServices(sv);setResources(data[3].resources||[]);setSettings(data[4].settings);setEnabled(data[4].settings?.enabled||false);setHours(data[4].settings?.hours?.length?data[4].settings.hours:defaultHours);setClosures((data[4].settings?.closures||[]).map((closure:Closure)=>({...closure,_id:closure._id||`${closure.startsAt}`})));if(!calendarInitialized.current&&data[4].settings?.timezone){setCalendarDate(localDateInZone(new Date(),data[4].settings.timezone));calendarInitialized.current=true}}catch(e){setError(e instanceof Error?e.message:"Appointments could not be loaded.")}finally{setBusy(false)}},[calendarDate]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{if(!serviceId||!date){setSlots([]);return}const controller=new AbortController();void fetch(`/api/appointments/availability?serviceId=${encodeURIComponent(serviceId)}&date=${encodeURIComponent(date)}`,{cache:"no-store",signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Availability could not be loaded.");const all=(d.resources||[]).flatMap((x:any)=>x.slots.map((slot:Slot)=>({...slot,resourceId:x.resource.id,resourceName:x.resource.name})));setSlots(all);if(all.length&&!all.some((x:any)=>x.resourceId===resourceId))setResourceId(all[0].resourceId)}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:"Availability could not be loaded.")});return()=>controller.abort()},[serviceId,date,resourceId]);
 async function create(){if(!customerId||!serviceId||!resourceId||!startAt){setError("Choose a customer, service and available time.");return}setSaving(true);setError("");try{const payload={customerId,serviceId,resourceId,startsAt:startAt},key=crypto.randomUUID(),r=await fetch("/api/appointments",{method:"POST",headers:{"content-type":"application/json","idempotency-key":key},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw new Error(d.error||"Appointment could not be created.");setNotice("A 10-minute appointment hold was created. Confirm it to reserve the time.");setStartAt("");await load()}catch(e){setError(e instanceof Error?e.message:"Appointment could not be created.")}finally{setSaving(false)}}
 async function change(item:Appointment,action:"confirm"|"cancel"|"complete"|"no_show"){setError("");try{const r=await fetch(`/api/appointments/${item._id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Appointment could not be updated.");setNotice(`Appointment ${action.replace("_"," ")}d.`);await load()}catch(e){setError(e instanceof Error?e.message:"Appointment could not be updated.")}}
 async function issueManageLink(item:Appointment){setError("");setManageLink("");try{const response=await fetch(`/api/appointments/${item._id}/manage-link`,{method:"POST"}),body=await response.json();if(!response.ok)throw new Error(body.error||"A customer link could not be issued.");setManageLink(body.url);try{await navigator.clipboard.writeText(body.url);setNotice("A new private customer link was copied. Earlier links for this appointment have been replaced.")}catch{setNotice("A new private customer link is ready below. Earlier links for this appointment have been replaced.")}}catch(e){setError(e instanceof Error?e.message:"A customer link could not be issued.")}}
 async function copyManageLink(){try{await navigator.clipboard.writeText(manageLink);setNotice("Customer appointment link copied.")}catch{setNotice("Clipboard access is unavailable. Select and copy the private link below.")}}
 async function addResource(event:React.FormEvent){event.preventDefault();try{const r=await fetch("/api/appointments/resources",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:resourceName,kind:"staff",capacity:1,bufferBeforeMinutes:0,bufferAfterMinutes:0})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Resource could not be added.");setResourceName("");await load()}catch(e){setError(e instanceof Error?e.message:"Resource could not be added.")}}
 function changeHours(weekday:number,key:"openMinute"|"closeMinute",value:string){const[hour,minute]=value.split(":").map(Number),minutes=hour*60+minute;setHours(current=>{const existing=current.find(day=>day.weekday===weekday),next=existing?current.map(day=>day.weekday===weekday?{...day,[key]:minutes}:day):[...current,{weekday,openMinute:key==="openMinute"?minutes:540,closeMinute:key==="closeMinute"?minutes:1020}];return next.sort((a,b)=>a.weekday-b.weekday)})}
 function timeValue(minutes:number){return`${String(Math.floor(minutes/60)).padStart(2,"0")}:${String(minutes%60).padStart(2,"0")}`}
 async function saveSettings(nextEnabled=enabled){setSaving(true);setError("");try{const r=await fetch("/api/appointments/settings",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({enabled:nextEnabled,hours,closures:closures.map(({startsAt,endsAt,label})=>({startsAt,endsAt,label})),cancellationHours:settings?.cancellationHours??24})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Settings could not be saved.");setSettings(d.settings);setEnabled(d.settings.enabled);setClosures((d.settings.closures||[]).map((closure:Closure)=>({...closure,_id:closure._id||`${closure.startsAt}`})));setNotice(d.settings.enabled?"Appointment hours and scheduling settings saved.":"Appointment scheduling is disabled.")}catch(e){setError(e instanceof Error?e.message:"Settings could not be saved.")}finally{setSaving(false)}}
 function addClosure(event:React.FormEvent){event.preventDefault();setError("");try{if(!settings?.timezone)throw new Error("Workspace timezone could not be read.");if(closureEnd<closureStart)throw new Error("The end date must be on or after the start date.");if(closures.length>=100)throw new Error("A workspace can have up to 100 closure periods.");const start=boundsForLocalDate(closureStart,settings.timezone),end=boundsForLocalDate(closureEnd,settings.timezone);setClosures(current=>[...current,{_id:crypto.randomUUID(),startsAt:start.startsAt.toISOString(),endsAt:end.endsAt.toISOString(),label:closureLabel.trim()}].sort((a,b)=>a.startsAt.localeCompare(b.startsAt)));setNotice("Closure added. Save the closure list to publish the change.");setClosureLabel("")}catch(e){setError(e instanceof Error?e.message:"Closure could not be added.")}}
 function removeClosure(id:string){setClosures(current=>current.filter(closure=>closure._id!==id))}
 const activeResources=resources.filter(r=>r.active!==false),selected=slots.filter((s:any)=>s.resourceId===resourceId);
 const timezone=settings?.timezone||"UTC",weekStart=mondayFor(calendarDate),weekDates=Array.from({length:7},(_,index)=>shiftDate(weekStart,index)),calendarHours=Array.from({length:16},(_,index)=>index+6);
 function eventsForDay(day:string){const items=appointments.filter(item=>localDateInZone(new Date(item.startsAt),timezone)===day).map(item=>({item,start:clockMinute(item.startsAt,timezone),end:clockMinute(item.endsAt,timezone)})).sort((a,b)=>a.start-b.start||a.end-b.end);const laneEnds:number[]=[];const positioned=items.map(event=>{let lane=laneEnds.findIndex(end=>end<=event.start);if(lane<0)lane=laneEnds.length;laneEnds[lane]=event.end;return{...event,lane}});return positioned.map(event=>({...event,lanes:laneEnds.length}))}
 return <div className="catalogue-page"><div className="catalogue-heading"><div><span className="eyebrow"><i/>SERVICE OPERATIONS</span><h1>Appointments</h1><p>Coordinate service bookings, resource capacity and customer visits in your workspace timezone.</p></div><button className="primary" onClick={()=>void load()}><RefreshCw/>Refresh</button></div>
  {error&&<div className="inline-error" role="alert"><X/>{error}</div>}{notice&&<div className="toast" role="status"><Check/>{notice}<button onClick={()=>setNotice("")} aria-label="Dismiss"><X/></button></div>}{manageLink&&<div className="appointment-link-output"><label>PRIVATE CUSTOMER LINK<input readOnly value={manageLink}/></label><button onClick={()=>void copyManageLink()}><Copy/>Copy link</button><button aria-label="Hide customer link" onClick={()=>setManageLink("")}><X/></button></div>}
  <section className="catalogue-card appointment-config"><div><span className="metric-icon"><CalendarDays/></span><div><small>BOOKING SYSTEM · {settings?.timezone||"BUSINESS TIMEZONE"}</small><h2>{enabled?"Online scheduling is enabled":"Scheduling is paused"}</h2><p>Bookings use service length, resource buffers and real local timezone transitions.</p></div></div><button className={enabled?"appointment-toggle on":"appointment-toggle"} onClick={()=>void saveSettings(!enabled)}>{enabled?"Disable bookings":"Enable bookings"}</button></section>
  <section className="catalogue-card appointment-hours">
   <div className="appointment-section-head"><div><small>BUSINESS AVAILABILITY</small><h2>Weekly opening hours</h2></div><button className="appointment-toggle" onClick={()=>void saveSettings()}>Save hours</button></div>
   {dayNames.map((day,weekday)=>{
    const config=hours.find(item=>item.weekday===weekday);
    return <div className="hours-row" key={day}>
     <label><input type="checkbox" checked={!!config} onChange={event=>setHours(current=>event.target.checked?[...current,{weekday,openMinute:540,closeMinute:1020}].sort((a,b)=>a.weekday-b.weekday):current.filter(item=>item.weekday!==weekday))}/>{day}</label>
     {config?<><input aria-label={`${day} opening time`} type="time" value={timeValue(config.openMinute)} onChange={event=>changeHours(weekday,"openMinute",event.target.value)}/><span>to</span><input aria-label={`${day} closing time`} type="time" value={timeValue(config.closeMinute)} onChange={event=>changeHours(weekday,"closeMinute",event.target.value)}/></>:<small>Closed</small>}
    </div>;
   })}
  </section>
  <section className="catalogue-card appointment-closures"><div className="appointment-section-head"><div><small>DATE EXCEPTIONS · {settings?.timezone||"WORKSPACE TIMEZONE"}</small><h2>Closed dates</h2><p>Pause online booking for holidays, leave or planned maintenance.</p></div><button className="appointment-toggle" onClick={()=>void saveSettings()} disabled={saving}>{saving?"Saving…":"Save closures"}</button></div><form className="closure-form" onSubmit={addClosure}><label>First closed day<input required type="date" min={todayLocal()} value={closureStart} onChange={event=>{setClosureStart(event.target.value);if(event.target.value>closureEnd)setClosureEnd(event.target.value)}}/></label><label>Last closed day<input required type="date" min={closureStart} value={closureEnd} onChange={event=>setClosureEnd(event.target.value)}/></label><label>Reason <span>optional</span><input maxLength={120} value={closureLabel} onChange={event=>setClosureLabel(event.target.value)} placeholder="Holiday, maintenance…"/></label><button className="primary" type="submit"><Plus/>Add closure</button></form>{closures.length?<div className="closure-list">{closures.map(closure=>{const timezone=settings?.timezone||"UTC",startLabel=localDateInZone(new Date(closure.startsAt),timezone),endLabel=localDateInZone(new Date(new Date(closure.endsAt).getTime()-60_000),timezone);return <article key={closure._id}><span><CalendarDays/><b>{startLabel===endLabel?startLabel:`${startLabel} — ${endLabel}`}</b><small>{closure.label||"Closed all day"}</small></span><button onClick={()=>removeClosure(closure._id)} aria-label={`Remove closure ${startLabel}`}><X/></button></article>})}</div>:<div className="closure-empty">No closed dates configured.</div>}<p className="closure-footnote">Dates follow the workspace timezone. Save closures to apply them to customer availability.</p></section>
  <section className="catalogue-card appointment-create"><div className="appointment-section-head"><div><small>NEW BOOKING</small><h2>Reserve a service time</h2></div><span><Clock3/> Holds expire after 10 minutes</span></div><div className="appointment-form"><label>Customer<select value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Choose customer</option>{customers.map(c=><option key={c._id} value={c._id}>{c.name}{c.email?` · ${c.email}`:""}</option>)}</select></label><label>Service<select value={serviceId} onChange={e=>{setServiceId(e.target.value);setStartAt("")}}><option value="">Choose service</option>{services.map(s=><option key={s._id} value={s._id}>{s.name} · {s.serviceDurationMinutes} min</option>)}</select></label><label>Date<input type="date" value={date} min={todayLocal()} onChange={e=>{setDate(e.target.value);setStartAt("")}}/></label><label>Resource<select value={resourceId} onChange={e=>{setResourceId(e.target.value);setStartAt("")}}><option value="">Choose resource</option>{activeResources.map(r=><option key={r._id||r.id} value={r._id||r.id}>{r.name}</option>)}</select></label></div><div className="appointment-slots">{selected.length?selected.map(slot=><button key={slot.startsAt} className={startAt===slot.startsAt?"selected":""} onClick={()=>setStartAt(slot.startsAt)}>{slot.label} <small>{slot.offset}</small></button>):<p>{serviceId?"No available times for this service and date.":"Choose a service to view available times."}</p>}</div><button className="primary" disabled={saving||!enabled} onClick={()=>void create()}><Plus/>{saving?"Creating hold…":"Create appointment hold"}</button></section>
  <section className="catalogue-card appointment-calendar"><div className="appointment-section-head"><div><small>VISUAL SCHEDULE · {timezone}</small><h2>{new Intl.DateTimeFormat("en-US",{timeZone:timezone,month:"long",year:"numeric"}).format(boundsForLocalDate(weekStart,timezone).startsAt)}</h2></div><div className="calendar-nav"><button onClick={()=>setCalendarDate(shiftDate(calendarDate,-7))} aria-label="Previous week"><ChevronLeft/></button><button onClick={()=>setCalendarDate(localDateInZone(new Date(),timezone))}>Today</button><button onClick={()=>setCalendarDate(shiftDate(calendarDate,7))} aria-label="Next week"><ChevronRight/></button></div></div><div className="calendar-scroll"><div className="calendar-header"><div/><div className="calendar-days">{weekDates.map(day=><div key={day} className={day===localDateInZone(new Date(),timezone)?"today":""}><small>{new Intl.DateTimeFormat("en-US",{timeZone:timezone,weekday:"short"}).format(new Date(`${day}T12:00:00.000Z`))}</small><b>{new Intl.DateTimeFormat("en-US",{timeZone:timezone,day:"numeric"}).format(new Date(`${day}T12:00:00.000Z`))}</b></div>)}</div></div><div className="calendar-body"><div className="calendar-time-axis">{calendarHours.map(hour=><div key={hour}>{new Intl.DateTimeFormat("en-US",{hour:"numeric",hourCycle:"h12",timeZone:"UTC"}).format(new Date(Date.UTC(2020,0,1,hour)))}</div>)}</div><div className="calendar-days">{weekDates.map(day=><div className="calendar-day" key={day}><div className="calendar-track">{calendarHours.map(hour=><i key={hour} style={{top:`${(hour-6)*60}px`}}/>)}{eventsForDay(day).map(({item,start,end,lane,lanes})=>{const top=start-360,bottom=end-360,visibleTop=Math.max(0,top),visibleBottom=Math.min(960,bottom);if(visibleBottom<=visibleTop)return null;return <article key={item._id} className={`calendar-event ${item.status}`} style={{top:`${visibleTop}px`,height:`${Math.max(28,visibleBottom-visibleTop-3)}px`,left:`calc(${lane*100/lanes}% + 2px)`,width:`calc(${100/lanes}% - 4px)`}} title={`${timeLabel(item.startsAt,timezone)}–${timeLabel(item.endsAt,timezone)} · ${item.customerName} · ${item.serviceName}`}><b>{item.customerName}</b><small>{timeLabel(item.startsAt,timezone)} · {item.serviceName}</small><em>{item.resourceName}</em></article>})}</div></div>)}</div></div>{!busy&&appointments.length===0&&<p className="calendar-empty">No appointments this week. Use the booking form above to reserve a time.</p>}</div></section>
  <section className="catalogue-card appointment-list"><div className="appointment-section-head"><div><small>UPCOMING WORK</small><h2>Appointment schedule</h2></div><span>{appointments.length} shown</span></div>{busy?<div className="catalogue-state"><LoaderCircle className="spin"/>Loading appointment schedule…</div>:appointments.length===0?<div className="catalogue-empty"><div><CalendarDays/></div><h2>No appointments yet</h2><p>Bookings will appear here as soon as you reserve a service time.</p></div>:appointments.map(item=><article className="appointment-row" key={item._id}><span className="appointment-date"><b>{new Date(item.startsAt).toLocaleDateString(undefined,{day:"2-digit"})}</b><small>{new Date(item.startsAt).toLocaleDateString(undefined,{month:"short"})}</small></span><div><b>{item.customerName}</b><small>{item.serviceName} · {item.resourceName} · {new Date(item.startsAt).toLocaleString()}</small></div><span className={`status-chip ${item.status==="confirmed"?"active":"draft"}`}>{item.status}</span><div className="appointment-actions">{item.status==="confirmed"&&<button title="Issue private customer link" onClick={()=>void issueManageLink(item)}><Copy/></button>}{item.status==="held"&&<button title="Confirm hold" onClick={()=>void change(item,"confirm")}><Check/></button>}{item.status==="confirmed"&&<><button title="Mark complete" onClick={()=>void change(item,"complete")}><Check/></button><button title="Mark no-show" onClick={()=>void change(item,"no_show")}><X/></button></>}{["held","confirmed"].includes(item.status)&&<button title="Cancel appointment" onClick={()=>void change(item,"cancel")}><X/></button>}</div></article>)}</section>
  <section className="catalogue-card appointment-resource"><div className="appointment-section-head"><div><small>CAPACITY</small><h2>Booking resources</h2></div><span>Staff or equipment assigned to appointments</span></div>{activeResources.map(resource=><div key={resource._id||resource.id} className="resource-row"><b>{resource.name}</b><small>{resource.kind} · capacity {resource.capacity} · buffer {resource.bufferBeforeMinutes}/{resource.bufferAfterMinutes} min</small></div>)}<form className="resource-add" onSubmit={e=>void addResource(e)}><input aria-label="New staff resource name" value={resourceName} onChange={e=>setResourceName(e.target.value)} placeholder="Add a staff resource" minLength={2} maxLength={120} required/><button className="primary"><Plus/>Add resource</button></form></section>
 </div>
}
