"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import CataloguePanel from "./CataloguePanel";
import CustomerPanel from "./CustomerPanel";
import OrdersPanel from "./OrdersPanel";
import QuotesPanel from "./QuotesPanel";
import WorkspaceSwitcher from "./WorkspaceSwitcher";
import StorefrontSettingsPanel from "./StorefrontSettingsPanel";
import AppointmentsPanel from "./AppointmentsPanel";
import TeamPanel from "./TeamPanel";
import DealsPanel from "./DealsPanel";
import {formatMinorUnits} from "@/server/domain/money";
import {Activity,ArrowRight,Boxes,Building2,CalendarDays,Check,ChevronDown,Command,CreditCard,Layers3,LockKeyhole,Menu,PackageCheck,Plus,ShieldCheck,ShoppingBag,Store,X} from "lucide-react";
function Mark(){return <span className="mark"><i/><i/><i/><i/></span>}
function Orbit(){return <div className="orbit-art" role="img" aria-label="Commerce network illustration"><div className="halo"/><i className="track t1"/><i className="track t2"/><i className="track t3"/><div className="core"><Mark/><small>CD</small></div><div className="node n1"><PackageCheck/></div><div className="node n2"><Building2/></div><div className="node n3"><CreditCard/></div><span className="cap c1">ORDERS</span><span className="cap c2">CUSTOMERS</span><span className="cap c3">PAYMENTS</span></div>}
type SnapshotMetric={key:"customers"|"openQuotes"|"netReceipts"|"openOrders";value:number|null;note:string};
type Snapshot={currency:string;metrics:SnapshotMetric[]};
const metricLabels={customers:"CUSTOMERS",openQuotes:"OPEN QUOTES",netReceipts:"COLLECTED REVENUE",openOrders:"OPEN ORDERS"} as const;
const metricIcons={customers:Building2,openQuotes:Layers3,netReceipts:CreditCard,openOrders:PackageCheck} as const;
export default function Dashboard({tenantName,userName,screen="overview",canManageCatalogue=false,canManageCustomers=false,canAdjustStock=false,canCreateOrders=false,canCreateQuotes=false,canConvertQuotes=false,canReadPayments=false,canCapturePayments=false,canRefundPayments=false,canManageStore=false,currency="USD",role="owner"}:{tenantName:string;userName:string;role?:"owner"|"sales"|"operations"|"finance"|"support";screen?:"overview"|"catalogue"|"customers"|"orders"|"quotes"|"storeSettings"|"appointments"|"team"|"pipeline";canManageCatalogue?:boolean;canManageCustomers?:boolean;canAdjustStock?:boolean;canCreateOrders?:boolean;canCreateQuotes?:boolean;canConvertQuotes?:boolean;canReadPayments?:boolean;canCapturePayments?:boolean;canRefundPayments?:boolean;canManageStore?:boolean;currency?:string}){
  const isCatalogue=screen==="catalogue";const isCustomers=screen==="customers";const isOrders=screen==="orders";const isQuotes=screen==="quotes";const isStoreSettings=screen==="storeSettings";const isAppointments=screen==="appointments";const isTeam=screen==="team";const isPipeline=screen==="pipeline";const canReadCatalogue=["owner","sales","operations"].includes(role);const canReadCustomers=["owner","sales","operations","support"].includes(role);const canReadOrders=["owner","sales","operations","finance"].includes(role);const canReadQuotes=["owner","sales"].includes(role);const canAppointments=["owner","sales","operations"].includes(role);const canReadDeals=["owner","sales"].includes(role);const mayManageStore=canManageStore||role==="owner";
 const[nav,setNav]=useState(false);const[snapshot,setSnapshot]=useState<Snapshot|null>(null);const[snapshotError,setSnapshotError]=useState(false);const[snapshotReload,setSnapshotReload]=useState(0);const router=useRouter();
 useEffect(()=>{if(screen!=="overview")return;const controller=new AbortController();setSnapshot(null);setSnapshotError(false);void fetch("/api/dashboard",{cache:"no-store",signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error("Snapshot unavailable");return await response.json() as Snapshot}).then(setSnapshot).catch(error=>{if(!controller.signal.aborted)setSnapshotError(true)});return()=>controller.abort()},[screen,snapshotReload]);
 async function signOut(){try{await fetch("/api/session",{method:"DELETE"})}finally{router.replace("/login");router.refresh()}}
 return <main className="shell">
  <aside className={`sidebar ${nav?"show":""}`}><div className="brand"><Mark/><b>commerce<span>desk</span></b><button className="close-mobile" onClick={()=>setNav(false)} aria-label="Close menu"><X/></button></div>
   <WorkspaceSwitcher tenantName={tenantName}/>
   <div className="nav-scroll"><div className="nav-label">WORKSPACE</div><nav><a className={isCatalogue||isCustomers||isOrders||isQuotes||isStoreSettings||isAppointments||isTeam||isPipeline?"":"selected"} href="/"><Command/>Overview{!isCatalogue&&!isCustomers&&!isOrders&&!isQuotes&&!isStoreSettings&&!isAppointments&&!isTeam&&!isPipeline&&<span className="live">LIVE</span>}</a>{canReadCustomers&&<a className={isCustomers?"selected":""} href="/customers"><Building2/>Customers</a>}{canReadDeals&&<a className={isPipeline?"selected":""} href="/pipeline"><Layers3/>Pipeline</a>}{canReadQuotes&&<a className={isQuotes?"selected":""} href="/quotes"><Layers3/>Quotes</a>}{canReadOrders&&<a className={isOrders?"selected":""} href="/orders"><ShoppingBag/>Orders</a>}{canReadCatalogue&&<a className={isCatalogue?"selected":""} href="/catalogue"><Boxes/>Catalogue</a>}{canAppointments&&<a className={isAppointments?"selected":""} href="/appointments"><CalendarDays/>Appointments</a>}</nav>
    {mayManageStore&&<><div className="nav-label spaced">ADMINISTRATION</div><nav><a className={isStoreSettings?"selected":""} href="/settings/store"><Store/>Storefront</a><a className={isTeam?"selected":""} href="/team"><ShieldCheck/>Team access</a></nav></>}</div>
   <div className="sidebar-bottom"><div className="secure"><ShieldCheck/>Tenant-first by design</div><button className="sign-out" onClick={signOut}>Sign out <ArrowRight/></button><div className="version"><i/>Workspace <span>v0.1</span></div></div>
  </aside>
   <section className="main" id="overview"><header className="topbar"><button className="mobile-menu" onClick={()=>setNav(true)} aria-label="Open menu"><Menu/></button><div className="crumb">Workspace <span>/</span> <b>{isCatalogue?"Catalogue":isCustomers?"Customers":isOrders?"Orders":isQuotes?"Quotes & deals":isStoreSettings?"Storefront":isAppointments?"Appointments":isTeam?"Team access":isPipeline?"Pipeline":"Overview"}</b></div><div className="top-actions"><span className="preview"><i/>LIVE WORKSPACE</span><span className="avatar" title={`Signed in as ${userName}`} aria-label={`Signed in as ${userName}`}>{userName.trim().slice(0,1).toUpperCase()}</span></div></header>
   <div className="content">{isPipeline?<DealsPanel canConfigure={role==="owner"}/>:isTeam?<TeamPanel/>:isAppointments?<AppointmentsPanel/>:isCatalogue?<CataloguePanel currency={currency} canManage={canManageCatalogue} canAdjustStock={canAdjustStock}/>:isCustomers?<CustomerPanel canManage={canManageCustomers}/>:isOrders?<OrdersPanel currency={currency} canCreate={canCreateOrders} canReadPayments={canReadPayments} canCapturePayments={canCapturePayments} canRefundPayments={canRefundPayments}/>:isQuotes?<QuotesPanel currency={currency} canCreate={canCreateQuotes} canConvert={canConvertQuotes}/>:isStoreSettings?<StorefrontSettingsPanel/>:<><div className="intro"><div className="eyebrow"><i/>YOUR COMMERCE OPERATING SYSTEM</div><span className="date"><CalendarDays/>Today <ChevronDown/></span></div>
    <section className="hero"><div className="hero-copy"><div className="kicker"><i/> YOUR WORKSPACE · {role.toUpperCase()}</div><h1>Commerce,<br/><em>connected.</em></h1><p>Move from customer records to quotes and orders in one tenant-scoped workspace. Open a working area to continue.</p><div className="hero-actions">{canReadOrders?<a className="primary" href="/orders"><ShoppingBag/>Review orders<ArrowRight/></a>:canReadCustomers?<a className="primary" href="/customers"><Building2/>View customers<ArrowRight/></a>:canReadCatalogue?<a className="primary" href="/catalogue"><Boxes/>Open catalogue<ArrowRight/></a>:null}{canReadQuotes&&<a href="/quotes">Review quotes <ArrowRight/></a>}</div><div className="footnote"><ShieldCheck/>Tenant-scoped access <i/> Live workspace records</div></div><div className="art"><Orbit/><span className="tag tag-a"><i/>CUSTOMER RECORDS</span><span className="tag tag-b"><i/>ORDERS & PAYMENTS</span><small>FIG 01 — COMMERCE GRAPH</small></div></section>
    <div className="section-head"><div><small>WORKSPACE SNAPSHOT</small><h2>Your business at a glance</h2></div><span>Live tenant records · all time</span></div>
    <div className="metrics" aria-live="polite" aria-busy={!snapshot&&!snapshotError}>{snapshotError?<div className="snapshot-state error" role="alert"><b>Workspace totals could not load.</b><span>Retry the tenant-scoped snapshot.</span><button type="button" onClick={()=>setSnapshotReload(value=>value+1)}>Try again <ArrowRight/></button></div>:!snapshot?<div className="snapshot-state" role="status"><b>Loading workspace totals…</b><span>Reading your tenant records.</span></div>:snapshot.metrics.map(metric=>{const I=metricIcons[metric.key];const label=metricLabels[metric.key];const value=metric.value===null?"Beyond safe display range":metric.key==="netReceipts"?formatMinorUnits(metric.value,snapshot.currency,"en"):new Intl.NumberFormat("en").format(metric.value);return <article className="metric" key={metric.key}><div><span className="metric-icon"><I/></span><small>{label}</small><i/></div><b>{value}</b><span>{metric.note}</span></article>})}</div>
    <div className="lower"><section className="build"><div className="build-head"><div><small>WORK AREAS</small><h2>Go where the work is</h2></div><span><i/>READY</span></div><p>Each shortcut opens a live module with actions for your workspace role.</p><div className="phases">{canReadOrders&&<a className="phase" href="/orders"><span className="phase-icon"><ShoppingBag/></span><div><b>Orders</b><p>Review order status, fulfilment and recorded payments.</p></div><ArrowRight/></a>}{canReadQuotes&&<a className="phase" href="/quotes"><span className="phase-icon"><Layers3/></span><div><b>Quotes</b><p>Create, issue and convert customer quotations.</p></div><ArrowRight/></a>}{canReadCustomers&&<a className="phase" href="/customers"><span className="phase-icon"><Building2/></span><div><b>Customers</b><p>Open tenant-scoped customer profiles and records.</p></div><ArrowRight/></a>}{canReadCatalogue&&<a className="phase" href="/catalogue"><span className="phase-icon"><Boxes/></span><div><b>Catalogue & stock</b><p>Manage catalogue items, variants and inventory.</p></div><ArrowRight/></a>}</div></section>
    <aside className="setup"><div className="setup-art"><span/><div><Mark/></div><small>ACTIVE</small></div><small>WORKSPACE</small><h2>{tenantName}</h2><p>Your current business workspace. Access to customer and commerce data is checked against your live membership.</p><div className="checklist"><div><i className="complete"><Check/></i>Access role<small>{role.toUpperCase()}</small></div><div><i className="complete"><Check/></i>Base currency<small>{currency}</small></div><div><i className="complete"><Check/></i>Data boundary<small>TENANT</small></div></div>{mayManageStore&&<a className="setup-action" href="/settings/store">Manage storefront <ArrowRight/></a>}<div className="local-note"><LockKeyhole/>Private workspace · tenant scoped</div></aside></div>
    </>}
    <footer>COMMERCE DESK · WORKSPACE <span>Built for connected commerce <b>✳</b></span></footer>
   </div>
  </section>
 </main>
}












