"use client";
import {useCallback,useEffect,useState} from "react";
import {ArrowRight,Check,CircleAlert,LoaderCircle,LockKeyhole,Mail,PlugZap,RefreshCw,ShieldCheck,Unplug} from "lucide-react";
import styles from "./EmailSettingsPanel.module.css";

type Connection={host:string;port:465|587;secure:boolean;username:string;fromName:string;fromEmail:string;status:"verified"|"degraded";lastVerifiedAt:string|null;passwordConfigured:boolean};
type Delivery={id:string;template:string;recipient:string;status:"queued"|"sending"|"sent"|"failed";attempts:number;nextAttemptAt:string|null;sentAt:string|null;lastErrorCode:string|null;createdAt:string};
type Reply={connection:Connection|null;deliveries?:Delivery[];error?:string};
const blank={host:"",port:587 as 465|587,secure:false,username:"",password:"",fromName:"CommerceDesk",fromEmail:""};
export default function EmailSettingsPanel(){
 const[connection,setConnection]=useState<Connection|null>(null),[deliveries,setDeliveries]=useState<Delivery[]>([]),[form,setForm]=useState(blank),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[removing,setRemoving]=useState(false),[retrying,setRetrying]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch("/api/integrations/smtp",{cache:"no-store"}),data=await response.json() as Reply;if(!response.ok)throw new Error(data.error||"Email settings could not be loaded.");setConnection(data.connection);setDeliveries(data.deliveries||[]);if(data.connection)setForm({...blank,...data.connection,password:""})}catch(reason){setError(reason instanceof Error?reason.message:"Email settings could not be loaded.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 async function save(event:React.FormEvent){event.preventDefault();setSaving(true);setError("");setNotice("");try{const response=await fetch("/api/integrations/smtp",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}),data=await response.json() as Reply;if(!response.ok)throw new Error(data.error||"SMTP connection could not be verified.");setConnection(data.connection);setForm({...blank,...data.connection,password:""});setNotice("SMTP connection verified. The password is encrypted for this workspace.")}catch(reason){setError(reason instanceof Error?reason.message:"SMTP connection could not be verified.")}finally{setSaving(false)}}
 async function disconnect(){setRemoving(true);setError("");setNotice("");try{const response=await fetch("/api/integrations/smtp",{method:"DELETE"}),data=await response.json();if(!response.ok)throw new Error(data.error||"Email connection could not be removed.");setConnection(null);setForm(blank);setNotice("SMTP credentials removed from this workspace.")}catch(reason){setError(reason instanceof Error?reason.message:"Email connection could not be removed.")}finally{setRemoving(false)}}
 async function retry(delivery:Delivery){setRetrying(delivery.id);setError("");setNotice("");try{const response=await fetch(`/api/integrations/smtp/deliveries/${delivery.id}/retry`,{method:"POST"}),data=await response.json();if(!response.ok)throw new Error(data.error||"Email could not be retried.");setNotice("Email queued for retry.");await load()}catch(reason){setError(reason instanceof Error?reason.message:"Email could not be retried.")}finally{setRetrying("")}}
 function update<K extends keyof typeof blank>(key:K,value:(typeof blank)[K]){setForm(current=>({...current,[key]:value,...(key==="port"?{secure:value===465}:{})}))}
 const verified=connection?.lastVerifiedAt?new Date(connection.lastVerifiedAt).toLocaleString():"Not verified";
 return <main className={styles.page}>
  <div className={styles.eyebrow}><span/>MESSAGING · INTEGRATIONS <a href="/settings/payments">Payments <ArrowRight/></a></div>
  <section className={styles.hero}><div className={styles.orbit}><i/><i/><i/><b><Mail/></b></div><div className={styles.heroCopy}><small>WORKSPACE EMAIL DELIVERY</small><h1>Connect your<br/><em>mail channel.</em></h1><p>Configure your SMTP provider to deliver CommerceDesk emails from the business address you choose.</p><div className={styles.assurance}><span><ShieldCheck/>Workspace scoped</span><i/><span><LockKeyhole/>Encrypted secrets</span><i/><span><PlugZap/>TLS required</span></div></div><div className={styles.pill}><i className={connection?.status==="verified"?styles.online:""}/>{loading?"CHECKING":connection?"VERIFIED":"NOT CONNECTED"}</div></section>
  <div className={styles.grid}>
   <section className={styles.card} aria-busy={loading}><header><div><small>SMTP CONNECTION</small><h2>{connection?connection.host:"Connect a mail server"}</h2><p>{connection?"Credentials are stored encrypted and never shown again.":"Use your provider's SMTP host and app password."}</p></div><button type="button" onClick={()=>void load()} disabled={loading} aria-label="Refresh SMTP status"><RefreshCw/></button></header>
    {loading?<div className={styles.state}><LoaderCircle/>Loading workspace mail settings…</div>:connection?<div className={styles.connection}><div className={styles.stateRow}><span><Check/></span><div><b>SMTP verified</b><small>Last checked {verified}</small></div><em>READY</em></div><dl><div><dt>Server</dt><dd>{connection.host}:{connection.port}</dd></div><div><dt>Security</dt><dd>{connection.secure?"TLS":"STARTTLS required"}</dd></div><div><dt>Sender</dt><dd>{connection.fromName} &lt;{connection.fromEmail}&gt;</dd></div><div><dt>Account</dt><dd>{connection.username}</dd></div></dl><button type="button" className={styles.disconnect} disabled={removing} onClick={()=>void disconnect()}>{removing?<LoaderCircle/>:<Unplug/>}{removing?"Removing…":"Disconnect email"}</button></div>:<div className={styles.empty}><span><Mail/></span><b>Email delivery is not connected</b><p>Connect SMTP to prepare invitations, customer notices, and account emails.</p></div>}
   </section>
   <aside className={styles.card+" "+styles.guide}><small>CONNECTION GUIDE</small><h2>Two secure<br/>server options.</h2><ol><li><i>01</i><div><b>Port 465</b><p>Use implicit TLS when your provider specifies secure SMTP.</p></div></li><li><i>02</i><div><b>Port 587</b><p>STARTTLS is required before credentials are sent.</p></div></li><li><i>03</i><div><b>Verify before saving</b><p>CommerceDesk checks the mail server and credentials first.</p></div></li></ol><p className={styles.note}><LockKeyhole/>Local and private network addresses are blocked; certificate checks stay enabled.</p></aside>
  </div>
  <section className={styles.card+" "+styles.deliveryCard}><header><div><small>OUTGOING EMAIL HISTORY</small><h2>Recent deliveries</h2><p>Last 50 invitations, their status, and available retry actions.</p></div><button type="button" onClick={()=>void load()} disabled={loading} aria-label="Refresh email delivery history"><RefreshCw/></button></header>{deliveries.length?<div className={styles.tableWrap}><table><thead><tr><th>Recipient</th><th>Status</th><th>Attempts</th><th>Updated</th><th></th></tr></thead><tbody>{deliveries.map(delivery=><tr key={delivery.id}><td><b>{delivery.recipient}</b><small>{delivery.template.replaceAll("_"," ")}</small></td><td><span className={`${styles.deliveryStatus} ${delivery.status==="sent"?styles.sent:delivery.status==="failed"?styles.failed:delivery.status==="sending"?styles.sending:styles.queued}`}>{delivery.status.toUpperCase()}</span>{delivery.lastErrorCode&&<small className={styles.deliveryError}>{delivery.lastErrorCode}</small>}</td><td>{delivery.attempts}/5</td><td>{new Date(delivery.sentAt||delivery.nextAttemptAt||delivery.createdAt).toLocaleString()}</td><td>{delivery.status==="failed"&&<button type="button" className={styles.retry} onClick={()=>void retry(delivery)} disabled={retrying===delivery.id}>{retrying===delivery.id?<LoaderCircle/>:"Retry"}</button>}</td></tr>)}</tbody></table></div>:<div className={styles.empty}><b>No transactional emails yet</b><p>New team invitations will appear here when SMTP delivery is enabled.</p></div>}</section>
  <section className={styles.card+" "+styles.formCard}><div className={styles.formIntro}><span><ShieldCheck/></span><div><small>{connection?"UPDATE SMTP SETTINGS":"CONNECT EMAIL DELIVERY"}</small><h2>{connection?"Update mail settings":"Add your SMTP details"}</h2><p>{connection?"Leave the password empty to keep the encrypted password.":"Your provider can supply these values. Use an app password where available."}</p></div></div>
   <form onSubmit={save}><div className={styles.formGrid}><label>SMTP hostname<input required autoComplete="off" maxLength={253} value={form.host} onChange={event=>update("host",event.target.value)} placeholder="smtp.example.com"/></label><label>Security mode<select value={form.port} onChange={event=>update("port",Number(event.target.value) as 465|587)}><option value={587}>587 · STARTTLS</option><option value={465}>465 · TLS</option></select></label><label>SMTP username<input required autoComplete="username" maxLength={254} value={form.username} onChange={event=>update("username",event.target.value)} placeholder="mailbox@example.com"/></label><label>App password<input type="password" autoComplete="new-password" maxLength={512} required={!connection} value={form.password} onChange={event=>update("password",event.target.value)} placeholder={connection?"Leave blank to keep saved password":"Provider app password"}/></label><label>Sender name<input required maxLength={120} value={form.fromName} onChange={event=>update("fromName",event.target.value)} placeholder="Your business"/></label><label>Sender email<input required type="email" autoComplete="email" maxLength={254} value={form.fromEmail} onChange={event=>update("fromEmail",event.target.value)} placeholder="hello@example.com"/></label></div><div className={styles.formBottom}><p><LockKeyhole/>Password is encrypted at rest and is never returned to the browser.</p><button type="submit" disabled={saving||loading}>{saving?<LoaderCircle/>:<PlugZap/>}{saving?"Verifying…":"Verify & save"}<ArrowRight/></button></div></form>
  </section>
  <div className={styles.feedback} aria-live="polite">{error&&<p role="alert"><CircleAlert/>{error}</p>}{notice&&<p role="status"><Check/>{notice}</p>}</div>
 </main>
}
