"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {Banknote,Check,ChevronDown,ChevronLeft,ChevronRight,CircleAlert,ClipboardCheck,LoaderCircle,PackageCheck,Plus,Printer,Search,ShieldCheck,ShoppingBag,Truck,X} from "lucide-react";
import {formatMinorUnits} from "@/server/domain/money";
import PaymentLedger from "./PaymentLedger";
type Customer={_id:string;name:string;email:string|null;status:string};
type Product={_id:string;name:string;kind:"physical"|"service";unitPriceMinor:number;trackInventory:boolean;stockOnHand:number;stockReserved:number};
type Order={_id:string;orderNumber:string;customerSnapshot:{name:string;email:string|null};lines:{kind:"physical"|"service";name:string;quantity:number}[];fulfilments?:{eventType?:"dispatch"|"service_completion";occurredAt?:string;note?:string;lines:{lineIndex:number;quantity:number}[]}[];currency:string;totalMinor:number;status:"open"|"pending_payment"|"fulfilled"|"cancelled";paymentStatus:string;fulfilmentStatus:string;createdAt:string};
export default function OrdersPanel({currency,canCreate,canFulfil=false,canReadPayments=false,canCapturePayments=false,canRefundPayments=false}:{currency:string;canCreate:boolean;canFulfil?:boolean;canReadPayments?:boolean;canCapturePayments?:boolean;canRefundPayments?:boolean}){
 const[orders,setOrders]=useState<Order[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[products,setProducts]=useState<Product[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[pageCount,setPageCount]=useState(0),[status,setStatus]=useState(""),[query,setQuery]=useState(""),[busy,setBusy]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[showForm,setShowForm]=useState(false),[customerId,setCustomerId]=useState(""),[lineItems,setLineItems]=useState([{itemId:"",quantity:"1"}]),[saving,setSaving]=useState(false),[actionBusy,setActionBusy]=useState(""),[ledgerOrder,setLedgerOrder]=useState<Order|null>(null),[dispatchOrder,setDispatchOrder]=useState<Order|null>(null),[dispatchQuantities,setDispatchQuantities]=useState<string[]>([]),[serviceOrder,setServiceOrder]=useState<Order|null>(null),[serviceQuantities,setServiceQuantities]=useState<string[]>([]),[serviceNote,setServiceNote]=useState("");
 const attempt=useRef<{signature:string;key:string}|null>(null),dispatchAttempt=useRef<{orderId:string;signature:string;key:string}|null>(null),serviceAttempt=useRef<{orderId:string;signature:string;key:string}|null>(null);
 const load=useCallback(async()=>{setBusy(true);setError("");try{const params=new URLSearchParams({page:String(page),limit:"25"});if(status)params.set("status",status);if(query.trim())params.set("q",query.trim());const response=await fetch(`/api/orders?${params}`,{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"Could not load orders.");setOrders(data.orders||[]);setTotal(data.total||0);setPageCount(data.pageCount||0)}catch(e){setError(e instanceof Error?e.message:"Could not load orders.")}finally{setBusy(false)}},[page,status,query]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),query?200:0);return()=>clearTimeout(timer)},[load,query]);
 useEffect(()=>{if(!canCreate)return;Promise.all([fetch("/api/customers?limit=100",{cache:"no-store"}),fetch("/api/catalogue?status=active&limit=100",{cache:"no-store"})]).then(async([cr,pr])=>{const[c,p]=await Promise.all([cr.json(),pr.json()]);if(!cr.ok)throw new Error(c.error||"Could not load customers.");if(!pr.ok)throw new Error(p.error||"Could not load catalogue items.");setCustomers(c.customers||[]);setProducts(p.items||[]) }).catch((e)=>setError(e instanceof Error?e.message:"Order entry data could not be loaded."))},[canCreate]);
 function reset(){setCustomerId("");setLineItems([{itemId:"",quantity:"1"}]);attempt.current=null}
 async function create(event:React.FormEvent){event.preventDefault();setSaving(true);setError("");try{const payload={customerId,lines:lineItems.map((line)=>({itemId:line.itemId,quantity:Number(line.quantity)}))};const signature=JSON.stringify(payload);if(!attempt.current||attempt.current.signature!==signature)attempt.current={signature,key:crypto.randomUUID()};const response=await fetch("/api/orders",{method:"POST",headers:{"content-type":"application/json","idempotency-key":attempt.current.key},body:signature});const data=await response.json();if(!response.ok)throw new Error(data.error||"Order could not be created.");setNotice(`${data.order.orderNumber} created. Tracked stock is reserved where applicable; payment remains unpaid.`);setShowForm(false);reset();setPage(1);await load()}catch(e){setError(e instanceof Error?e.message:"Order could not be created.")}finally{setSaving(false)}}
 function dispatched(order:Order,index:number){return (order.fulfilments||[]).filter(event=>(event.eventType??"dispatch")==="dispatch").reduce((sum,event)=>sum+event.lines.filter(line=>line.lineIndex===index).reduce((n,line)=>n+line.quantity,0),0)}
 function serviceCompleted(order:Order,index:number){return (order.fulfilments||[]).filter(event=>event.eventType==="service_completion").reduce((sum,event)=>sum+event.lines.filter(line=>line.lineIndex===index).reduce((n,line)=>n+line.quantity,0),0)}
 function hasDispatchable(order:Order){return order.lines.some((line,index)=>line.kind==="physical"&&dispatched(order,index)<line.quantity)}
 function hasServiceToComplete(order:Order){return order.lines.some((line,index)=>line.kind==="service"&&serviceCompleted(order,index)<line.quantity)}
 function beginDispatch(order:Order){setError("");setDispatchOrder(order);setDispatchQuantities(order.lines.map((line,index)=>line.kind==="physical"?String(Math.max(0,line.quantity-dispatched(order,index))):"0"));dispatchAttempt.current=null}
 function beginServiceCompletion(order:Order){setError("");setServiceOrder(order);setServiceQuantities(order.lines.map((line,index)=>line.kind==="service"?String(Math.max(0,line.quantity-serviceCompleted(order,index))):"0"));setServiceNote("");serviceAttempt.current=null}
 async function saveDispatch(event:React.FormEvent){event.preventDefault();if(!dispatchOrder)return;const lines=dispatchQuantities.flatMap((value,lineIndex)=>Number(value)>0?[{lineIndex,quantity:Number(value)}]:[]);const payload={action:"dispatch",lines},signature=JSON.stringify(payload);if(!dispatchAttempt.current||dispatchAttempt.current.orderId!==dispatchOrder._id||dispatchAttempt.current.signature!==signature)dispatchAttempt.current={orderId:dispatchOrder._id,signature,key:crypto.randomUUID()};setActionBusy(dispatchOrder._id);setError("");try{const response=await fetch(`/api/orders/${dispatchOrder._id}`,{method:"POST",headers:{"content-type":"application/json","idempotency-key":dispatchAttempt.current.key},body:signature});const data=await response.json();if(!response.ok)throw new Error(data.error||"Dispatch could not be recorded.");setNotice(`${dispatchOrder.orderNumber} dispatch recorded. Payment status is unchanged.`);setDispatchOrder(null);dispatchAttempt.current=null;await load()}catch(e){setError(e instanceof Error?e.message:"Dispatch could not be recorded.")}finally{setActionBusy("")}}
 async function saveServiceCompletion(event:React.FormEvent){event.preventDefault();if(!serviceOrder)return;const lines=serviceQuantities.flatMap((value,lineIndex)=>Number(value)>0?[{lineIndex,quantity:Number(value)}]:[]);const payload={action:"complete_service",lines,note:serviceNote.trim()},signature=JSON.stringify(payload);if(!serviceAttempt.current||serviceAttempt.current.orderId!==serviceOrder._id||serviceAttempt.current.signature!==signature)serviceAttempt.current={orderId:serviceOrder._id,signature,key:crypto.randomUUID()};setActionBusy(serviceOrder._id);setError("");try{const response=await fetch(`/api/orders/${serviceOrder._id}`,{method:"POST",headers:{"content-type":"application/json","idempotency-key":serviceAttempt.current.key},body:signature});const data=await response.json();if(!response.ok)throw new Error(data.error||"Service completion could not be recorded.");setNotice(`${serviceOrder.orderNumber} service work recorded. Payment status is unchanged.`);setServiceOrder(null);serviceAttempt.current=null;await load()}catch(e){setError(e instanceof Error?e.message:"Service completion could not be recorded.")}finally{setActionBusy("")}}
 async function changeOrder(order:Order,action:"fulfil"|"cancel"){const message=action==="fulfil"?`Dispatch all remaining physical quantities for ${order.orderNumber}? Service work remains separate.`:`Cancel ${order.orderNumber} and release only the remaining reserved stock? Payment will not change.`;if(!window.confirm(message))return;setActionBusy(order._id);setError("");try{const response=await fetch(`/api/orders/${order._id}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Order could not be updated.");setNotice(action==="fulfil"?`${order.orderNumber} physical quantities dispatched.`:`${order.orderNumber} cancelled. Payment state is unchanged.`);await load()}catch(e){setError(e instanceof Error?e.message:"Order could not be updated.")}finally{setActionBusy("")}}
 const open=orders.filter((order)=>order.status==="open"||order.status==="pending_payment").length,unpaid=orders.filter((order)=>order.paymentStatus==="unpaid").length,fulfilled=orders.filter((order)=>order.status==="fulfilled").length;
 return <>
  <div className="catalogue-heading"><div><div className="eyebrow"><i/> SALES OPERATIONS</div><h1>Orders</h1><p>Track order commitments, reserved stock and fulfilment separately from payment.</p></div>{canCreate&&<button className="primary" onClick={()=>{reset();setError("");setShowForm(true)}}><Plus/>Create order</button>}</div>
  <div className="catalogue-stats"><div><small>ORDERS</small><b>{busy?"—":total}</b></div><div><small>OPEN IN VIEW</small><b>{busy?"—":open}</b></div><div><small>UNPAID IN VIEW</small><b>{busy?"—":unpaid}</b></div><div><small>FULFILLED IN VIEW</small><b>{busy?"—":fulfilled}</b></div></div>
  <section className="catalogue-card"><div className="catalogue-toolbar"><label className="catalogue-search"><Search/><input aria-label="Search orders" placeholder="Search order number or customer" value={query} onChange={(e)=>{setPage(1);setQuery(e.target.value)}}/>{query&&<button aria-label="Clear search" onClick={()=>{setPage(1);setQuery("")}}><X/></button>}</label><span className="filter-icon"><ShoppingBag/>STATUS</span><select aria-label="Filter orders" value={status} onChange={(e)=>{setPage(1);setStatus(e.target.value)}}><option value="">All orders</option><option value="open">Open</option><option value="pending_payment">Pending payment</option><option value="fulfilled">Fulfilled</option><option value="cancelled">Cancelled</option></select></div>
   <div className="orders-table-head"><span>ORDER</span><span>CUSTOMER</span><span>TOTAL</span><span>PAYMENT</span><span>FULFILMENT</span><span>ACTIONS</span></div>
   {busy?<div className="catalogue-state"><LoaderCircle className="spin"/>Loading orders…</div>:error&&!orders.length?<div className="catalogue-state error-state"><CircleAlert/>{error}<button onClick={()=>void load()}>Try again</button></div>:orders.length===0?<div className="catalogue-empty"><div><ShoppingBag/></div><h2>{query||status?"No orders match this view":"No orders yet"}</h2><p>{query||status?"Change the filters to see more orders.":"Create an order from an active product. Stock is reserved at creation; payments need verified evidence."}</p>{canCreate&&!(query||status)&&<button className="primary" onClick={()=>setShowForm(true)}><Plus/>Create an order</button>}</div>:<div className="orders-rows">{orders.map((order)=><article className="orders-row" key={order._id}><div className="order-reference"><span><PackageCheck/></span><div><b>{order.orderNumber}</b><small>{new Date(order.createdAt).toLocaleDateString()} · {order.lines.length} {order.lines.length===1?"line":"lines"}</small></div></div><div className="order-customer"><b>{order.customerSnapshot?.name||"Customer"}</b><small>{order.customerSnapshot?.email||""}</small></div><b className="order-total">{formatMinorUnits(order.totalMinor,order.currency||currency,"en")}</b><span className={`order-payment ${order.paymentStatus}`}>{order.paymentStatus.replaceAll("_"," ")}</span><span className={`status-chip ${order.fulfilmentStatus==="fulfilled"||order.fulfilmentStatus==="partially_fulfilled"?"active":order.fulfilmentStatus==="cancelled"?"archived":"draft"}`}>{order.fulfilmentStatus.replaceAll("_"," ")}</span><div className="order-actions">{canReadPayments&&<button title="View payment ledger" onClick={()=>setLedgerOrder(order)}><Banknote/></button>}{canFulfil&&order.fulfilments?.some(event=>event.eventType==="dispatch")&&<a className="order-icon-action" href={`/orders/${order._id}/packing-slip`} target="_blank" rel="noreferrer" title="Print packing slip" aria-label={`Print packing slip for ${order.orderNumber}`}><Printer/></a>}{(order.status==="open"||order.status==="pending_payment")&&<>{canFulfil&&hasDispatchable(order)&&<><button disabled={actionBusy===order._id} title="Dispatch selected quantities" onClick={()=>beginDispatch(order)}><Truck/></button><button disabled={actionBusy===order._id} title="Dispatch all remaining physical quantities" onClick={()=>void changeOrder(order,"fulfil")}><Check/></button></>}{canFulfil&&hasServiceToComplete(order)&&<button disabled={actionBusy===order._id} title="Complete service work" onClick={()=>beginServiceCompletion(order)}><ClipboardCheck/></button>}{canCreate&&<button disabled={actionBusy===order._id} title="Cancel order and release remaining stock" onClick={()=>void changeOrder(order,"cancel")}><X/></button>}</>}</div></article>)}</div>}
   {error&&orders.length>0&&<div className="inline-error"><CircleAlert/>{error}</div>}<div className="catalogue-foot"><span>Payment stays unpaid until verified provider evidence is recorded.</span><div className="page-controls"><small>{total?`${(page-1)*25+1}–${Math.min(page*25,total)} of ${total}`:"0 orders"}</small><button disabled={page<=1||busy} aria-label="Previous page" onClick={()=>setPage((n)=>Math.max(1,n-1))}><ChevronLeft/></button><button disabled={page>=pageCount||busy} aria-label="Next page" onClick={()=>setPage((n)=>Math.min(pageCount,n+1))}><ChevronRight/></button></div></div>
  </section>
  {ledgerOrder&&<PaymentLedger order={ledgerOrder} currency={currency} canCapture={canCapturePayments} canRefund={canRefundPayments} onClose={()=>setLedgerOrder(null)} onSaved={()=>{setNotice("Payment ledger updated.");void load()}}/>}
  {notice&&<div className="toast"><Check/>{notice}<button aria-label="Dismiss" onClick={()=>setNotice("")}><X/></button></div>}
  {showForm&&<div className="backdrop" role="presentation" onMouseDown={(e)=>{if(e.target===e.currentTarget){setShowForm(false);reset()}}}><form className="modal catalogue-modal order-modal" onSubmit={create}><header><div><ShoppingBag/></div><button type="button" aria-label="Close" onClick={()=>{setShowForm(false);reset()}}><X/></button></header><small>ORDERS · NATIVE STORE</small><h2>Create a sales order</h2><p>Price and tax are snapshotted from the active catalogue when saved.</p><div className="auth-fields"><div><label htmlFor="order-customer">Customer</label><select id="order-customer" required value={customerId} onChange={(e)=>setCustomerId(e.target.value)}><option value="">Choose a customer</option>{customers.filter((c)=>c.status!=="archived").map((c)=><option key={c._id} value={c._id}>{c.name}{c.email?` · ${c.email}`:""}</option>)}</select></div>{lineItems.map((line,index)=><div className="order-line" key={index}><div><label htmlFor={`order-product-${index}`}>Product or service</label><select id={`order-product-${index}`} required value={line.itemId} onChange={(e)=>setLineItems((current)=>current.map((entry,i)=>i===index?{...entry,itemId:e.target.value}:entry))}><option value="">Choose an active product or service</option>{products.map((p)=><option key={p._id} value={p._id} disabled={lineItems.some((other,i)=>i!==index&&other.itemId===p._id)}>{p.name} · {p.kind==="service"?"Service":"Physical"} · {formatMinorUnits(p.unitPriceMinor,currency,"en")}{p.trackInventory?` · ${p.stockOnHand-p.stockReserved} available`:""}</option>)}</select></div><div><label htmlFor={`order-quantity-${index}`}>Qty</label><input id={`order-quantity-${index}`} type="number" min="1" max="100000" step="1" required value={line.quantity} onChange={(e)=>setLineItems((current)=>current.map((entry,i)=>i===index?{...entry,quantity:e.target.value}:entry))}/></div>{lineItems.length>1&&<button type="button" className="remove-line" aria-label="Remove order item" onClick={()=>setLineItems((current)=>current.filter((_,i)=>i!==index))}><X/></button>}</div>)}{lineItems.length<50&&<button type="button" className="add-order-line" onClick={()=>setLineItems((current)=>[...current,{itemId:"",quantity:"1"}])}><Plus/>Add another item</button>}<div className="order-payment-note"><ShieldCheck/>Order creation reserves tracked stock. It never marks payment as received.</div></div>{error&&<div className="auth-error"><span>!</span>{error}</div>}<button className="primary submit" disabled={saving||!customers.length||!products.length}>{saving?<LoaderCircle className="spin"/>:<Plus/>}{saving?"Creating order…":"Create order"}<ChevronDown/></button></form></div>}
  {dispatchOrder&&<div className="backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget){setDispatchOrder(null);dispatchAttempt.current=null;setError("")}}}><form className="modal catalogue-modal order-modal" onSubmit={saveDispatch}><header><div><Truck/></div><button type="button" aria-label="Close dispatch" onClick={()=>{setDispatchOrder(null);dispatchAttempt.current=null;setError("")}}><X/></button></header><small>ORDERS · PHYSICAL FULFILMENT</small><h2>Record a dispatch</h2><p>Dispatch reduces reserved stock. Service work and payment status remain separate.</p><div className="auth-fields">{dispatchOrder.lines.map((line,index)=>{const sent=dispatched(dispatchOrder,index),remaining=Math.max(0,line.quantity-sent),fieldId="dispatch-quantity-"+index;return <div className="order-line" key={index}><div><b>{line.name}</b><small>{line.kind==="service"?"Service · completed separately":sent+" sent · "+remaining+" remaining"}</small></div><div><label htmlFor={fieldId}>Send now</label><input id={fieldId} type="number" min="0" max={remaining} step="1" disabled={line.kind!=="physical"||remaining===0} value={dispatchQuantities[index]??"0"} onChange={event=>setDispatchQuantities(current=>current.map((value,i)=>i===index?event.target.value:value))}/></div></div>})}<div className="order-payment-note"><ShieldCheck/>Each dispatch is saved to the order history. Only operations staff and owners can dispatch.</div></div>{error&&<div className="auth-error" role="alert"><span>!</span>{error}</div>}<button className="primary submit" disabled={actionBusy===dispatchOrder._id||!dispatchQuantities.some(value=>Number(value)>0)}>{actionBusy===dispatchOrder._id?<LoaderCircle className="spin"/>:<Truck/>}{actionBusy===dispatchOrder._id?"Recording dispatch…":"Record dispatch"}<ChevronDown/></button></form></div>}
  {serviceOrder&&<div className="backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget){setServiceOrder(null);serviceAttempt.current=null;setError("")}}}><form className="modal catalogue-modal order-modal" onSubmit={saveServiceCompletion}><header><div><ClipboardCheck/></div><button type="button" aria-label="Close service completion" onClick={()=>{setServiceOrder(null);serviceAttempt.current=null;setError("")}}><X/></button></header><small>ORDERS · SERVICE FULFILMENT</small><h2>Record completed service</h2><p>Record the service quantities completed in this work session.</p><div className="auth-fields">{serviceOrder.lines.map((line,index)=>{const done=serviceCompleted(serviceOrder,index),remaining=Math.max(0,line.quantity-done),fieldId="service-quantity-"+index;return <div className="order-line" key={index}><div><b>{line.name}</b><small>{line.kind==="service"?done+" completed · "+remaining+" remaining":"Physical item · dispatched separately"}</small></div><div><label htmlFor={fieldId}>Complete now</label><input id={fieldId} type="number" min="0" max={remaining} step="1" disabled={line.kind!=="service"||remaining===0} value={serviceQuantities[index]??"0"} onChange={event=>setServiceQuantities(current=>current.map((value,i)=>i===index?event.target.value:value))}/></div></div>})}<label htmlFor="service-completion-note">Work note <small>Optional · up to 500 characters</small></label><textarea id="service-completion-note" maxLength={500} rows={3} value={serviceNote} onChange={event=>setServiceNote(event.target.value)} placeholder="What was completed? Add any handover details."/><div className="service-history"><b>Previous service entries</b>{(serviceOrder.fulfilments||[]).filter(entry=>entry.eventType==="service_completion").length===0?<small>No service work recorded yet.</small>:(serviceOrder.fulfilments||[]).filter(entry=>entry.eventType==="service_completion").map((entry,index)=><small key={index}>{entry.occurredAt?new Date(entry.occurredAt).toLocaleString():"Completion recorded"} · {entry.lines.map(part=>`${serviceOrder.lines[part.lineIndex]?.name||"Service"} × ${part.quantity}`).join(", ")}{entry.note?` · ${entry.note}`:""}</small>)}</div><div className="order-payment-note"><ShieldCheck/>Completion is immutable in the order history. Payment status does not change.</div></div>{error&&<div className="auth-error" role="alert"><span>!</span>{error}</div>}<button className="primary submit" disabled={actionBusy===serviceOrder._id||!serviceQuantities.some(value=>Number(value)>0)}>{actionBusy===serviceOrder._id?<LoaderCircle className="spin"/>:<ClipboardCheck/>}{actionBusy===serviceOrder._id?"Recording completion…":"Record service completion"}<ChevronDown/></button></form></div>}
 </>;
}




