"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {Banknote,Check,ChevronDown,ChevronLeft,ChevronRight,CircleAlert,LoaderCircle,PackageCheck,Plus,Search,ShieldCheck,ShoppingBag,X} from "lucide-react";
import {formatMinorUnits} from "@/server/domain/money";
import PaymentLedger from "./PaymentLedger";
type Customer={_id:string;name:string;email:string|null;status:string};
type Product={_id:string;name:string;unitPriceMinor:number;trackInventory:boolean;stockOnHand:number;stockReserved:number};
type Order={_id:string;orderNumber:string;customerSnapshot:{name:string;email:string|null};lines:{name:string;quantity:number}[];currency:string;totalMinor:number;status:"open"|"pending_payment"|"fulfilled"|"cancelled";paymentStatus:string;fulfilmentStatus:string;createdAt:string};
export default function OrdersPanel({currency,canCreate,canReadPayments=false,canCapturePayments=false,canRefundPayments=false}:{currency:string;canCreate:boolean;canReadPayments?:boolean;canCapturePayments?:boolean;canRefundPayments?:boolean}){
 const[orders,setOrders]=useState<Order[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[products,setProducts]=useState<Product[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[pageCount,setPageCount]=useState(0),[status,setStatus]=useState(""),[query,setQuery]=useState(""),[busy,setBusy]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[showForm,setShowForm]=useState(false),[customerId,setCustomerId]=useState(""),[lineItems,setLineItems]=useState([{itemId:"",quantity:"1"}]),[saving,setSaving]=useState(false),[actionBusy,setActionBusy]=useState(""),[ledgerOrder,setLedgerOrder]=useState<Order|null>(null);
 const attempt=useRef<{signature:string;key:string}|null>(null);
 const load=useCallback(async()=>{setBusy(true);setError("");try{const params=new URLSearchParams({page:String(page),limit:"25"});if(status)params.set("status",status);if(query.trim())params.set("q",query.trim());const response=await fetch(`/api/orders?${params}`,{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"Could not load orders.");setOrders(data.orders||[]);setTotal(data.total||0);setPageCount(data.pageCount||0)}catch(e){setError(e instanceof Error?e.message:"Could not load orders.")}finally{setBusy(false)}},[page,status,query]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),query?200:0);return()=>clearTimeout(timer)},[load,query]);
 useEffect(()=>{if(!canCreate)return;Promise.all([fetch("/api/customers?limit=100",{cache:"no-store"}),fetch("/api/catalogue?status=active&kind=physical&limit=100",{cache:"no-store"})]).then(async([cr,pr])=>{const[c,p]=await Promise.all([cr.json(),pr.json()]);if(!cr.ok)throw new Error(c.error||"Could not load customers.");if(!pr.ok)throw new Error(p.error||"Could not load products.");setCustomers(c.customers||[]);setProducts(p.items||[]) }).catch((e)=>setError(e instanceof Error?e.message:"Order entry data could not be loaded."))},[canCreate]);
 function reset(){setCustomerId("");setLineItems([{itemId:"",quantity:"1"}]);attempt.current=null}
 async function create(event:React.FormEvent){event.preventDefault();setSaving(true);setError("");try{const payload={customerId,lines:lineItems.map((line)=>({itemId:line.itemId,quantity:Number(line.quantity)}))};const signature=JSON.stringify(payload);if(!attempt.current||attempt.current.signature!==signature)attempt.current={signature,key:crypto.randomUUID()};const response=await fetch("/api/orders",{method:"POST",headers:{"content-type":"application/json","idempotency-key":attempt.current.key},body:signature});const data=await response.json();if(!response.ok)throw new Error(data.error||"Order could not be created.");setNotice(`${data.order.orderNumber} created. Stock is reserved; payment remains unpaid.`);setShowForm(false);reset();setPage(1);await load()}catch(e){setError(e instanceof Error?e.message:"Order could not be created.")}finally{setSaving(false)}}
 async function changeOrder(order:Order,action:"fulfil"|"cancel"){const message=action==="fulfil"?`Mark ${order.orderNumber} as fulfilled and deduct reserved stock?`:`Cancel ${order.orderNumber} and release reserved stock? Payment will not change.`;if(!window.confirm(message))return;setActionBusy(order._id);setError("");try{const response=await fetch(`/api/orders/${order._id}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Order could not be updated.");setNotice(action==="fulfil"?`${order.orderNumber} fulfilled.`:`${order.orderNumber} cancelled. Payment state is unchanged.`);await load()}catch(e){setError(e instanceof Error?e.message:"Order could not be updated.")}finally{setActionBusy("")}}
 const open=orders.filter((order)=>order.status==="open"||order.status==="pending_payment").length,unpaid=orders.filter((order)=>order.paymentStatus==="unpaid").length,fulfilled=orders.filter((order)=>order.status==="fulfilled").length;
 return <>
  <div className="catalogue-heading"><div><div className="eyebrow"><i/> SALES OPERATIONS</div><h1>Orders</h1><p>Track order commitments, reserved stock and fulfilment separately from payment.</p></div>{canCreate&&<button className="primary" onClick={()=>{reset();setError("");setShowForm(true)}}><Plus/>Create order</button>}</div>
  <div className="catalogue-stats"><div><small>ORDERS</small><b>{busy?"—":total}</b></div><div><small>OPEN IN VIEW</small><b>{busy?"—":open}</b></div><div><small>UNPAID IN VIEW</small><b>{busy?"—":unpaid}</b></div><div><small>FULFILLED IN VIEW</small><b>{busy?"—":fulfilled}</b></div></div>
  <section className="catalogue-card"><div className="catalogue-toolbar"><label className="catalogue-search"><Search/><input aria-label="Search orders" placeholder="Search order number or customer" value={query} onChange={(e)=>{setPage(1);setQuery(e.target.value)}}/>{query&&<button aria-label="Clear search" onClick={()=>{setPage(1);setQuery("")}}><X/></button>}</label><span className="filter-icon"><ShoppingBag/>STATUS</span><select aria-label="Filter orders" value={status} onChange={(e)=>{setPage(1);setStatus(e.target.value)}}><option value="">All orders</option><option value="open">Open</option><option value="pending_payment">Pending payment</option><option value="fulfilled">Fulfilled</option><option value="cancelled">Cancelled</option></select></div>
   <div className="orders-table-head"><span>ORDER</span><span>CUSTOMER</span><span>TOTAL</span><span>PAYMENT</span><span>FULFILMENT</span><span>ACTIONS</span></div>
   {busy?<div className="catalogue-state"><LoaderCircle className="spin"/>Loading orders…</div>:error&&!orders.length?<div className="catalogue-state error-state"><CircleAlert/>{error}<button onClick={()=>void load()}>Try again</button></div>:orders.length===0?<div className="catalogue-empty"><div><ShoppingBag/></div><h2>{query||status?"No orders match this view":"No orders yet"}</h2><p>{query||status?"Change the filters to see more orders.":"Create an order from an active product. Stock is reserved at creation; payments need verified evidence."}</p>{canCreate&&!(query||status)&&<button className="primary" onClick={()=>setShowForm(true)}><Plus/>Create an order</button>}</div>:<div className="orders-rows">{orders.map((order)=><article className="orders-row" key={order._id}><div className="order-reference"><span><PackageCheck/></span><div><b>{order.orderNumber}</b><small>{new Date(order.createdAt).toLocaleDateString()} · {order.lines.length} {order.lines.length===1?"line":"lines"}</small></div></div><div className="order-customer"><b>{order.customerSnapshot?.name||"Customer"}</b><small>{order.customerSnapshot?.email||""}</small></div><b className="order-total">{formatMinorUnits(order.totalMinor,order.currency||currency,"en")}</b><span className={`order-payment ${order.paymentStatus}`}>{order.paymentStatus.replaceAll("_"," ")}</span><span className={`status-chip ${order.fulfilmentStatus==="fulfilled"?"active":order.fulfilmentStatus==="cancelled"?"archived":"draft"}`}>{order.fulfilmentStatus}</span><div className="order-actions">{canReadPayments&&<button title="View payment ledger" onClick={()=>setLedgerOrder(order)}><Banknote/></button>}{(order.status==="open"||order.status==="pending_payment")&&canCreate&&<><button disabled={actionBusy===order._id} title="Fulfil order" onClick={()=>void changeOrder(order,"fulfil")}><Check/></button><button disabled={actionBusy===order._id} title="Cancel order and release stock" onClick={()=>void changeOrder(order,"cancel")}><X/></button></>}</div></article>)}</div>}
   {error&&orders.length>0&&<div className="inline-error"><CircleAlert/>{error}</div>}<div className="catalogue-foot"><span>Payment stays unpaid until verified provider evidence is recorded.</span><div className="page-controls"><small>{total?`${(page-1)*25+1}–${Math.min(page*25,total)} of ${total}`:"0 orders"}</small><button disabled={page<=1||busy} aria-label="Previous page" onClick={()=>setPage((n)=>Math.max(1,n-1))}><ChevronLeft/></button><button disabled={page>=pageCount||busy} aria-label="Next page" onClick={()=>setPage((n)=>Math.min(pageCount,n+1))}><ChevronRight/></button></div></div>
  </section>
  {ledgerOrder&&<PaymentLedger order={ledgerOrder} currency={currency} canCapture={canCapturePayments} canRefund={canRefundPayments} onClose={()=>setLedgerOrder(null)} onSaved={()=>{setNotice("Payment ledger updated.");void load()}}/>}
  {notice&&<div className="toast"><Check/>{notice}<button aria-label="Dismiss" onClick={()=>setNotice("")}><X/></button></div>}
  {showForm&&<div className="backdrop" role="presentation" onMouseDown={(e)=>{if(e.target===e.currentTarget){setShowForm(false);reset()}}}><form className="modal catalogue-modal order-modal" onSubmit={create}><header><div><ShoppingBag/></div><button type="button" aria-label="Close" onClick={()=>{setShowForm(false);reset()}}><X/></button></header><small>ORDERS · NATIVE STORE</small><h2>Create a sales order</h2><p>Price and tax are snapshotted from the active catalogue when saved.</p><div className="auth-fields"><div><label htmlFor="order-customer">Customer</label><select id="order-customer" required value={customerId} onChange={(e)=>setCustomerId(e.target.value)}><option value="">Choose a customer</option>{customers.filter((c)=>c.status!=="archived").map((c)=><option key={c._id} value={c._id}>{c.name}{c.email?` · ${c.email}`:""}</option>)}</select></div>{lineItems.map((line,index)=><div className="order-line" key={index}><div><label htmlFor={`order-product-${index}`}>Product</label><select id={`order-product-${index}`} required value={line.itemId} onChange={(e)=>setLineItems((current)=>current.map((entry,i)=>i===index?{...entry,itemId:e.target.value}:entry))}><option value="">Choose an active product</option>{products.map((p)=><option key={p._id} value={p._id} disabled={lineItems.some((other,i)=>i!==index&&other.itemId===p._id)}>{p.name} · {formatMinorUnits(p.unitPriceMinor,currency,"en")}{p.trackInventory?` · ${p.stockOnHand-p.stockReserved} available`:""}</option>)}</select></div><div><label htmlFor={`order-quantity-${index}`}>Qty</label><input id={`order-quantity-${index}`} type="number" min="1" max="100000" step="1" required value={line.quantity} onChange={(e)=>setLineItems((current)=>current.map((entry,i)=>i===index?{...entry,quantity:e.target.value}:entry))}/></div>{lineItems.length>1&&<button type="button" className="remove-line" aria-label="Remove order item" onClick={()=>setLineItems((current)=>current.filter((_,i)=>i!==index))}><X/></button>}</div>)}{lineItems.length<50&&<button type="button" className="add-order-line" onClick={()=>setLineItems((current)=>[...current,{itemId:"",quantity:"1"}])}><Plus/>Add another item</button>}<div className="order-payment-note"><ShieldCheck/>Order creation reserves tracked stock. It never marks payment as received.</div></div>{error&&<div className="auth-error"><span>!</span>{error}</div>}<button className="primary submit" disabled={saving||!customers.length||!products.length}>{saving?<LoaderCircle className="spin"/>:<Plus/>}{saving?"Creating order…":"Create order and reserve stock"}<ChevronDown/></button></form></div>}
 </>;
}




