"use client";
import {useEffect,useRef,useState} from "react";
import {Banknote,Check,CircleAlert,LoaderCircle,ShieldCheck,X} from "lucide-react";
import {formatMinorUnits} from "@/server/domain/money";
type Order={_id:string;orderNumber:string;totalMinor:number;currency:string;paymentStatus:string};
type Entry={_id:string;direction:"capture"|"refund";method:string;amountMinor:number;currency:string;reference:string;note:string;verifiedBy?:{name:string};createdAt:string};
export default function PaymentLedger({order,currency,canCapture,canRefund,onClose,onSaved}:{order:Order;currency:string;canCapture:boolean;canRefund:boolean;onClose:()=>void;onSaved:()=>void}){
 const[entries,setEntries]=useState<Entry[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[direction,setDirection]=useState<"capture"|"refund">(canCapture?"capture":"refund"),[method,setMethod]=useState("bank_transfer"),[amount,setAmount]=useState(""),[reference,setReference]=useState(""),[note,setNote]=useState(""),[saving,setSaving]=useState(false);
 const attempt=useRef<{signature:string;key:string}|null>(null);const activeCurrency=order.currency||currency;const digits=new Intl.NumberFormat("en",{style:"currency",currency:activeCurrency}).resolvedOptions().maximumFractionDigits??2;
 useEffect(()=>{let alive=true;fetch(`/api/orders/${order._id}/payments`,{cache:"no-store"}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||"Payment history could not be loaded.");if(alive)setEntries(data.entries||[])}).catch(e=>alive&&setError(e instanceof Error?e.message:"Payment history could not be loaded.")).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[order._id]);
 async function save(event:React.FormEvent){event.preventDefault();setError("");const amountMinor=Math.round(Number(amount)*10**digits);if(!Number.isSafeInteger(amountMinor)||amountMinor<1){setError("Enter a valid amount greater than zero.");return}const payload={direction,method,amountMinor,reference,note},signature=JSON.stringify(payload);if(!attempt.current||attempt.current.signature!==signature)attempt.current={signature,key:crypto.randomUUID()};setSaving(true);try{const response=await fetch(`/api/orders/${order._id}/payments`,{method:"POST",headers:{"content-type":"application/json","idempotency-key":attempt.current.key},body:signature}),data=await response.json();if(!response.ok)throw new Error(data.error||"The ledger entry could not be saved.");setEntries(current=>[...current,data.entry]);setAmount("");setReference("");setNote("");attempt.current=null;onSaved()}catch(e){setError(e instanceof Error?e.message:"The ledger entry could not be saved.")}finally{setSaving(false)}}
 const canAdd=canCapture||canRefund;
 return <div className="backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className="modal catalogue-modal ledger-modal" role="dialog" aria-modal="true" aria-labelledby="ledger-heading"><header><div><Banknote/></div><button type="button" aria-label="Close" onClick={onClose}><X/></button></header><small>ORDERS · PAYMENT LEDGER</small><h2 id="ledger-heading">{order.orderNumber}</h2><p>{formatMinorUnits(order.totalMinor,activeCurrency,"en")} order total · {order.paymentStatus.replaceAll("_"," ")}</p>{error&&<div className="auth-error"><span>!</span>{error}</div>}
 {loading?<div className="catalogue-state"><LoaderCircle className="spin"/>Loading verified entries…</div>:entries.length===0?<div className="ledger-empty"><ShieldCheck/><span>No manual payment entries yet.</span></div>:<div className="ledger-list">{entries.map(entry=><article key={entry._id}><span className={`ledger-icon ${entry.direction}`}><Banknote/></span><div><b>{entry.direction==="capture"?"Payment verified":"Refund verified"}</b><small>{entry.method.replaceAll("_"," ")}{entry.reference?` · ${entry.reference}`:""}{entry.verifiedBy?.name?` · ${entry.verifiedBy.name}`:""}</small>{entry.note&&<small>{entry.note}</small>}</div><strong className={entry.direction}>{entry.direction==="refund"?"−":"+"}{formatMinorUnits(entry.amountMinor,entry.currency,"en")}</strong><time>{new Date(entry.createdAt).toLocaleDateString()}</time></article>)}</div>}
 {canAdd&&!loading&&<form className="ledger-form" onSubmit={save}><div className="ledger-form-head"><strong>Record a verified entry</strong><small>Save only after you confirm the money moved.</small></div><div className="form-row"><div><label htmlFor="ledger-direction">Entry type</label><select id="ledger-direction" value={direction} onChange={event=>{setDirection(event.target.value as "capture"|"refund");attempt.current=null}}><option value="capture" disabled={!canCapture}>Payment received</option><option value="refund" disabled={!canRefund}>Refund sent</option></select></div><div><label htmlFor="ledger-method">Method</label><select id="ledger-method" value={method} onChange={event=>{setMethod(event.target.value);attempt.current=null}}><option value="bank_transfer">Bank transfer</option><option value="cash">Cash</option><option value="other">Other</option></select></div></div><div className="form-row"><div><label htmlFor="ledger-amount">Amount ({activeCurrency})</label><input id="ledger-amount" type="number" min={1/(10**digits)} step={1/(10**digits)} required value={amount} onChange={event=>{setAmount(event.target.value);attempt.current=null}}/></div><div><label htmlFor="ledger-reference">Reference <span className="optional">OPTIONAL</span></label><input id="ledger-reference" maxLength={120} value={reference} onChange={event=>{setReference(event.target.value);attempt.current=null}} placeholder="Transfer or receipt ID"/></div></div><div><label htmlFor="ledger-note">Note <span className="optional">OPTIONAL</span></label><textarea id="ledger-note" maxLength={500} value={note} onChange={event=>{setNote(event.target.value);attempt.current=null}} placeholder="Add context for the audit trail"/></div><div className="disclosure"><ShieldCheck/>The entry and verifier are saved to the audit history.</div><button className="primary submit" disabled={saving}>{saving?<LoaderCircle className="spin"/>:<Check/>}{saving?"Saving entry…":"Save verified entry"}</button></form>}
 </section></div>
}
