"use client";
import {useCallback,useEffect,useState} from "react";
type PortalData={customer:{name:string;company?:string|null};tenant:{name:string;baseCurrency:string};orders:any[];quotes:any[];appointments:any[];cases:any[]};
const money=(minor:number,currency:string)=>new Intl.NumberFormat(undefined,{style:"currency",currency}).format(minor/100);
const date=(value:string)=>new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));
export default function PublicCustomerPortal({token}:{token:string}){
 const [data,setData]=useState<PortalData|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(true),[form,setForm]=useState(false),[sending,setSending]=useState(false),[notice,setNotice]=useState("");
 const load=useCallback(async()=>{setBusy(true);try{const response=await fetch(`/api/portal/${encodeURIComponent(token)}`,{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error(body.error||"This link is unavailable.");setData(body);setError("")}catch(e){setError(e instanceof Error?e.message:"This link is unavailable.")}finally{setBusy(false)}},[token]);
 useEffect(()=>{void load()},[load]);
 async function submitCase(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setSending(true);setNotice("");const formData=new FormData(event.currentTarget);try{const response=await fetch(`/api/portal/${encodeURIComponent(token)}/cases`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:formData.get("kind"),subject:formData.get("subject"),message:formData.get("message")})}),body=await response.json();if(!response.ok)throw new Error(body.error||"Could not send your request.");setForm(false);setNotice("Your support request was sent.");await load()}catch(e){setNotice(e instanceof Error?e.message:"Could not send your request.")}finally{setSending(false)}}
 async function acceptQuote(id:string){setNotice("");try{const response=await fetch(`/api/portal/${encodeURIComponent(token)}/quotes/${id}/accept`,{method:"POST"}),body=await response.json();if(!response.ok)throw new Error(body.error||"Could not accept this quote.");setNotice("Quote accepted.");await load()}catch(e){setNotice(e instanceof Error?e.message:"Could not accept this quote.")}}
 async function reply(caseId:string,message:string){const response=await fetch(`/api/portal/${encodeURIComponent(token)}/cases/${caseId}/reply`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message})}),body=await response.json();if(!response.ok)throw new Error(body.error||"Could not send reply.");await load()}
 if(busy)return <main className="cp-shell"><div className="cp-loading"><i/><span>Opening your secure portal</span></div></main>;
 if(error||!data)return <main className="cp-shell"><section className="cp-error"><div className="cp-brand"><b>Commerce<span>Desk</span></b></div><div className="cp-icon">↗</div><h1>This portal link is unavailable</h1><p>{error||"This link may have expired. Contact the business for a fresh link."}</p></section></main>;
 return <main className="cp-shell"><header className="cp-top"><div className="cp-brand"><span className="cp-mark">c</span><b>Commerce<span>Desk</span></b></div><span className="cp-secure">PRIVATE CUSTOMER PORTAL <i/></span></header><section className="cp-hero"><div><small>YOUR ACCOUNT</small><h1>Good to see you, {data.customer.name.split(" ")[0]}.</h1><p>Your orders, appointments, quotes and support in one place.</p></div><div className="cp-orbit"><i/><i/><i/><b>{data.customer.name.slice(0,1).toUpperCase()}</b></div></section>
 {notice&&<div className="cp-notice" role="status">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
 <section className="cp-section"><div className="cp-section-title"><div><small>01 / PURCHASES</small><h2>Order history</h2></div><span>{data.orders.length} ORDERS</span></div>{data.orders.length?<div className="cp-grid">{data.orders.map(order=><article className="cp-card" key={order._id}><div className="cp-card-head"><b>Order {order.orderNumber}</b><span>{order.status.replaceAll("_"," ")}</span></div><p>{order.lines.map((line:any)=>`${line.quantity} × ${line.name}`).join(" · ")}</p><div className="cp-card-foot"><span>{date(order.createdAt)}</span><b>{money(order.totalMinor,order.currency)}</b></div><small className="cp-subtle">Payment: {order.paymentStatus.replaceAll("_"," ")} · Fulfilment: {order.fulfilmentStatus}</small></article>)}</div>:<p className="cp-empty">Orders associated with your account will appear here.</p>}</section>
 <section className="cp-section"><div className="cp-section-title"><div><small>02 / DECISIONS</small><h2>Quotes</h2></div><span>{data.quotes.length} QUOTES</span></div>{data.quotes.length?<div className="cp-grid">{data.quotes.map(quote=><article className="cp-card" key={quote._id}><div className="cp-card-head"><b>Quote {quote.quoteNumber}</b><span>{quote.status}</span></div>{quote.revision&&<><p>{quote.revision.lines.map((line:any)=>`${line.quantity} × ${line.name}`).join(" · ")}</p><div className="cp-card-foot"><span>Valid until {date(quote.revision.expiresAt)}</span><b>{money(quote.revision.totalMinor,quote.revision.currency)}</b></div>{quote.revision.terms&&<small className="cp-subtle">{quote.revision.terms}</small>}</>}{quote.status==="issued"&&new Date(quote.expiresAt)>new Date()&&<button className="cp-button" onClick={()=>void acceptQuote(quote._id)}>Accept quote <span>↗</span></button>}</article>)}</div>:<p className="cp-empty">Quotes shared with you will appear here.</p>}</section>
 <section className="cp-section"><div className="cp-section-title"><div><small>03 / SCHEDULE</small><h2>Appointments</h2></div><span>{data.appointments.length} VISITS</span></div>{data.appointments.length?<div className="cp-grid">{data.appointments.map(item=><article className="cp-card" key={item._id}><div className="cp-card-head"><b>{item.serviceName}</b><span>{item.status.replaceAll("_"," ")}</span></div><p>{date(item.startsAt)} · {item.businessTimezone}</p><div className="cp-card-foot"><span>{item.resourceName}</span><b>{item.serviceDurationMinutes} min</b></div></article>)}</div>:<p className="cp-empty">Your appointments will appear here.</p>}</section>
 <section className="cp-section"><div className="cp-section-title"><div><small>04 / WE’RE HERE</small><h2>Support</h2><p>Only messages shared with you appear in this conversation.</p></div><button className="cp-button" onClick={()=>setForm(!form)}>New request <span>＋</span></button></div>{form&&<form className="cp-form" onSubmit={submitCase}><label>Type<select name="kind"><option value="question">Question</option><option value="delivery">Delivery</option><option value="return">Return</option><option value="damaged">Damaged item</option><option value="other">Other</option></select></label><label>Subject<input name="subject" minLength={3} maxLength={180} required placeholder="How can we help?"/></label><label>Message<textarea name="message" minLength={3} maxLength={2000} required placeholder="Tell us a little more…"/></label><button className="cp-button" disabled={sending}>{sending?"Sending…":"Send request"}<span>↗</span></button></form>}{data.cases.length?<div className="cp-conversations">{data.cases.map(item=><article className="cp-conversation" key={item._id}><div className="cp-card-head"><b>{item.subject}</b><span>{item.status.replaceAll("_"," ")}</span></div><small>{item.kind} · updated {date(item.updatedAt)}</small>{item.events.map((event:any,index:number)=><div className="cp-message" key={`${item._id}-${index}`}><small>{event.action.includes("staff")?data.tenant.name:data.customer.name} · {date(event.createdAt)}</small><p>{event.body}</p></div>)}{!["closed","resolved"].includes(item.status)&&<ReplyForm onSubmit={(message)=>reply(item._id,message)}/>}</article>)}</div>:<p className="cp-empty">Your support conversations will appear here.</p>}</section>
 <footer className="cp-footer"><b>{data.tenant.name}</b><span>Secure customer access · CommerceDesk</span></footer></main>
}
function ReplyForm({onSubmit}:{onSubmit:(value:string)=>Promise<void>}){const [value,setValue]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");return <form className="cp-reply" onSubmit={async event=>{event.preventDefault();setBusy(true);setError("");try{await onSubmit(value);setValue("")}catch(e){setError(e instanceof Error?e.message:"Could not send reply.")}finally{setBusy(false)}}}><input aria-label="Reply" value={value} maxLength={2000} onChange={e=>setValue(e.target.value)} placeholder="Write a reply…" required/><button disabled={busy||!value.trim()}>{busy?"Sending":"Reply ↗"}</button>{error&&<small>{error}</small>}</form>}
