"use client";
import {useCallback,useEffect,useState} from "react";
import {ArrowUpRight,Check,CircleAlert,LoaderCircle,LockKeyhole,Save,Store,Truck} from "lucide-react";
import {formatMinorUnits} from "@/server/domain/money";
type Settings={storefrontEnabled:boolean;storefrontDescription:string;storefrontTerms:string;storefrontPrivacy:string;storefrontContactEmail:string;deliveryEnabled:boolean;deliveryFlatFeeMinor:number;deliveryTaxRateBps:number;deliveryTaxMode:"inclusive"|"exclusive";pickupEnabled:boolean;bankTransferEnabled:boolean;bankTransferInstructions:string;storefrontPaymentMode:"full"|"deposit";storefrontDepositPercentBps:number;cashOnPickupEnabled:boolean;reservationMinutes:number;storeSlug:string;storeName:string;currency:string;commerceMode:string};
const blank:Settings={storefrontEnabled:false,storefrontDescription:"",storefrontTerms:"",storefrontPrivacy:"",storefrontContactEmail:"",deliveryEnabled:false,deliveryFlatFeeMinor:0,deliveryTaxRateBps:0,deliveryTaxMode:"exclusive",pickupEnabled:false,bankTransferEnabled:false,bankTransferInstructions:"",storefrontPaymentMode:"full",storefrontDepositPercentBps:3000,cashOnPickupEnabled:false,reservationMinutes:30,storeSlug:"",storeName:"",currency:"USD",commerceMode:"native"};
function majorToMinor(value:string,currency:string){const digits=new Intl.NumberFormat("en",{style:"currency",currency}).resolvedOptions().maximumFractionDigits??2;const number=Number(value);return Number.isFinite(number)&&number>=0?Math.round(number*10**digits):NaN}
export default function StorefrontSettingsPanel(){
 const[settings,setSettings]=useState(blank),[deliveryFee,setDeliveryFee]=useState("0"),[deliveryTaxRate,setDeliveryTaxRate]=useState("0"),[busy,setBusy]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=useCallback(async()=>{setBusy(true);setError("");try{const response=await fetch("/api/store/settings",{cache:"no-store"}),data=await response.json();if(!response.ok)throw new Error(data.error||"Store settings could not be loaded.");const next=data.settings as Settings;setSettings(next);const digits=new Intl.NumberFormat("en",{style:"currency",currency:next.currency}).resolvedOptions().maximumFractionDigits??2;setDeliveryFee((next.deliveryFlatFeeMinor/(10**digits)).toFixed(digits));setDeliveryTaxRate((next.deliveryTaxRateBps/100).toString())}catch(e){setError(e instanceof Error?e.message:"Store settings could not be loaded.")}finally{setBusy(false)}},[]);
 useEffect(()=>{void load()},[load]);
 function update<K extends keyof Settings>(key:K,value:Settings[K]){setSettings(current=>({...current,[key]:value}))}
 async function save(event:React.FormEvent){event.preventDefault();setSaving(true);setError("");setNotice("");try{const payload={storefrontEnabled:settings.storefrontEnabled,storefrontDescription:settings.storefrontDescription,storefrontTerms:settings.storefrontTerms,storefrontPrivacy:settings.storefrontPrivacy,storefrontContactEmail:settings.storefrontContactEmail,deliveryEnabled:settings.deliveryEnabled,deliveryFlatFeeMinor:majorToMinor(deliveryFee,settings.currency),deliveryTaxRateBps:Math.round(Number(deliveryTaxRate)*100),deliveryTaxMode:settings.deliveryTaxMode,pickupEnabled:settings.pickupEnabled,bankTransferEnabled:settings.bankTransferEnabled,bankTransferInstructions:settings.bankTransferInstructions,storefrontPaymentMode:settings.storefrontPaymentMode,storefrontDepositPercentBps:settings.storefrontDepositPercentBps,cashOnPickupEnabled:settings.cashOnPickupEnabled,reservationMinutes:settings.reservationMinutes};if(!Number.isSafeInteger(payload.deliveryFlatFeeMinor))throw new Error("Enter a valid delivery fee.");const response=await fetch("/api/store/settings",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),data=await response.json();if(!response.ok)throw new Error(data.error||"Store settings could not be saved.");setSettings(data.settings);setNotice("Store settings saved.")}catch(e){setError(e instanceof Error?e.message:"Store settings could not be saved.")}finally{setSaving(false)}}
 if(busy)return <div className="catalogue-state"><LoaderCircle className="spin"/>Loading store settings…</div>;
 const digits=new Intl.NumberFormat("en",{style:"currency",currency:settings.currency}).resolvedOptions().maximumFractionDigits??2;
 return <>
  <div className="catalogue-heading"><div><div className="eyebrow"><i/> STORE & CHANNELS</div><h1>Storefront</h1><p>Configure what customers see and the fulfillment and payment options you can support.</p></div>{settings.storefrontEnabled&&settings.storeSlug&&<a className="primary" href={`/store/${settings.storeSlug}`} target="_blank" rel="noreferrer"><Store/>Preview storefront<ArrowUpRight/></a>}</div>
  {settings.commerceMode!=="native"&&<div className="store-mode-note"><LockKeyhole/>This workspace is connected to WooCommerce. Configure its storefront in WooCommerce to preserve one catalogue and stock owner.</div>}
  <form className="store-settings-grid" onSubmit={save}>
   <section className="catalogue-card store-settings-card"><div className="store-settings-title"><span><Store/></span><div><small>PUBLIC EXPERIENCE</small><h2>Store identity</h2></div></div><div className="store-form-body"><label className="store-toggle"><span><b>Open public storefront</b><small>Only explicitly published, active products appear.</small></span><input type="checkbox" checked={settings.storefrontEnabled} disabled={settings.commerceMode!=="native"} onChange={e=>update("storefrontEnabled",e.target.checked)}/></label><div><label htmlFor="store-description">Store introduction</label><textarea id="store-description" maxLength={700} value={settings.storefrontDescription} onChange={e=>update("storefrontDescription",e.target.value)} placeholder="Tell customers what your business offers."/></div><div><label htmlFor="store-terms">Store terms</label><textarea id="store-terms" maxLength={3000} value={settings.storefrontTerms} onChange={e=>update("storefrontTerms",e.target.value)} placeholder="Returns, delivery, order changes and payment conditions. Required before opening."/></div><div><label htmlFor="store-privacy">Privacy notice</label><textarea id="store-privacy" maxLength={3000} value={settings.storefrontPrivacy} onChange={e=>update("storefrontPrivacy",e.target.value)} placeholder="Explain how checkout contact and address data will be used. Required before opening."/></div><div><label htmlFor="store-contact">Public contact email <span className="optional">OPTIONAL</span></label><input id="store-contact" type="email" maxLength={254} value={settings.storefrontContactEmail} onChange={e=>update("storefrontContactEmail",e.target.value)} placeholder="hello@example.com"/></div>{settings.storeSlug&&<div className="store-url"><span>PUBLIC ADDRESS</span><code>/store/{settings.storeSlug}</code><small>{settings.storeName}</small></div>}</div></section>
   <section className="catalogue-card store-settings-card"><div className="store-settings-title"><span><Truck/></span><div><small>FULFILLMENT</small><h2>Delivery and pickup</h2></div></div><div className="store-form-body"><label className="store-toggle"><span><b>Local delivery</b><small>One flat delivery fee; customer address collected at checkout.</small></span><input type="checkbox" checked={settings.deliveryEnabled} onChange={e=>update("deliveryEnabled",e.target.checked)}/></label>{settings.deliveryEnabled&&<div><label htmlFor="store-delivery-fee">Flat delivery fee ({settings.currency})</label><input id="store-delivery-fee" type="number" min="0" step={1/(10**digits)} value={deliveryFee} onChange={e=>setDeliveryFee(e.target.value)}/><div className="form-row store-tax-row"><div><label htmlFor="store-delivery-tax">Delivery tax rate (%)</label><input id="store-delivery-tax" type="number" min="0" max="1000" step="0.01" value={deliveryTaxRate} onChange={e=>setDeliveryTaxRate(e.target.value)}/></div><div><label htmlFor="store-delivery-tax-mode">Delivery fee tax</label><select id="store-delivery-tax-mode" value={settings.deliveryTaxMode} onChange={e=>update("deliveryTaxMode",e.target.value as Settings["deliveryTaxMode"])}><option value="exclusive">Tax added</option><option value="inclusive">Tax included</option></select></div></div></div>}<label className="store-toggle"><span><b>Pickup</b><small>Customers collect orders from your business.</small></span><input type="checkbox" checked={settings.pickupEnabled} onChange={e=>update("pickupEnabled",e.target.checked)}/></label><div className="form-row"><div><label htmlFor="hold-minutes">Unpaid stock hold</label><select id="hold-minutes" value={settings.reservationMinutes} onChange={e=>update("reservationMinutes",Number(e.target.value))}><option value={15}>15 minutes</option><option value={30}>30 minutes</option><option value={60}>1 hour</option><option value={240}>4 hours</option><option value={1440}>24 hours</option></select></div><div className="store-hold-note"><LockKeyhole/>Held stock releases automatically when the timer expires.</div></div></div></section>
   <section className="catalogue-card store-settings-card"><div className="store-settings-title"><span><LockKeyhole/></span><div><small>PAYMENT TERMS</small><h2>Deposit or full payment</h2></div></div><div className="store-form-body"><label htmlFor="store-payment-mode">Amount due at checkout</label><select id="store-payment-mode" value={settings.storefrontPaymentMode} onChange={e=>update("storefrontPaymentMode",e.target.value as Settings["storefrontPaymentMode"])}><option value="full">Full payment</option><option value="deposit">Deposit, then remaining balance</option></select>{settings.storefrontPaymentMode==="deposit"&&<div><label htmlFor="store-deposit-percent">Initial deposit (%)</label><input id="store-deposit-percent" type="number" min="1" max="99" step="1" value={settings.storefrontDepositPercentBps/100} onChange={e=>update("storefrontDepositPercentBps",Math.round(Number(e.target.value)*100))}/><small>The customer pays this share first. The remaining balance stays on the private order receipt.</small></div>}<p>WooCommerce-connected workspaces stay on their external store payment rules.</p></div></section><section className="catalogue-card store-settings-card"><div className="store-settings-title"><span><LockKeyhole/></span><div><small>MANUAL PAYMENT</small><h2>Instructions at checkout</h2></div></div><div className="store-form-body"><label className="store-toggle"><span><b>Bank transfer</b><small>Payment remains pending until your team verifies receipt.</small></span><input type="checkbox" checked={settings.bankTransferEnabled} onChange={e=>update("bankTransferEnabled",e.target.checked)}/></label>{settings.bankTransferEnabled&&<div><label htmlFor="bank-instructions">Transfer instructions</label><textarea id="bank-instructions" required maxLength={1000} value={settings.bankTransferInstructions} onChange={e=>update("bankTransferInstructions",e.target.value)} placeholder="Bank name, account holder, transfer reference and what the customer should do."/></div>}<label className="store-toggle"><span><b>Cash on pickup</b><small>Available only when pickup is enabled.</small></span><input type="checkbox" checked={settings.cashOnPickupEnabled} onChange={e=>update("cashOnPickupEnabled",e.target.checked)}/></label></div></section>
   <section className="catalogue-card store-settings-card store-summary-card"><div className="store-settings-title"><span><Check/></span><div><small>RELEASE RULES</small><h2>Checkout integrity</h2></div></div><div className="store-form-body"><p>Prices and product tax are recalculated from the catalogue on the server. Delivery tax follows the rate and inclusive/exclusive setting here. The customer sees the selected payment instructions; an order stays unpaid until an authorised staff member verifies the funds.</p><p>Delivery uses the flat fee configured here. Pickup orders require no shipping address. Stock holds expire after the period selected above.</p><span className="store-currency">BASE CURRENCY <b>{settings.currency}</b> · CONFIGURED DURING SETUP</span></div></section>
   {error&&<div className="store-error"><CircleAlert/>{error}</div>}{notice&&<div className="store-notice"><Check/>{notice}</div>}
   <button className="primary store-save" disabled={saving||settings.commerceMode!=="native"}>{saving?<LoaderCircle className="spin"/>:<Save/>}{saving?"Saving settings…":"Save storefront settings"}</button>
  </form>
 </>;
}


