"use client";
import {useCallback,useEffect,useState} from "react";
import {ArrowRight,Check,ChevronRight,CircleAlert,Copy,ExternalLink,KeyRound,LoaderCircle,LockKeyhole,PlugZap,RefreshCw,ShieldCheck,Unplug} from "lucide-react";

type Connection={accountId:string;chargesEnabled:boolean;detailsSubmitted:boolean;status:"connected"|"degraded"|"disconnected"|"setup_required";lastVerifiedAt:string|null;lastEventAt:string|null;lastErrorCode:string|null;updatedAt?:string;livemode?:boolean};
type ApiReply={connection:Connection|null;error?:string};

export default function StripeSettingsPanel({tenantId}:{tenantId:string}){
 const[connection,setConnection]=useState<Connection|null>(null),[apiKey,setApiKey]=useState(""),[webhookSecret,setWebhookSecret]=useState(""),[busy,setBusy]=useState(true),[saving,setSaving]=useState(false),[disconnecting,setDisconnecting]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[copiedWebhook,setCopiedWebhook]=useState(false);
 const load=useCallback(async()=>{setBusy(true);setError("");try{const response=await fetch("/api/integrations/stripe",{cache:"no-store"}),data=await response.json() as ApiReply;if(!response.ok)throw new Error(data.error||"Stripe connection could not be loaded.");setConnection(data.connection)}catch(reason){setError(reason instanceof Error?reason.message:"Stripe connection could not be loaded.")}finally{setBusy(false)}},[]);
 useEffect(()=>{void load()},[load]);
 async function connect(event:React.FormEvent){event.preventDefault();setSaving(true);setError("");setNotice("");try{const response=await fetch("/api/integrations/stripe",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({apiKey,webhookSecret})}),data=await response.json() as ApiReply;if(!response.ok)throw new Error(data.error||"Stripe connection could not be verified.");setConnection(data.connection);setApiKey("");setWebhookSecret("");setNotice(`Verified Stripe account ${data.connection?.accountId||""}. Secrets were saved encrypted for this workspace.`)}catch(reason){setError(reason instanceof Error?reason.message:"Stripe connection could not be verified.")}finally{setSaving(false)}}
 async function disconnect(){setDisconnecting(true);setError("");setNotice("");try{const response=await fetch("/api/integrations/stripe",{method:"DELETE"}),data=await response.json();if(!response.ok)throw new Error(data.error||"Stripe could not be disconnected.");setConnection(null);setNotice("Stripe credentials were removed from this workspace.")}catch(reason){setError(reason instanceof Error?reason.message:"Stripe could not be disconnected.")}finally{setDisconnecting(false)}}
 async function copyWebhookEndpoint(){const url=`${window.location.origin}/api/webhooks/stripe/${tenantId}`;try{await navigator.clipboard.writeText(url);setCopiedWebhook(true);window.setTimeout(()=>setCopiedWebhook(false),2200)}catch{setError("Could not copy the endpoint. Select and copy its address manually.")}}
 const connected=connection?.status==="connected",verified=connection?.lastVerifiedAt?new Date(connection.lastVerifiedAt).toLocaleString():"Not verified yet";
 return <div className="stripe-settings">
  <div className="intro"><div className="eyebrow"><i/>PAYMENTS · INTEGRATIONS</div><a className="stripe-doc-link" href="https://dashboard.stripe.com/apikeys" target="_blank" rel="noreferrer">Open Stripe dashboard <ExternalLink/></a></div>
  <section className="stripe-hero"><div className="stripe-hero-orbit"><span/><span/><span/><b>stripe</b></div><div className="stripe-hero-copy"><small>PAYMENTS INFRASTRUCTURE · STRIPE</small><h1>Connect your<br/><em>payment layer.</em></h1><p>Verify the account, keep its keys encrypted per workspace, and prepare this business for online payments.</p><div className="stripe-assurance"><span><ShieldCheck/>Tenant-scoped secrets</span><i/><span><LockKeyhole/>Encrypted at rest</span><i/><span><PlugZap/>Account verified live</span></div></div><div className="stripe-status-pill"><i className={connected?"is-connected":""}/>{busy?"CHECKING CONNECTION":connected?"ACCOUNT CONNECTED":connection?"ACTION REQUIRED":"NOT CONNECTED"}</div></section>
  <div className="stripe-content-grid">
   <section className="catalogue-card stripe-connection-card" aria-busy={busy}>
    <header className="stripe-card-head"><div><small>WORKSPACE PAYMENT ACCOUNT</small><h2>{connection?`Account ${connection.accountId}`:"Connect Stripe"}</h2><p>{connection?"Credentials are stored encrypted. Secret values are never shown again.":"Add the Stripe secret key and webhook signing secret for this workspace."}</p></div><button className="stripe-refresh" type="button" onClick={()=>void load()} disabled={busy} aria-label="Refresh Stripe connection"><RefreshCw/></button></header>
    {busy?<div className="stripe-state" role="status"><LoaderCircle/>Checking the workspace connection…</div>:connection?<div className="stripe-connection-state"><div className="stripe-state-row"><span className={connected?"stripe-state-icon good":"stripe-state-icon warn"}>{connected?<Check/>:<CircleAlert/>}</span><div><b>{connection.chargesEnabled?"Ready to accept charges":"Connected, setup required"}</b><small>{connection.detailsSubmitted?"Account details submitted":"Stripe account details still need completion"}</small></div><span className={connected?"stripe-state-tag good":"stripe-state-tag warn"}>{connection.status.replace("_"," ").toUpperCase()}</span></div><dl className="stripe-meta"><div><dt>Account</dt><dd>{connection.accountId}</dd></div><div><dt>Charges</dt><dd>{connection.chargesEnabled?"Enabled":"Not enabled"}</dd></div><div><dt>Last verified</dt><dd>{verified}</dd></div><div><dt>Webhook events</dt><dd>{connection.lastEventAt?new Date(connection.lastEventAt).toLocaleString():"Not received yet"}</dd></div></dl>{connection.lastErrorCode&&<p className="stripe-inline-warn"><CircleAlert/>{connection.lastErrorCode}</p>}<button type="button" className="stripe-disconnect" onClick={()=>void disconnect()} disabled={disconnecting}>{disconnecting?<LoaderCircle/>:<Unplug/>}{disconnecting?"Disconnecting…":"Disconnect account"}</button></div>:<div className="stripe-empty"><span><KeyRound/></span><b>No Stripe account connected</b><p>Connect an account to prepare payment processing for this workspace.</p></div>}
   </section>
   <aside className="catalogue-card stripe-guide"><small>SETUP GUIDE · 02 MIN</small><h2>Three pieces.<br/>One secure link.</h2><ol><li><span>01</span><div><b>Use a restricted secret</b><p>Create a Stripe secret key for this application. Test keys are supported for setup and verification.</p></div></li><li><span>02</span><div><b>Add the webhook secret</b><p>Copy the signing secret from your Stripe webhook endpoint configuration.</p></div></li><li><span>03</span><div><b>Verify the account</b><p>CommerceDesk checks the key with Stripe before encrypting and saving either secret.</p></div></li></ol><div className="stripe-webhook-url"><small>WEBHOOK ENDPOINT · ADD IN STRIPE</small><div><code>/api/webhooks/stripe/{tenantId}</code><button type="button" onClick={()=>void copyWebhookEndpoint()}>{copiedWebhook?<Check/>:<Copy/>}{copiedWebhook?"Copied":"Copy URL"}</button></div><p>Subscribe to checkout.session.completed, checkout.session.expired, checkout.session.async_payment_succeeded and checkout.session.async_payment_failed, refund.created and refund.updated.</p></div><div className="stripe-guide-foot"><LockKeyhole/>Credentials are scoped to the active workspace.</div></aside>
  </div>
  <section className="catalogue-card stripe-key-form"><div className="stripe-form-intro"><span className="stripe-form-icon"><KeyRound/></span><div><small>{connection?"ROTATE OR REPLACE CREDENTIALS":"CONNECT A STRIPE ACCOUNT"}</small><h2>{connection?"Update secure credentials":"Add Stripe credentials"}</h2><p>Submitting new credentials verifies the account before replacing saved values.</p></div></div><form onSubmit={connect}><label>Stripe secret key<input type="password" name="stripeApiKey" autoComplete="new-password" spellCheck={false} required minLength={20} maxLength={255} value={apiKey} onChange={event=>setApiKey(event.target.value)} placeholder="sk_test_… or sk_live_…"/></label><label>Webhook signing secret<input type="password" name="stripeWebhookSecret" autoComplete="new-password" spellCheck={false} required pattern="whsec_[A-Za-z0-9_-]{20,}" value={webhookSecret} onChange={event=>setWebhookSecret(event.target.value)} placeholder="whsec_…"/></label><div className="stripe-form-bottom"><p><LockKeyhole/>Secret fields clear after a successful save and cannot be retrieved later.</p><button className="primary" type="submit" disabled={saving||!apiKey||!webhookSecret}>{saving?<LoaderCircle/>:<ShieldCheck/>}{saving?"Verifying securely…":"Verify & connect"}<ArrowRight/></button></div></form></section>
  <div className="stripe-notes"><div><b>Payment flow</b><span>Checkout and payment requests are still being built. Connecting keys alone does not enable customer charges.</span></div><a href="/settings/store">Storefront settings <ChevronRight/></a></div>
  <div className="stripe-feedback" aria-live="polite">{error&&<p className="error" role="alert"><CircleAlert/>{error}</p>}{notice&&<p className="notice" role="status"><Check/>{notice}</p>}</div>
 </div>
}
