"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {Check,Layers,LoaderCircle,Plus,Power,RefreshCw,X} from "lucide-react";
import {formatMinorUnits} from "@/server/domain/money";

type Option={name:string;value:string};
type Variant={_id:string;name:string;options:Option[];sku:string|null;unitPriceMinor:number|null;active:boolean;stockOnHand:number;stockReserved:number};
type Item={_id:string;name:string;unitPriceMinor:number;trackInventory:boolean};
function parseOptions(value:string):Option[]{return value.split(/[\n,]+/).map(part=>part.trim()).filter(Boolean).map(part=>{const split=part.includes("=")?part.indexOf("="):part.indexOf(":");if(split<1||split===part.length-1)throw new Error("Enter each option as Color=Blue or Size=Large.");return{name:part.slice(0,split).trim(),value:part.slice(split+1).trim()}})}
function minor(value:string,currency:string){if(!value.trim())return null;const digits=new Intl.NumberFormat("en",{style:"currency",currency}).resolvedOptions().maximumFractionDigits??2,n=Number(value);if(!Number.isFinite(n)||n<0)throw new Error("Enter a valid price override.");const result=Math.round(n*10**digits);if(!Number.isSafeInteger(result))throw new Error("The price is too large.");return result}
export default function VariantManager({item,currency,onClose,onChanged}:{item:Item;currency:string;onClose:()=>void;onChanged:()=>void}){
 const[variants,setVariants]=useState<Variant[]>([]),[name,setName]=useState(""),[sku,setSku]=useState(""),[price,setPrice]=useState(""),[options,setOptions]=useState(""),[busy,setBusy]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[adjusting,setAdjusting]=useState<string|null>(null),[stockQty,setStockQty]=useState(""),[stockReason,setStockReason]=useState("receipt"),[stockNote,setStockNote]=useState("");const stockAttempt=useRef<{signature:string;key:string}|null>(null);
 const load=useCallback(async()=>{setBusy(true);setError("");try{const response=await fetch(`/api/catalogue/${item._id}/variants`,{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error(body.error||"Could not load variants.");setVariants(body.variants||[])}catch(e){setError(e instanceof Error?e.message:"Could not load variants.")}finally{setBusy(false)}},[item._id]);
 useEffect(()=>{void load()},[load]);
 async function create(event:React.FormEvent){event.preventDefault();setSaving(true);setError("");setNotice("");try{const payload={name,sku:sku.trim()||null,unitPriceMinor:minor(price,currency),options:parseOptions(options)},response=await fetch(`/api/catalogue/${item._id}/variants`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),body=await response.json();if(!response.ok)throw new Error(body.error||"Variant could not be added.");setName("");setSku("");setPrice("");setOptions("");setNotice(`${body.variant.name} added.`);await load();onChanged()}catch(e){setError(e instanceof Error?e.message:"Variant could not be added.")}finally{setSaving(false)}}
 async function setActive(variant:Variant){setSaving(true);setError("");try{const response=await fetch(`/api/catalogue/${item._id}/variants`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({variantId:variant._id,active:!variant.active})}),body=await response.json();if(!response.ok)throw new Error(body.error||"Variant could not be updated.");setNotice(`${variant.name} ${variant.active?"hidden from sales":"made available"}.`);await load();onChanged()}catch(e){setError(e instanceof Error?e.message:"Variant could not be updated.")}finally{setSaving(false)}}
 async function adjustStock(event:React.FormEvent,variant:Variant){event.preventDefault();setSaving(true);setError("");try{const quantityDelta=Number(stockQty);if(!Number.isSafeInteger(quantityDelta)||quantityDelta===0||(stockReason!=="count_correction"&&quantityDelta<1))throw new Error(stockReason==="count_correction"?"Enter a non-zero whole number.":"Enter a whole number greater than zero.");const payload={variantId:variant._id,quantityDelta,reason:stockReason,note:stockNote},signature=JSON.stringify(payload);if(!stockAttempt.current||stockAttempt.current.signature!==signature)stockAttempt.current={signature,key:crypto.randomUUID()};const response=await fetch(`/api/catalogue/${item._id}/stock`,{method:"POST",headers:{"content-type":"application/json","idempotency-key":stockAttempt.current.key},body:signature}),body=await response.json();if(!response.ok)throw new Error(body.error||"Variant stock could not be adjusted.");setNotice(`Stock updated for ${variant.name}.`);setAdjusting(null);setStockQty("");setStockNote("");stockAttempt.current=null;await load();onChanged()}catch(e){setError(e instanceof Error?e.message:"Variant stock could not be adjusted.")}finally{setSaving(false)}}
 return <div className="backdrop variant-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className="modal catalogue-modal variant-manager" role="dialog" aria-modal="true" aria-labelledby="variant-manager-title"><header><div><Layers/></div><button type="button" aria-label="Close variants" onClick={onClose}><X/></button></header><small>CATALOGUE · PRODUCT VARIANTS</small><h2 id="variant-manager-title">{item.name}</h2><p>Create option combinations such as color and size. Each variant keeps its own SKU and stock balance.</p>{error&&<div className="auth-error" role="alert"><span>!</span>{error}</div>}{notice&&<div className="variant-notice"><Check/>{notice}</div>}
  {busy?<div className="catalogue-state"><LoaderCircle className="spin"/>Loading variants…</div>:<div className="variant-list">{variants.length===0?<div className="variant-empty">No variants yet. Add the first option combination below.</div>:variants.map(variant=><article key={variant._id} className={variant.active?"":"inactive"}><div className="variant-list-main"><b>{variant.name}</b><span>{variant.options.map(option=>`${option.name}: ${option.value}`).join(" · ")}</span><small>{variant.sku||"No variant SKU"} · {formatMinorUnits(variant.unitPriceMinor??item.unitPriceMinor,currency,"en")}</small></div><div className="variant-balance"><b>{variant.stockOnHand-variant.stockReserved}</b><small>available</small></div><div className="variant-actions"><button type="button" disabled={saving||!variant.active||!item.trackInventory} onClick={()=>{setError("");setAdjusting(adjusting===variant._id?null:variant._id);stockAttempt.current=null}}>Adjust stock</button><button type="button" disabled={saving||variant.active&&variant.stockReserved>0} title={variant.active?"Hide variant from sales":"Make variant available"} onClick={()=>void setActive(variant)}><Power/>{variant.active?"Disable":"Enable"}</button>{adjusting===variant._id&&<form className="variant-stock-form" onSubmit={event=>void adjustStock(event,variant)}><label>Quantity change<input type="number" step="1" required value={stockQty} onChange={event=>setStockQty(event.target.value)} placeholder="+5 or -2"/></label><label>Reason<select value={stockReason} onChange={event=>setStockReason(event.target.value)}><option value="receipt">Supplier receipt</option><option value="opening">Opening stock</option><option value="count_correction">Count correction</option></select></label><label>Note<input maxLength={500} value={stockNote} onChange={event=>setStockNote(event.target.value)} placeholder="Optional reference"/></label><button type="submit" disabled={saving}>{saving?<LoaderCircle className="spin"/>:<Check/>}Record adjustment</button></form>}</div></article>)}</div>}
  <form className="variant-create" onSubmit={create}><h3>Add an option combination</h3><div className="auth-fields"><div><label htmlFor="variant-name">Display name</label><input id="variant-name" required minLength={1} maxLength={100} value={name} onChange={event=>setName(event.target.value)} placeholder="Blue / Large"/></div><div><label htmlFor="variant-options">Options</label><input id="variant-options" required value={options} onChange={event=>setOptions(event.target.value)} placeholder="Color=Blue, Size=Large"/><small>Use up to 8 distinct option names.</small></div><div className="form-row"><div><label htmlFor="variant-sku">Variant SKU <span className="optional">OPTIONAL</span></label><input id="variant-sku" maxLength={80} value={sku} onChange={event=>setSku(event.target.value)} placeholder="SHIRT-BLU-L"/></div><div><label htmlFor="variant-price">Price override ({currency}) <span className="optional">OPTIONAL</span></label><input id="variant-price" type="number" min="0" step="0.01" value={price} onChange={event=>setPrice(event.target.value)} placeholder={formatMinorUnits(item.unitPriceMinor,currency,"en")}/></div></div></div><div className="disclosure"><RefreshCw/>New variants start with zero stock. Record variant stock separately after adding.</div><button className="primary submit" disabled={saving}>{saving?<LoaderCircle className="spin"/>:<Plus/>}{saving?"Saving variant…":"Add variant"}</button></form>
 </section></div>
}
