"use client";
import {useEffect,useState} from "react";
import {Building2,ChevronDown,LoaderCircle} from "lucide-react";
type Workspace={id:string;name:string;current:boolean};
export default function WorkspaceSwitcher({tenantName}:{tenantName:string}){
 const[open,setOpen]=useState(false),[items,setItems]=useState<Workspace[]>([]),[busy,setBusy]=useState(false),[switching,setSwitching]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(!open||items.length)return;setBusy(true);fetch("/api/session/workspaces",{cache:"no-store"}).then(async(r)=>{const data=await r.json();if(!r.ok)throw new Error(data.error||"Could not load workspaces.");setItems(data.workspaces||[])}).catch((e)=>setError(e instanceof Error?e.message:"Could not load workspaces.")).finally(()=>setBusy(false))},[open,items.length]);
 async function select(id:string){setSwitching(true);setError("");try{const response=await fetch("/api/session/workspace",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({tenantId:id})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Could not switch workspace.");window.location.reload()}catch(e){setError(e instanceof Error?e.message:"Could not switch workspace.");setSwitching(false)}}
 return <div className="workspace-wrap"><button type="button" className="switcher" onClick={()=>setOpen(!open)} aria-expanded={open}><div className="switch-icon">{tenantName.trim().slice(0,1).toUpperCase()||"C"}</div><div><small>WORKSPACE</small><b>{tenantName}</b></div>{switching?<LoaderCircle className="spin" size={15}/>:<ChevronDown size={15}/>}</button>{open&&<div className="workspace-menu">{busy?<div className="workspace-message"><LoaderCircle className="spin"/>Loading workspaces…</div>:items.length<2?<div className="workspace-message"><Building2/>This account has one workspace.</div>:items.map((item)=><button key={item.id} type="button" disabled={switching||item.current} className={item.current?"current":""} onClick={()=>void select(item.id)}><span>{item.name}</span>{item.current&&<small>CURRENT</small>}</button>)}{error&&<div className="workspace-error">{error}</div>}</div>}</div>;
}
