"use client";
import {useCallback,useEffect,useState} from "react";
import {AlertCircle,CalendarClock,Check,ClipboardCheck,Download,FileUp,LoaderCircle,Plus,Trash2,UserRound} from "lucide-react";

type Task={_id:string;title:string;createdAt:string;completedAt:string|null};
type Attachment={id:string;name:string;contentType:string;sizeBytes:number;purpose:"supporting"|"completion_evidence";createdAt:string};
type WorkOrder={_id:string;orderId:string;orderNumber:string;orderLineIndex:number;customerName:string;serviceName:string;quantity:number;completedQuantity:number;status:"open"|"in_progress"|"completed"|"cancelled";assigneeId:string|null;assigneeName:string|null;dueAt:string|null;tasks:Task[];attachments:Attachment[]};
type Assignee={id:string;name:string;role:string};
function localDateTime(value:string|null){if(!value)return "";const date=new Date(value);date.setMinutes(date.getMinutes()-date.getTimezoneOffset());return date.toISOString().slice(0,16)}

export default function WorkOrdersPanel(){
 const[workOrders,setWorkOrders]=useState<WorkOrder[]>([]),[assignees,setAssignees]=useState<Assignee[]>([]),[role,setRole]=useState("operations"),[filter,setFilter]=useState(""),[busy,setBusy]=useState(true),[saving,setSaving]=useState(""),[uploading,setUploading]=useState(""),[removing,setRemoving]=useState(""),[error,setError]=useState(""),[dueDrafts,setDueDrafts]=useState<Record<string,string>>({}),[taskDrafts,setTaskDrafts]=useState<Record<string,string>>({}),[purposes,setPurposes]=useState<Record<string,"supporting"|"completion_evidence">>({});
 const load=useCallback(async()=>{setBusy(true);setError("");try{const params=new URLSearchParams();if(filter)params.set("status",filter);const response=await fetch(`/api/work-orders?${params}`,{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"Work orders could not be loaded.");setWorkOrders(data.workOrders||[]);setAssignees(data.assignees||[]);setRole(data.role||"operations")}catch(e){setError(e instanceof Error?e.message:"Work orders could not be loaded.")}finally{setBusy(false)}},[filter]);
 useEffect(()=>{void load()},[load]);
 async function update(order:WorkOrder,payload:Record<string,unknown>){setSaving(order._id);setError("");try{const response=await fetch(`/api/work-orders/${order._id}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error||"Work order could not be updated.");await load()}catch(e){setError(e instanceof Error?e.message:"Work order could not be updated.")}finally{setSaving("")}}
 async function addTask(event:React.FormEvent,order:WorkOrder){event.preventDefault();const title=(taskDrafts[order._id]||"").trim();if(title.length<2)return;await update(order,{action:"add_task",title});setTaskDrafts(current=>({...current,[order._id]:""}))}
 async function uploadFile(event:React.FormEvent<HTMLFormElement>,order:WorkOrder){event.preventDefault();const form=event.currentTarget,fileInput=form.elements.namedItem("file");if(!(fileInput instanceof HTMLInputElement)||!fileInput.files?.[0]){setError("Choose a file to attach.");return}const data=new FormData();data.set("file",fileInput.files[0]);data.set("purpose",purposes[order._id]||"supporting");setUploading(order._id);setError("");try{const response=await fetch(`/api/work-orders/${order._id}/attachments`,{method:"POST",body:data});const result=await response.json();if(!response.ok)throw new Error(result.error||"The file could not be uploaded.");form.reset();await load()}catch(e){setError(e instanceof Error?e.message:"The file could not be uploaded.")}finally{setUploading("")}}
 async function removeFile(order:WorkOrder,file:Attachment){if(!window.confirm(`Remove ${file.name}? This cannot be undone.`))return;setRemoving(file.id);setError("");try{const response=await fetch(`/api/work-orders/${order._id}/attachments/${file.id}`,{method:"DELETE"});const result=await response.json();if(!response.ok)throw new Error(result.error||"The file could not be removed.");await load()}catch(e){setError(e instanceof Error?e.message:"The file could not be removed.")}finally{setRemoving("")}}
 async function saveDueDate(order:WorkOrder){const value=dueDrafts[order._id]??localDateTime(order.dueAt);const dueAt=value?new Date(value).toISOString():null;await update(order,{action:"set_due_date",dueAt});setDueDrafts(current=>{const next={...current};delete next[order._id];return next})}
 const openCount=workOrders.filter(item=>item.status==="open"||item.status==="in_progress").length,overdueCount=workOrders.filter(item=>item.dueAt&&new Date(item.dueAt).getTime()<Date.now()&&item.status!=="completed"&&item.status!=="cancelled").length;
 return <section className="work-orders-page">
  <div className="catalogue-heading"><div><div className="eyebrow"><i/>OPERATIONS · SERVICE WORK</div><h1>Work orders</h1><p>Assign service work, set due dates, and track task completion against the customer order.</p></div><button className="secondary" onClick={()=>void load()} disabled={busy}><ClipboardCheck/>Refresh</button></div>
  <div className="catalogue-stats"><div><small>WORK ORDERS</small><b>{busy?"—":workOrders.length}</b></div><div><small>OPEN</small><b>{busy?"—":openCount}</b></div><div><small>OVERDUE</small><b className={overdueCount?"warning-number":""}>{busy?"—":overdueCount}</b></div><div><small>COMPLETED</small><b>{busy?"—":workOrders.filter(item=>item.status==="completed").length}</b></div></div>
  <section className="catalogue-card work-orders-card"><div className="catalogue-toolbar"><div className="work-orders-toolbar"><span>QUEUE</span><select aria-label="Filter work orders" value={filter} onChange={event=>setFilter(event.target.value)}><option value="">All statuses</option><option value="open">Open</option><option value="in_progress">In progress</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select><small>{role==="owner"?"Workspace queue":"Assigned to you"}</small></div></div>
   {error&&<div className="work-orders-error" role="alert"><AlertCircle/>{error}</div>}
   {busy?<div className="catalogue-state"><LoaderCircle className="spin"/>Loading work orders…</div>:workOrders.length===0?<div className="catalogue-empty"><div><ClipboardCheck/></div><h2>{filter?"No work orders in this status":"No service work is waiting"}</h2><p>{role==="owner"?"Service order lines appear here when an order or accepted quote is created.":"New work orders assigned to you will appear here."}</p></div>:<div className="work-orders-list">{workOrders.map(order=>{
    const closed=order.status==="completed"||order.status==="cancelled",overdue=!!order.dueAt&&new Date(order.dueAt).getTime()<Date.now()&&!closed,allTasksDone=order.tasks.every(task=>!!task.completedAt);
    return <article className="work-order" key={order._id}><header className="work-order-head"><span className="work-order-icon"><ClipboardCheck/></span><div className="work-order-title"><small>{order.orderNumber} · {order.customerName}</small><h2>{order.serviceName}</h2><span>{order.completedQuantity} of {order.quantity} service units completed</span></div><span className={`work-order-status ${order.status}`}>{order.status.replaceAll("_"," ")}</span></header>
     <div className="work-order-fields">{role==="owner"&&<label><span><UserRound/>Assignee</span><select aria-label={`Assignee for ${order.serviceName}`} disabled={closed||saving===order._id} value={order.assigneeId||""} onChange={event=>void update(order,{action:"assign",assigneeId:event.target.value||null})}><option value="">Unassigned</option>{assignees.map(person=><option key={person.id} value={person.id}>{person.name} · {person.role}</option>)}</select></label>}{role!=="owner"&&<div className="work-order-assignee"><UserRound/>{order.assigneeName||"Unassigned"}</div>}<label><span><CalendarClock/>Due date</span><input aria-label={`Due date for ${order.serviceName}`} type="datetime-local" disabled={closed||saving===order._id} value={dueDrafts[order._id]??localDateTime(order.dueAt)} onChange={event=>setDueDrafts(current=>({...current,[order._id]:event.target.value}))} onBlur={()=>{if(!closed&&Object.hasOwn(dueDrafts,order._id))void saveDueDate(order)}}/></label>{overdue&&<span className="work-order-overdue">Overdue</span>}</div>
     <div className="work-order-attachments"><div className="work-order-task-heading"><b>Files &amp; completion evidence</b><small>{order.attachments.length}/20</small></div>{order.attachments.length>0&&<ul>{order.attachments.map(file=><li key={file.id}><a href={`/api/work-orders/${order._id}/attachments/${file.id}`}><Download/>{file.name}</a><small>{file.purpose==="completion_evidence"?"Completion evidence":"Supporting file"} · {(file.sizeBytes/1024).toFixed(0)} KB</small><button className="work-order-file-remove" type="button" title={`Remove ${file.name}`} aria-label={`Remove ${file.name}`} disabled={removing===file.id} onClick={()=>void removeFile(order,file)}><Trash2/></button></li>)}</ul>}{order.status!=="cancelled"&&order.attachments.length<20&&<form onSubmit={event=>void uploadFile(event,order)}><select aria-label={`File purpose for ${order.serviceName}`} value={purposes[order._id]||"supporting"} onChange={event=>setPurposes(current=>({...current,[order._id]:event.target.value as "supporting"|"completion_evidence"}))}><option value="supporting">Supporting file</option><option value="completion_evidence">Completion evidence</option></select><input aria-label={`File for ${order.serviceName}`} name="file" type="file" accept=".pdf,image/png,image/jpeg,image/webp" required/><button className="secondary" disabled={uploading===order._id}><FileUp/>{uploading===order._id?"Uploading…":"Attach file"}</button></form>}</div>
     <div className="work-order-tasks"><div className="work-order-task-heading"><b>Tasks</b><small>{order.tasks.filter(task=>task.completedAt).length}/{order.tasks.length} complete</small></div>{order.tasks.length===0?<p className="work-order-no-tasks">Add a short checklist before recording final service completion.</p>:<ul>{order.tasks.map(task=><li key={task._id}><label><input type="checkbox" checked={!!task.completedAt} disabled={closed||saving===order._id} onChange={event=>void update(order,{action:"complete_task",taskId:task._id,completed:event.target.checked})}/><span className={task.completedAt?"done":""}>{task.title}</span></label>{task.completedAt&&<small><Check/>{new Date(task.completedAt).toLocaleDateString()}</small>}</li>)}</ul>}{!closed&&<form onSubmit={event=>void addTask(event,order)}><input aria-label={`New task for ${order.serviceName}`} minLength={2} maxLength={180} value={taskDrafts[order._id]||""} onChange={event=>setTaskDrafts(current=>({...current,[order._id]:event.target.value}))} placeholder="Add a work step"/><button className="secondary" disabled={saving===order._id||(taskDrafts[order._id]||"").trim().length<2}><Plus/>Add task</button></form>}{!allTasksDone&&order.tasks.length>0&&!closed&&<small className="work-order-gate">Complete the checklist before recording the final service quantity in Orders.</small>}</div>
    </article>})}</div>}
  </section>
 </section>
}
