import {randomBytes} from "node:crypto";
import mongoose from "mongoose";
import {NextResponse} from "next/server";
import {isSameOrigin,readJsonLimited} from "@/server/request-security";
import {z} from "zod";
import {requireTenantAccess} from "@/server/tenant-scope";
import {Order} from "@/server/models/Order";
import {CatalogueItem} from "@/server/models/CatalogueItem";
import {CatalogueVariant} from "@/server/models/CatalogueVariant";
import {StockMovement} from "@/server/models/StockMovement";
import {AuditEvent} from "@/server/models/AuditEvent";
import {dispatchFingerprint,fulfilledQuantities,fulfilmentStatus,serviceCompletedQuantities,serviceCompletionFingerprint,validateDispatch,validateServiceCompletion} from "@/server/domain/fulfilment";
import {WorkOrder} from "@/server/models/WorkOrder";
import {ensureServiceWorkOrders} from "@/server/work-orders";

type Context={params:Promise<{id:string}>};
const actionSchema=z.discriminatedUnion("action",[
 z.object({action:z.literal("fulfil")}).strict(),
 z.object({action:z.literal("cancel")}).strict(),
 z.object({action:z.literal("dispatch"),lines:z.array(z.object({lineIndex:z.number().int().safe().min(0).max(49),quantity:z.number().int().safe().min(1).max(100000)}).strict()).min(1).max(50)}).strict().superRefine((value,context)=>{const keys=value.lines.map(line=>line.lineIndex);if(new Set(keys).size!==keys.length)context.addIssue({code:"custom",path:["lines"],message:"A line can only appear once per dispatch."})}),
 z.object({action:z.literal("complete_service"),lines:z.array(z.object({lineIndex:z.number().int().safe().min(0).max(49),quantity:z.number().int().safe().min(1).max(100000)}).strict()).min(1).max(50),note:z.string().trim().max(500).default("")}).strict().superRefine((value,context)=>{const keys=value.lines.map(line=>line.lineIndex);if(new Set(keys).size!==keys.length)context.addIssue({code:"custom",path:["lines"],message:"A service line can only appear once per completion."})}),
]);
function fail(error:unknown){if(error instanceof Error&&error.message==="PERMISSION_DENIED")return NextResponse.json({error:"You do not have permission to update this order."},{status:403});return NextResponse.json({error:"Order service is temporarily unavailable."},{status:503})}
function clientOrder(order:unknown){const value=order as {idempotencyKey?:string;requestFingerprint?:string;fulfilments?:{requestFingerprint?:string;idempotencyKey?:string;actorId?:string}[]};delete value.idempotencyKey;delete value.requestFingerprint;for(const fulfilment of value.fulfilments||[]){delete fulfilment.requestFingerprint;delete fulfilment.idempotencyKey;delete fulfilment.actorId}return value}
function eventLines(order: {fulfilments?:{eventType?:"dispatch"|"service_completion";lines:{lineIndex:number;quantity:number}[]}[]}){return (order.fulfilments||[]).map((event)=>({eventType:event.eventType,lines:event.lines.map((line)=>({lineIndex:line.lineIndex,quantity:line.quantity}))}))}
export const dynamic="force-dynamic";
export async function GET(_request:Request,context:Context){let access;try{access=await requireTenantAccess("orders:read")}catch(error){return fail(error)}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});const{id}=await context.params;if(!mongoose.isValidObjectId(id))return NextResponse.json({error:"Order not found."},{status:404});try{const order=await Order.findOne({_id:id,tenantId:access.scope.tenantId}).populate({path:"customerId",match:{tenantId:access.scope.tenantId},select:"name email phone"}).lean();if(!order)return NextResponse.json({error:"Order not found."},{status:404});return NextResponse.json({order:clientOrder(order)},{headers:{"Cache-Control":"private, no-store"}})}catch(error){return fail(error)}}
export async function POST(request:Request,context:Context){
 if(!isSameOrigin(request))return NextResponse.json({error:"Request origin could not be verified."},{status:403});
 const{id}=await context.params;if(!mongoose.isValidObjectId(id))return NextResponse.json({error:"Order not found."},{status:404});
 const limitedJsonBody=await readJsonLimited(request,24000);if(limitedJsonBody.kind==="too-large")return NextResponse.json({error:"Request is too large."},{status:413});
 const parsed=actionSchema.safeParse(limitedJsonBody.kind==="ok"?limitedJsonBody.value:null);if(!parsed.success)return NextResponse.json({error:"Choose a valid order action and quantity."},{status:400});
 const required=parsed.data.action==="cancel"?"orders:write":"orders:fulfil";let access;try{access=await requireTenantAccess(required)}catch(error){return fail(error)}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});if(access.tenant.commerceMode!=="native")return NextResponse.json({error:"Fulfilment is managed by the connected WooCommerce store."},{status:409});
 const idempotencyKey=parsed.data.action==="fulfil"?`fulfil:${id}`:parsed.data.action==="cancel"?null:request.headers.get("idempotency-key")?.trim();if(parsed.data.action!=="cancel"&&(!idempotencyKey||idempotencyKey.length>120||!/^[A-Za-z0-9._:-]+$/.test(idempotencyKey)||(parsed.data.action!=="fulfil"&&idempotencyKey.startsWith("fulfil:"))))return NextResponse.json({error:"Supply a stable Idempotency-Key for this operation."},{status:400});
 const requested=parsed.data.action==="dispatch"||parsed.data.action==="complete_service"?parsed.data.lines:null,requestFingerprint=parsed.data.action==="dispatch"?dispatchFingerprint(parsed.data.lines):parsed.data.action==="complete_service"?serviceCompletionFingerprint(parsed.data.lines,parsed.data.note):null;
 const session=await mongoose.startSession();let result:unknown,replayed=false;
 try{await session.withTransaction(async()=>{
  const order=await Order.findOne({_id:id,tenantId:access.scope.tenantId}).select("+fulfilments.requestFingerprint").session(session);if(!order)throw new Error("ORDER_NOT_FOUND");
  if(parsed.data.action==="cancel"){
   if(order.status==="cancelled"){result=clientOrder(order.toObject());replayed=true;return}if(order.status!=="open"&&order.status!=="pending_payment")throw new Error("ORDER_CLOSED");
   const completed=fulfilledQuantities(eventLines(order),order.lines.length);
   for(let index=0;index<order.lines.length;index++){const line=order.lines[index],remaining=line.quantity-completed[index];if(!line.tracksStock||remaining<=0)continue;const released=line.variantId?await CatalogueVariant.findOneAndUpdate({_id:line.variantId,itemId:line.itemId,tenantId:access.scope.tenantId,stockReserved:{$gte:remaining}},{$inc:{stockReserved:-remaining,version:1}},{new:true,session}):await CatalogueItem.findOneAndUpdate({_id:line.itemId,tenantId:access.scope.tenantId,stockReserved:{$gte:remaining}},{$inc:{stockReserved:-remaining,version:1}},{new:true,session});if(!released)throw new Error("RESERVATION_MISSING");await StockMovement.create([{tenantId:access.scope.tenantId,itemId:line.itemId,variantId:line.variantId||null,actorId:access.scope.userId,requestId:`cancel:${order._id}:${line.itemId}:${line.variantId||"base"}`,reason:"order_cancelled",quantityDelta:0,stockBefore:released.stockOnHand,stockAfter:released.stockOnHand,note:`Released ${remaining} reserved unit(s) for cancelled ${order.orderNumber}`}],{session})}
   await WorkOrder.updateMany({tenantId:access.scope.tenantId,orderId:order._id,status:{$ne:"completed"}},{$set:{status:"cancelled"}},{session});order.status="cancelled";order.fulfilmentStatus="cancelled";order.cancelReason="staff";if(order.paymentStatus==="pending"||order.paymentStatus==="unpaid")order.paymentStatus="cancelled";await order.save({session});await AuditEvent.create([{tenantId:access.scope.tenantId,actorId:access.scope.userId,action:"order.cancelled",entityType:"order",entityId:String(order._id),requestId:randomBytes(12).toString("hex"),metadata:{orderNumber:order.orderNumber,paymentStatus:order.paymentStatus}}],{session});result=clientOrder(order.toObject());return;
  }
  const prior=order.fulfilments.find((event)=>event.idempotencyKey===idempotencyKey);if(prior){if(prior.requestFingerprint!==(requestFingerprint??dispatchFingerprint(prior.lines)))throw new Error("IDEMPOTENCY_CONFLICT");result=clientOrder(order.toObject());replayed=true;return}
  if(order.status!=="open"&&order.status!=="pending_payment")throw new Error("ORDER_CLOSED");
  if(parsed.data.action==="complete_service"){
   const serviceProgress=validateServiceCompletion(order.lines,eventLines(order),parsed.data.lines);await ensureServiceWorkOrders(order,session,serviceProgress.completed);for(const line of parsed.data.lines){const completedQuantity=serviceProgress.next[line.lineIndex],workOrder=await WorkOrder.findOne({tenantId:access.scope.tenantId,orderId:order._id,orderLineIndex:line.lineIndex}).session(session);if(!workOrder)throw new Error("WORK_ORDER_MISSING");if(access.scope.role!=="owner"&&String(workOrder.assigneeId)!==access.scope.userId)throw new Error("WORK_ORDER_NOT_ASSIGNED");if(completedQuantity>=order.lines[line.lineIndex].quantity&&workOrder.tasks.some(task=>!task.completedAt))throw new Error("WORK_ORDER_TASKS_OPEN");workOrder.completedQuantity=completedQuantity;workOrder.status=completedQuantity>=order.lines[line.lineIndex].quantity?"completed":completedQuantity>0?"in_progress":"open";await workOrder.save({session})}
   order.fulfilments.push({eventType:"service_completion",idempotencyKey:idempotencyKey!,requestFingerprint:requestFingerprint!,actorId:access.scope.userId,occurredAt:new Date(),note:parsed.data.note,lines:parsed.data.lines});
   order.fulfilmentStatus=fulfilmentStatus(order.lines,fulfilledQuantities(eventLines(order),order.lines.length),serviceCompletedQuantities(eventLines(order),order.lines.length));if(order.fulfilmentStatus==="fulfilled")order.status="fulfilled";
   await order.save({session});await AuditEvent.create([{tenantId:access.scope.tenantId,actorId:access.scope.userId,action:order.fulfilmentStatus==="fulfilled"?"order.fulfilled":"order.service_completed",entityType:"order",entityId:String(order._id),requestId:randomBytes(12).toString("hex"),metadata:{orderNumber:order.orderNumber,completedLines:parsed.data.lines.length,fulfilmentStatus:order.fulfilmentStatus,paymentStatus:order.paymentStatus}}],{session});result=clientOrder(order.toObject());return;
  }
  const history=eventLines(order),validated=validateDispatch(order.lines,history,requested??order.lines.flatMap((line,index)=>{if(line.kind!=="physical")return[];const completed=history.reduce((sum,event)=>sum+event.lines.filter((part)=>part.lineIndex===index).reduce((n,part)=>n+part.quantity,0),0);const remaining=line.quantity-completed;return remaining>0?[{lineIndex:index,quantity:remaining}]:[]}));
  const dispatchLines=requested??order.lines.flatMap((line,index)=>{if(line.kind!=="physical")return[];const remaining=line.quantity-validated.fulfilled[index];return remaining>0?[{lineIndex:index,quantity:remaining}]:[]});
  if(!dispatchLines.length)throw new Error("NOTHING_TO_DISPATCH");
  const fingerprint=requestFingerprint??dispatchFingerprint(dispatchLines);if(prior)throw new Error("IDEMPOTENCY_CONFLICT");
  for(const part of dispatchLines){const line=order.lines[part.lineIndex];if(!line.tracksStock)continue;const updated=line.variantId?await CatalogueVariant.findOneAndUpdate({_id:line.variantId,itemId:line.itemId,tenantId:access.scope.tenantId,stockOnHand:{$gte:part.quantity},stockReserved:{$gte:part.quantity}},{$inc:{stockOnHand:-part.quantity,stockReserved:-part.quantity,version:1}},{new:true,session}):await CatalogueItem.findOneAndUpdate({_id:line.itemId,tenantId:access.scope.tenantId,stockOnHand:{$gte:part.quantity},stockReserved:{$gte:part.quantity}},{$inc:{stockOnHand:-part.quantity,stockReserved:-part.quantity,version:1}},{new:true,session});if(!updated)throw new Error("RESERVATION_MISSING");await StockMovement.create([{tenantId:access.scope.tenantId,itemId:line.itemId,variantId:line.variantId||null,actorId:access.scope.userId,requestId:`dispatch:${order._id}:${idempotencyKey}:${part.lineIndex}`,reason:"order_fulfilled",quantityDelta:-part.quantity,stockBefore:updated.stockOnHand+part.quantity,stockAfter:updated.stockOnHand,note:`Dispatched ${part.quantity} unit(s) of ${line.name} for ${order.orderNumber}`}],{session})}
  order.fulfilments.push({eventType:"dispatch",idempotencyKey:idempotencyKey!,requestFingerprint:fingerprint,actorId:access.scope.userId,occurredAt:new Date(),lines:dispatchLines});
  order.fulfilmentStatus=fulfilmentStatus(order.lines,fulfilledQuantities(eventLines(order),order.lines.length),serviceCompletedQuantities(eventLines(order),order.lines.length));if(order.fulfilmentStatus==="fulfilled")order.status="fulfilled";
  await order.save({session});await AuditEvent.create([{tenantId:access.scope.tenantId,actorId:access.scope.userId,action:order.fulfilmentStatus==="fulfilled"?"order.fulfilled":"order.partially_dispatched",entityType:"order",entityId:String(order._id),requestId:randomBytes(12).toString("hex"),metadata:{orderNumber:order.orderNumber,dispatchLines:dispatchLines.length,fulfilmentStatus:order.fulfilmentStatus,paymentStatus:order.paymentStatus}}],{session});result=clientOrder(order.toObject())
  })}catch(error){if(error instanceof Error&&error.message==="ORDER_NOT_FOUND")return NextResponse.json({error:"Order not found."},{status:404});if(error instanceof Error&&["ORDER_CLOSED","NOTHING_TO_DISPATCH"].includes(error.message))return NextResponse.json({error:error.message==="ORDER_CLOSED"?"This order is already closed.":"There are no remaining physical quantities to dispatch."},{status:409});if(error instanceof Error&&["DISPATCH_EMPTY","DISPATCH_INVALID_LINE","DISPATCH_DUPLICATE_LINE","DISPATCH_SERVICE_LINE","DISPATCH_EXCEEDS_REMAINING","SERVICE_COMPLETION_EMPTY","SERVICE_COMPLETION_INVALID_LINE","SERVICE_COMPLETION_PHYSICAL_LINE","SERVICE_COMPLETION_EXCEEDS_REMAINING","INVALID_FULFILMENT_HISTORY"].includes(error.message))return NextResponse.json({error:error.message==="DISPATCH_SERVICE_LINE"?"Service lines are completed separately; only physical items can be dispatched.":error.message==="DISPATCH_EXCEEDS_REMAINING"?"The dispatch quantity exceeds the remaining order quantity.":error.message==="SERVICE_COMPLETION_PHYSICAL_LINE"?"Only service lines can be completed here.":error.message==="SERVICE_COMPLETION_EXCEEDS_REMAINING"?"The completion quantity exceeds the remaining service quantity.":"Review the quantities and try again."},{status:400});if(error instanceof Error&&error.message==="IDEMPOTENCY_CONFLICT")return NextResponse.json({error:"This Idempotency-Key was already used for different quantities or details."},{status:409});if(error instanceof Error&&error.message==="RESERVATION_MISSING")return NextResponse.json({error:"The expected stock reservation is missing. Reconcile inventory before continuing."},{status:409});if(error instanceof Error&&error.message==="WORK_ORDER_NOT_ASSIGNED")return NextResponse.json({error:"Service completion is limited to the assigned operator or a workspace owner."},{status:403});if(error instanceof Error&&error.message==="WORK_ORDER_TASKS_OPEN")return NextResponse.json({error:"Complete every work-order task before recording the final service quantity."},{status:409});if(error instanceof Error&&error.message==="WORK_ORDER_MISSING")return NextResponse.json({error:"The service work order is unavailable. Refresh and try again."},{status:409});return fail(error)}finally{await session.endSession()}
 return NextResponse.json({order:result,replayed},{headers:{"Cache-Control":"private, no-store"}})
}
