import {randomBytes} from "node:crypto";
import mongoose from "mongoose";
import {NextResponse} from "next/server";
import {isSameOrigin,readJsonLimited} from "@/server/request-security";
import {z} from "zod";
import {requireTenantAccess} from "@/server/tenant-scope";
import {Order} from "@/server/models/Order";
import {CatalogueItem} from "@/server/models/CatalogueItem";
import {CatalogueVariant} from "@/server/models/CatalogueVariant";
import {StockMovement} from "@/server/models/StockMovement";
import {AuditEvent} from "@/server/models/AuditEvent";
type Context={params:Promise<{id:string}>};
const actionSchema=z.object({action:z.enum(["fulfil","cancel"])}).strict();
function fail(error:unknown){if(error instanceof Error&&error.message==="PERMISSION_DENIED")return NextResponse.json({error:"You do not have permission to update orders."},{status:403});return NextResponse.json({error:"Order service is temporarily unavailable."},{status:503})}
export const dynamic="force-dynamic";
export async function GET(_request:Request,context:Context){let access;try{access=await requireTenantAccess("orders:read")}catch(error){return fail(error)}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});const{id}=await context.params;if(!mongoose.isValidObjectId(id))return NextResponse.json({error:"Order not found."},{status:404});try{const order=await Order.findOne({_id:id,tenantId:access.scope.tenantId}).populate({path:"customerId",match:{tenantId:access.scope.tenantId},select:"name email phone"}).lean();if(!order)return NextResponse.json({error:"Order not found."},{status:404});return NextResponse.json({order},{headers:{"Cache-Control":"private, no-store"}})}catch(error){return fail(error)}}
export async function POST(request:Request,context:Context){
 if(!isSameOrigin(request))return NextResponse.json({error:"Request origin could not be verified."},{status:403});let access;try{access=await requireTenantAccess("orders:write")}catch(error){return fail(error)}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});if(access.tenant.commerceMode!=="native")return NextResponse.json({error:"Fulfilment is managed by the connected WooCommerce store."},{status:409});const{id}=await context.params;if(!mongoose.isValidObjectId(id))return NextResponse.json({error:"Order not found."},{status:404});const limitedJsonBody=await readJsonLimited(request,24000);if(limitedJsonBody.kind==="too-large")return NextResponse.json({error:"Request is too large."},{status:413});const parsed=actionSchema.safeParse(limitedJsonBody.kind==="ok"?limitedJsonBody.value:null);if(!parsed.success)return NextResponse.json({error:"Choose a valid order action."},{status:400});const session=await mongoose.startSession();let result:unknown;try{await session.withTransaction(async()=>{const order=await Order.findOne({_id:id,tenantId:access.scope.tenantId}).session(session);if(!order)throw new Error("ORDER_NOT_FOUND");if((parsed.data.action==="fulfil"&&order.status==="fulfilled")||(parsed.data.action==="cancel"&&order.status==="cancelled")){result=order.toObject();return}if(order.status!=="open"&&order.status!=="pending_payment")throw new Error("ORDER_CLOSED");if(parsed.data.action==="fulfil"){
  for(const line of order.lines){if(!line.tracksStock)continue;const updated=line.variantId?await CatalogueVariant.findOneAndUpdate({_id:line.variantId,itemId:line.itemId,tenantId:access.scope.tenantId,stockOnHand:{$gte:line.quantity},stockReserved:{$gte:line.quantity}},{$inc:{stockOnHand:-line.quantity,stockReserved:-line.quantity,version:1}},{new:true,session}):await CatalogueItem.findOneAndUpdate({_id:line.itemId,tenantId:access.scope.tenantId,stockOnHand:{$gte:line.quantity},stockReserved:{$gte:line.quantity}},{$inc:{stockOnHand:-line.quantity,stockReserved:-line.quantity,version:1}},{new:true,session});if(!updated)throw new Error("RESERVATION_MISSING");const requestId=`fulfil:${order._id}:${line.itemId}:${line.variantId||"base"}`;await StockMovement.create([{tenantId:access.scope.tenantId,itemId:line.itemId,variantId:line.variantId||null,actorId:access.scope.userId,requestId,reason:"order_fulfilled",quantityDelta:-line.quantity,stockBefore:updated.stockOnHand+line.quantity,stockAfter:updated.stockOnHand,note:`Fulfilled ${order.orderNumber}`}],{session})}
  order.status="fulfilled";order.fulfilmentStatus="fulfilled";
 }else{
  for(const line of order.lines){if(!line.tracksStock)continue;const released=line.variantId?await CatalogueVariant.findOneAndUpdate({_id:line.variantId,itemId:line.itemId,tenantId:access.scope.tenantId,stockReserved:{$gte:line.quantity}},{$inc:{stockReserved:-line.quantity,version:1}},{new:true,session}):await CatalogueItem.findOneAndUpdate({_id:line.itemId,tenantId:access.scope.tenantId,stockReserved:{$gte:line.quantity}},{$inc:{stockReserved:-line.quantity,version:1}},{new:true,session});if(!released)throw new Error("RESERVATION_MISSING");await StockMovement.create([{tenantId:access.scope.tenantId,itemId:line.itemId,variantId:line.variantId||null,actorId:access.scope.userId,requestId:`cancel:${order._id}:${line.itemId}:${line.variantId||"base"}`,reason:"order_cancelled",quantityDelta:0,stockBefore:released.stockOnHand,stockAfter:released.stockOnHand,note:`Released ${line.quantity} reserved unit(s) for cancelled ${order.orderNumber}`}],{session})}
  order.status="cancelled";order.fulfilmentStatus="cancelled";order.cancelReason="staff";if(order.paymentStatus==="pending"||order.paymentStatus==="unpaid")order.paymentStatus="cancelled";
 }
 await order.save({session});await AuditEvent.create([{tenantId:access.scope.tenantId,actorId:access.scope.userId,action:parsed.data.action==="fulfil"?"order.fulfilled":"order.cancelled",entityType:"order",entityId:String(order._id),requestId:randomBytes(12).toString("hex"),metadata:{orderNumber:order.orderNumber,paymentStatus:order.paymentStatus}}],{session});result=order.toObject()})}catch(error){if(error instanceof Error&&error.message==="ORDER_NOT_FOUND")return NextResponse.json({error:"Order not found."},{status:404});if(error instanceof Error&&error.message==="ORDER_CLOSED")return NextResponse.json({error:"This order is already closed."},{status:409});if(error instanceof Error&&error.message==="RESERVATION_MISSING")return NextResponse.json({error:"The expected stock reservation is missing. Reconcile inventory before continuing."},{status:409});return fail(error)}finally{await session.endSession()}return NextResponse.json({order:result},{headers:{"Cache-Control":"private, no-store"}})}



