"use client";
import {useCallback,useEffect,useState} from "react";
import {Check,LockKeyhole,MessageCircle,Send} from "lucide-react";
import styles from "./PublicConversation.module.css";
type Message={id:string;direction:"customer"|"staff";body:string;createdAt:string;deliveryStatus:string};
type Data={conversation:{subject:string;status:string;customerName:string;businessName:string};messages:Message[]};
export default function PublicConversation({token}:{token:string}){const[data,setData]=useState<Data|null>(null),[busy,setBusy]=useState(true),[text,setText]=useState(""),[error,setError]=useState(""),[sending,setSending]=useState(false);
 const load=useCallback(async()=>{try{const response=await fetch(`/api/public/conversations/${token}`,{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error(body.error||"This private conversation is unavailable.");setData(body);setError("")}catch(e){setError(e instanceof Error?e.message:"This private conversation is unavailable.")}finally{setBusy(false)}},[token]);
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),15000);return()=>clearInterval(timer)},[load]);
 async function send(event:React.FormEvent){event.preventDefault();if(!text.trim())return;setSending(true);setError("");try{const response=await fetch(`/api/public/conversations/${token}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({body:text,requestKey:crypto.randomUUID()})}),body=await response.json();if(!response.ok)throw new Error(body.error||"Message could not be sent.");setText("");await load()}catch(e){setError(e instanceof Error?e.message:"Message could not be sent.")}finally{setSending(false)}}
 return <main className={styles.shell}><header className={styles.brand}><span className={styles.mark}><i/><i/><i/><i/></span><b>commerce<span>desk</span></b><small>PRIVATE CONVERSATION</small></header><section className={styles.card}><div className={styles.heading}><div className={styles.icon}><MessageCircle/></div><div><small>{data?.conversation.businessName||"COMMERCE DESK"}</small><h1>{data?.conversation.subject||"A direct line to the team."}</h1><p>{data?`Conversation with ${data.conversation.businessName}.`:"Messages stay private to this conversation."}</p></div></div>{error&&!data&&<div className={styles.error}>{error}</div>}{busy&&!data?<div className={styles.loading}>Loading conversation…</div>:data?<><div className={styles.thread} aria-live="polite">{data.messages.map(message=><article className={`${styles.message} ${message.direction==="customer"?styles.customer:""}`} key={message.id}><small>{message.direction==="customer"?"YOU":data.conversation.businessName.toUpperCase()} · {new Date(message.createdAt).toLocaleString()}</small><p>{message.body}</p></article>)}{data.messages.length===0&&<div className={styles.empty}><MessageCircle/><b>Start the conversation</b><span>Send a message and the team will reply here.</span></div>}</div>{data.conversation.status==="closed"?<div className={styles.closed}><Check/>This conversation is closed. Contact the business to continue.</div>:<form className={styles.form} onSubmit={send}><label className={styles.sr} htmlFor="conversation-message">Your message</label><textarea id="conversation-message" required minLength={2} maxLength={4000} value={text} onChange={e=>setText(e.target.value)} placeholder="Write a message to the team…"/><button disabled={sending||!text.trim()}><Send/>{sending?"Sending…":"Send message"}</button></form>}</>:null}<footer className={styles.privacy}><LockKeyhole/>Only you and the business can view these messages.</footer></section><footer className={styles.bottom}>COMMERCE DESK <span>Private customer channel</span></footer></main>}
