import mongoose,{Schema,type InferSchemaType,type Model} from "mongoose";
const variantOptionSnapshotSchema=new Schema({name:{type:String,required:true,immutable:true,maxlength:40},value:{type:String,required:true,immutable:true,maxlength:80}},{_id:false,versionKey:false});
const lineSchema=new Schema({itemId:{type:Schema.Types.ObjectId,ref:"CatalogueItem",required:true,immutable:true},variantId:{type:Schema.Types.ObjectId,ref:"CatalogueVariant",default:null,immutable:true},variantName:{type:String,default:null,immutable:true,maxlength:100},variantOptions:{type:[variantOptionSnapshotSchema],default:[],immutable:true},kind:{type:String,enum:["physical","service"],required:true,immutable:true},name:{type:String,required:true,immutable:true,maxlength:160},sku:{type:String,default:null,immutable:true,maxlength:80},quantity:{type:Number,required:true,immutable:true,min:1,max:100000},unitPriceMinor:{type:Number,required:true,immutable:true,min:0,max:Number.MAX_SAFE_INTEGER},discountPercentBps:{type:Number,required:true,immutable:true,min:0,max:9999,default:0},discountAmountMinor:{type:Number,required:true,immutable:true,min:0,max:Number.MAX_SAFE_INTEGER,default:0},taxRateBps:{type:Number,required:true,immutable:true,min:0,max:100000},taxMode:{type:String,enum:["inclusive","exclusive"],required:true,immutable:true},netMinor:{type:Number,required:true,immutable:true,min:0},taxMinor:{type:Number,required:true,immutable:true,min:0},grossMinor:{type:Number,required:true,immutable:true,min:0},tracksStock:{type:Boolean,required:true,immutable:true,default:false}},{_id:false,versionKey:false});
const addressSchema=new Schema({recipient:{type:String,required:true,immutable:true,trim:true,maxlength:160},line1:{type:String,required:true,immutable:true,trim:true,maxlength:200},line2:{type:String,default:"",immutable:true,trim:true,maxlength:200},city:{type:String,required:true,immutable:true,trim:true,maxlength:120},region:{type:String,default:"",immutable:true,trim:true,maxlength:120},postalCode:{type:String,default:"",immutable:true,trim:true,maxlength:32},countryCode:{type:String,required:true,immutable:true,uppercase:true,match:/^[A-Z]{2}$/}},{_id:false,versionKey:false});
const fulfilmentLineSchema=new Schema({lineIndex:{type:Number,required:true,immutable:true,min:0,max:49},quantity:{type:Number,required:true,immutable:true,min:1,max:100000}},{_id:false,versionKey:false});
const fulfilmentSchema=new Schema({eventType:{type:String,enum:["dispatch","service_completion"],required:true,default:"dispatch",immutable:true},idempotencyKey:{type:String,required:true,immutable:true,trim:true,maxlength:120},requestFingerprint:{type:String,required:true,immutable:true,select:false,maxlength:64},actorId:{type:Schema.Types.ObjectId,ref:"User",required:true,immutable:true},occurredAt:{type:Date,required:true,immutable:true,default:Date.now},note:{type:String,trim:true,default:"",immutable:true,maxlength:500},lines:{type:[fulfilmentLineSchema],required:true,immutable:true,validate:{validator:(value:unknown[])=>value.length>0&&value.length<=50,message:"Fulfilment event needs at least one line."}}},{_id:true,versionKey:false});
const schema=new Schema({
 tenantId:{type:Schema.Types.ObjectId,ref:"Tenant",required:true,immutable:true},orderNumber:{type:String,required:true,immutable:true,trim:true,maxlength:32},
 customerId:{type:Schema.Types.ObjectId,ref:"Customer",default:null,immutable:true},customerSnapshot:{name:{type:String,required:true,immutable:true},email:{type:String,default:null,immutable:true},phone:{type:String,default:null,immutable:true}},
 lines:{type:[lineSchema],required:true,immutable:true,validate:{validator:(value:unknown[])=>value.length>0&&value.length<=50,message:"Order needs 1–50 item lines."}},currency:{type:String,required:true,immutable:true,uppercase:true,match:/^[A-Z]{3}$/},
 subtotalMinor:{type:Number,required:true,immutable:true,min:0,max:Number.MAX_SAFE_INTEGER},taxMinor:{type:Number,required:true,immutable:true,min:0,max:Number.MAX_SAFE_INTEGER},shippingFeeMinor:{type:Number,required:true,immutable:true,min:0,max:Number.MAX_SAFE_INTEGER,default:0},totalMinor:{type:Number,required:true,immutable:true,min:0,max:Number.MAX_SAFE_INTEGER},
 source:{type:String,enum:["workspace","storefront","quote"],required:true,immutable:true,default:"workspace"},fulfilmentMethod:{type:String,enum:["delivery","pickup"],default:null,immutable:true},shippingAddress:{type:addressSchema,default:null,immutable:true},
 paymentMethod:{type:String,enum:["bank_transfer","cash_on_pickup"],default:null,immutable:true},paymentInstructionsSnapshot:{type:String,default:"",immutable:true,maxlength:1000},storefrontTermsSnapshot:{type:String,default:"",immutable:true,maxlength:3000},storefrontPrivacySnapshot:{type:String,default:"",immutable:true,maxlength:3000},policyVersion:{type:String,default:null,immutable:true,maxlength:64},reservationExpiresAt:{type:Date,default:null},
 receiptTokenHash:{type:String,default:null,select:false,immutable:true},receiptTokenEncrypted:{type:String,default:null,select:false,immutable:true},receiptTokenExpiresAt:{type:Date,default:null,immutable:true},
 cancelReason:{type:String,enum:["staff","hold_expired"],default:null},
 status:{type:String,enum:["open","pending_payment","fulfilled","cancelled"],required:true,default:"open"},paymentStatus:{type:String,enum:["unpaid","pending","partially_paid","paid","partially_refunded","refunded","cancelled"],required:true,default:"unpaid"},fulfilmentStatus:{type:String,enum:["unfulfilled","partially_fulfilled","fulfilled","cancelled"],required:true,default:"unfulfilled"},fulfilments:{type:[fulfilmentSchema],default:[]},
 depositDueMinor:{type:Number,default:0,immutable:true,min:0,max:Number.MAX_SAFE_INTEGER},stripeRefundsPendingMinor:{type:Number,default:0,select:false,min:0,max:Number.MAX_SAFE_INTEGER},
 sourceQuoteId:{type:Schema.Types.ObjectId,ref:"Quote",default:null,immutable:true},sourceQuoteRevision:{type:Number,default:null,immutable:true},idempotencyKey:{type:String,required:true,immutable:true,trim:true,maxlength:120},requestFingerprint:{type:String,required:true,immutable:true,select:false,maxlength:64},createdBy:{type:Schema.Types.ObjectId,ref:"User",default:null,immutable:true}
},{timestamps:true,versionKey:"version"});
schema.index({tenantId:1,orderNumber:1},{unique:true});schema.index({tenantId:1,idempotencyKey:1},{unique:true});schema.index({tenantId:1,sourceQuoteId:1,sourceQuoteRevision:1},{unique:true,partialFilterExpression:{sourceQuoteId:{$type:"objectId"}}});schema.index({tenantId:1,status:1,createdAt:-1});schema.index({tenantId:1,customerId:1,createdAt:-1});schema.index({receiptTokenHash:1},{unique:true,partialFilterExpression:{receiptTokenHash:{$type:"string"}}});schema.index({status:1,reservationExpiresAt:1});
export type OrderRecord=InferSchemaType<typeof schema>;
export const Order:Model<OrderRecord>=mongoose.models.Order??mongoose.model<OrderRecord>("Order",schema);


