import {randomBytes} from "node:crypto";
import mongoose from "mongoose";
import {NextResponse} from "next/server";
import {z} from "zod";
import {isSameOrigin,readJsonLimited} from "@/server/request-security";
import {requireTenantAccess} from "@/server/tenant-scope";
import {Customer} from "@/server/models/Customer";
import {Order} from "@/server/models/Order";
import {SupportCase} from "@/server/models/SupportCase";
import {SupportEvent} from "@/server/models/SupportEvent";
import {AuditEvent} from "@/server/models/AuditEvent";
export const dynamic="force-dynamic";
const createSchema=z.object({customerId:z.string().regex(/^[a-f\d]{24}$/i),orderId:z.string().regex(/^[a-f\d]{24}$/i).nullable().optional(),kind:z.enum(["question","delivery","return","damaged","other"]),subject:z.string().trim().min(3).max(180),message:z.string().trim().min(1).max(2000)}).strict();
function fail(error:unknown){if(error instanceof Error&&error.message==="PERMISSION_DENIED")return NextResponse.json({error:"You do not have permission to manage support cases."},{status:403});return NextResponse.json({error:"Support service is temporarily unavailable."},{status:503})}
export async function GET(request:Request){let access;try{access=await requireTenantAccess("support:write")}catch(error){return fail(error)}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});const url=new URL(request.url),status=url.searchParams.get("status"),filter:Record<string,unknown>={tenantId:access.scope.tenantId};if(status){if(!["open","assigned","awaiting_customer","awaiting_internal","resolved","closed"].includes(status))return NextResponse.json({error:"Choose a valid support status."},{status:400});filter.status=status}try{const cases=await SupportCase.find(filter).sort({updatedAt:-1,_id:-1}).limit(200).populate({path:"customerId",match:{tenantId:access.scope.tenantId},select:"name email phone"}).populate({path:"assignedTo",select:"name"}).populate({path:"orderId",match:{tenantId:access.scope.tenantId},select:"orderNumber status totalMinor currency"}).lean();return NextResponse.json({cases},{headers:{"Cache-Control":"private, no-store"}})}catch(error){return fail(error)}}
export async function POST(request:Request){if(!isSameOrigin(request))return NextResponse.json({error:"Request origin could not be verified."},{status:403});const body=await readJsonLimited(request,12000);if(body.kind==="too-large")return NextResponse.json({error:"Request is too large."},{status:413});const parsed=createSchema.safeParse(body.kind==="ok"?body.value:null);if(!parsed.success)return NextResponse.json({error:"Enter a customer, subject and case message."},{status:400});let access;try{access=await requireTenantAccess("support:write")}catch(error){return fail(error)}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});try{const customer=await Customer.findOne({_id:parsed.data.customerId,tenantId:access.scope.tenantId}).select("_id").lean();if(!customer)return NextResponse.json({error:"Customer not found in this workspace."},{status:404});if(parsed.data.orderId){const order=await Order.findOne({_id:parsed.data.orderId,tenantId:access.scope.tenantId,customerId:customer._id}).select("_id").lean();if(!order)return NextResponse.json({error:"Choose an order belonging to this customer."},{status:400})}const session=await mongoose.startSession();let created:unknown;try{await session.withTransaction(async()=>{const[record]=await SupportCase.create([{tenantId:access!.scope.tenantId,customerId:customer._id,orderId:parsed.data.orderId||null,kind:parsed.data.kind,subject:parsed.data.subject,createdBy:access!.scope.userId,updatedBy:access!.scope.userId}],{session});await SupportEvent.create([{tenantId:access!.scope.tenantId,caseId:record._id,actorId:access!.scope.userId,action:"created",body:parsed.data.message}],{session});await AuditEvent.create([{tenantId:access!.scope.tenantId,actorId:access!.scope.userId,action:"support.case_created",entityType:"support_case",entityId:String(record._id),requestId:randomBytes(12).toString("hex"),metadata:{kind:record.kind,orderId:record.orderId?String(record.orderId):null}}],{session});created=record.toObject()})}finally{await session.endSession()}return NextResponse.json({case:created},{status:201,headers:{"Cache-Control":"private, no-store"}})}catch(error){return fail(error)}}
