import {createHash,randomBytes} from "node:crypto";
import mongoose from "mongoose";
import {NextResponse} from "next/server";
import {isSameOrigin,readJsonLimited} from "@/server/request-security";
import {z} from "zod";
import {requireTenantAccess} from "@/server/tenant-scope";
import {Order} from "@/server/models/Order";
import {OrderCounter} from "@/server/models/OrderCounter";
import {CatalogueItem} from "@/server/models/CatalogueItem";
import {CatalogueVariant} from "@/server/models/CatalogueVariant";
import {Customer} from "@/server/models/Customer";
import {AuditEvent} from "@/server/models/AuditEvent";
import {calculateLineAmount} from "@/server/domain/money";
import {ensureServiceWorkOrders} from "@/server/work-orders";
export const dynamic="force-dynamic";
const createSchema=z.object({customerId:z.string().regex(/^[a-f\d]{24}$/i),lines:z.array(z.object({itemId:z.string().regex(/^[a-f\d]{24}$/i),variantId:z.string().regex(/^[a-f\d]{24}$/i).optional(),quantity:z.number().int().safe().min(1).max(100000)}).strict()).min(1).max(50)}).strict().superRefine((value,context)=>{const keys=value.lines.map(line=>`${line.itemId}:${line.variantId||"base"}`);if(new Set(keys).size!==keys.length)context.addIssue({code:"custom",path:["lines"],message:"Each product and variant may appear once; combine its quantity."})});
function fail(error:unknown){if(error instanceof Error&&error.message==="PERMISSION_DENIED")return NextResponse.json({error:"You do not have permission to view or create orders."},{status:403});return NextResponse.json({error:"Order service is temporarily unavailable."},{status:503})}
function clientOrder(order:unknown){const value=order as {idempotencyKey?:string;requestFingerprint?:string;fulfilments?:{requestFingerprint?:string;idempotencyKey?:string;actorId?:string}[]};delete value.idempotencyKey;delete value.requestFingerprint;for(const fulfilment of value.fulfilments||[]){delete fulfilment.requestFingerprint;delete fulfilment.idempotencyKey;delete fulfilment.actorId}return value}
function safeSum(values:number[]){const total=values.reduce((sum,value)=>sum+BigInt(value),0n);const number=Number(total);if(!Number.isSafeInteger(number))throw new RangeError("Order total exceeds the safe integer range.");return number}
function requestFingerprint(data:{customerId:string;lines:{itemId:string;quantity:number}[]}){return createHash("sha256").update(JSON.stringify(data)).digest("hex")}
export async function GET(request:Request){
 let access;try{access=await requireTenantAccess("orders:read")}catch(error){return fail(error)}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});
 const url=new URL(request.url),q=(url.searchParams.get("q")||"").trim().slice(0,120),status=url.searchParams.get("status"),page=Math.max(1,Number.parseInt(url.searchParams.get("page")||"1",10)||1),limit=Math.max(1,Math.min(100,Number.parseInt(url.searchParams.get("limit")||"25",10)||25));
 const filter:Record<string,unknown>={tenantId:access.scope.tenantId};if(q){const rx={$regex:q.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),$options:"i"};filter.$or=[{orderNumber:rx},{"customerSnapshot.name":rx}]};if(["open","pending_payment","fulfilled","cancelled"].includes(status||""))filter.status=status;
 try{const [orders,total]=await Promise.all([Order.find(filter).sort({createdAt:-1,_id:-1}).skip((page-1)*limit).limit(limit).populate({path:"customerId",match:{tenantId:access.scope.tenantId},select:"name email phone"}).lean(),Order.countDocuments(filter)]);return NextResponse.json({orders:orders.map(clientOrder),currency:access.tenant.baseCurrency,page,limit,total,pageCount:Math.ceil(total/limit)},{headers:{"Cache-Control":"private, no-store"}})}catch(error){return fail(error)}
}
export async function POST(request:Request){
 if(!isSameOrigin(request))return NextResponse.json({error:"Request origin could not be verified."},{status:403});
 let access;try{access=await requireTenantAccess("orders:write")}catch(error){return fail(error)}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});if(access.tenant.commerceMode!=="native")return NextResponse.json({error:"This store is connected to WooCommerce. Orders must be created and fulfilled in the connected store."},{status:409});
 const key=request.headers.get("idempotency-key")?.trim();if(!key||key.length>120||!/^[A-Za-z0-9._:-]+$/.test(key))return NextResponse.json({error:"Supply a stable Idempotency-Key for this order."},{status:400});if(Number(request.headers.get("content-length")||0)>20000)return NextResponse.json({error:"Request is too large."},{status:413});
 const limitedJsonBody=await readJsonLimited(request,24000);if(limitedJsonBody.kind==="too-large")return NextResponse.json({error:"Request is too large."},{status:413});const parsed=createSchema.safeParse(limitedJsonBody.kind==="ok"?limitedJsonBody.value:null);if(!parsed.success)return NextResponse.json({error:"Review the customer and order items.",issues:parsed.error.issues.map((issue)=>({field:issue.path.join("."),message:issue.message}))},{status:400});const fingerprint=requestFingerprint(parsed.data);
 const prior=await Order.findOne({tenantId:access.scope.tenantId,idempotencyKey:key}).select("+requestFingerprint").lean().catch(()=>null);if(prior){if(prior.requestFingerprint!==fingerprint)return NextResponse.json({error:"This Idempotency-Key was already used for a different order."},{status:409});return NextResponse.json({order:clientOrder(prior),replayed:true},{headers:{"Cache-Control":"private, no-store"}})}
 const session=await mongoose.startSession();let result:unknown;try{await session.withTransaction(async()=>{
  const customer=await Customer.findOne({_id:parsed.data.customerId,tenantId:access.scope.tenantId,status:{$ne:"archived"}}).session(session).lean();if(!customer)throw new Error("CUSTOMER_NOT_FOUND");
  const ids=[...new Set(parsed.data.lines.map((line)=>line.itemId))],catalogue=await CatalogueItem.find({_id:{$in:ids},tenantId:access.scope.tenantId,status:"active",kind:{$in:["physical","service"]}}).session(session).lean();if(catalogue.length!==ids.length)throw new Error("ITEM_UNAVAILABLE");
  const physicalIds=catalogue.filter(item=>item.kind==="physical").map(item=>item._id),variantRows=physicalIds.length?await CatalogueVariant.find({tenantId:access.scope.tenantId,itemId:{$in:physicalIds}}).session(session).lean():[],variantsByItem=new Map<string,typeof variantRows>();for(const variant of variantRows){const key=String(variant.itemId),group=variantsByItem.get(key)||[];group.push(variant);variantsByItem.set(key,group)}const byId=new Map(catalogue.map((item)=>[String(item._id),item]));const orderLines=[] as Record<string,unknown>[];
  for(const line of parsed.data.lines){const item=byId.get(line.itemId);if(!item)throw new Error("ITEM_UNAVAILABLE");const options=variantsByItem.get(line.itemId)||[];let variant=undefined;if(item.kind==="service"&&line.variantId)throw new Error("ITEM_UNAVAILABLE");if(options.length){if(!line.variantId)throw new Error("VARIANT_REQUIRED");variant=options.find(candidate=>String(candidate._id)===line.variantId&&candidate.active);if(!variant)throw new Error("ITEM_UNAVAILABLE")}else if(line.variantId)throw new Error("ITEM_UNAVAILABLE");if(item.trackInventory){const reserved=variant?await CatalogueVariant.updateOne({_id:variant._id,itemId:item._id,tenantId:access.scope.tenantId,active:true,$expr:{$gte:[{$subtract:["$stockOnHand","$stockReserved"]},line.quantity]}},{$inc:{stockReserved:line.quantity,version:1}},{session}):await CatalogueItem.updateOne({_id:item._id,tenantId:access.scope.tenantId,status:"active",kind:"physical",trackInventory:true,$expr:{$gte:[{$subtract:["$stockOnHand","$stockReserved"]},line.quantity]}},{$inc:{stockReserved:line.quantity,version:1}},{session});if(!reserved.modifiedCount)throw new Error("STOCK_UNAVAILABLE")}
   const unitPriceMinor=variant?.unitPriceMinor??item.unitPriceMinor,amount=calculateLineAmount({unitPriceMinor,quantity:line.quantity,taxRateBps:item.taxRateBps,taxMode:item.taxMode as "inclusive"|"exclusive"},access.tenant.baseCurrency);orderLines.push({itemId:item._id,variantId:variant?._id||null,variantName:variant?.name||null,variantOptions:variant?.options||[],kind:item.kind,name:item.name,sku:variant?.sku||item.sku,quantity:line.quantity,unitPriceMinor,taxRateBps:item.taxRateBps,taxMode:item.taxMode,netMinor:amount.netMinor,taxMinor:amount.taxMinor,grossMinor:amount.grossMinor,tracksStock:item.trackInventory});
  }
  const counter=await OrderCounter.findOneAndUpdate({tenantId:access.scope.tenantId},{$inc:{nextNumber:1},$setOnInsert:{tenantId:access.scope.tenantId}},{new:true,upsert:true,session});const orderNumber=`ORD-${new Date().getUTCFullYear().toString().slice(-2)}-${String(counter.nextNumber).padStart(6,"0")}`;const subtotalMinor=safeSum(orderLines.map((line)=>line.netMinor as number)),taxMinor=safeSum(orderLines.map((line)=>line.taxMinor as number)),totalMinor=safeSum(orderLines.map((line)=>line.grossMinor as number));
  const[order]=await Order.create([{tenantId:access.scope.tenantId,orderNumber,customerId:customer._id,customerSnapshot:{name:customer.name,email:customer.email,phone:customer.phone},lines:orderLines,currency:access.tenant.baseCurrency,subtotalMinor,taxMinor,totalMinor,idempotencyKey:key,requestFingerprint:fingerprint,createdBy:access.scope.userId,status:"open",paymentStatus:"unpaid",fulfilmentStatus:"unfulfilled"}],{session});await ensureServiceWorkOrders(order,session);
  await AuditEvent.create([{tenantId:access.scope.tenantId,actorId:access.scope.userId,action:"order.created",entityType:"order",entityId:String(order._id),requestId:key,metadata:{orderNumber:order.orderNumber,totalMinor:order.totalMinor,currency:order.currency,lineCount:order.lines.length}}],{session});result=order.toObject();
 })}catch(error){if(error instanceof Error&&error.message==="CUSTOMER_NOT_FOUND")return NextResponse.json({error:"Choose an active customer in this workspace."},{status:404});if(error instanceof Error&&error.message==="ITEM_UNAVAILABLE")return NextResponse.json({error:"One or more products or variants are unavailable or belong to another workspace."},{status:409});if(error instanceof Error&&error.message==="VARIANT_REQUIRED")return NextResponse.json({error:"Choose an option for each product with variants."},{status:400});if(error instanceof Error&&error.message==="STOCK_UNAVAILABLE")return NextResponse.json({error:"There is not enough unreserved stock for this order."},{status:409});if((error as {code?:number})?.code===11000){const replay=await Order.findOne({tenantId:access.scope.tenantId,idempotencyKey:key}).select("+requestFingerprint").lean();if(replay&&replay.requestFingerprint===fingerprint)return NextResponse.json({order:clientOrder(replay),replayed:true},{headers:{"Cache-Control":"private, no-store"}});return NextResponse.json({error:"The order number or idempotency key is already in use."},{status:409})}return fail(error)}finally{await session.endSession()}
 return NextResponse.json({order:clientOrder(result),replayed:false},{status:201,headers:{"Cache-Control":"private, no-store"}})
}



