import {randomBytes} from "node:crypto";
import mongoose from "mongoose";
import {NextResponse} from "next/server";
import {z} from "zod";
import {isSameOrigin,readJsonLimited} from "@/server/request-security";
import {requireTenantAccess} from "@/server/tenant-scope";
import {Appointment} from "@/server/models/Appointment";
import {AppointmentEvent} from "@/server/models/AppointmentEvent";
import {AuditEvent} from "@/server/models/AuditEvent";
import {Tenant} from "@/server/models/Tenant";
import {ServiceResource} from "@/server/models/ServiceResource";
import {hasIntervalCapacity,isValidLocalDate,localDateInZone,slotsForLocalDate} from "@/server/domain/appointments";

const actionSchema=z.discriminatedUnion("action",[
 z.object({action:z.literal("confirm")}).strict(),z.object({action:z.literal("cancel"),note:z.string().trim().max(500).default("")}).strict(),z.object({action:z.literal("complete")}).strict(),z.object({action:z.literal("no_show")}).strict(),
 z.object({action:z.literal("reschedule"),resourceId:z.string().regex(/^[a-f\d]{24}$/i),startsAt:z.string().datetime({offset:true})}).strict()
]);
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){
 if(!isSameOrigin(request))return NextResponse.json({error:"Request origin could not be verified."},{status:403});let access;try{access=await requireTenantAccess("appointments:write")}catch(error){if(error instanceof Error&&error.message==="PERMISSION_DENIED")return NextResponse.json({error:"You do not have permission to update appointments."},{status:403});return NextResponse.json({error:"Appointments are temporarily unavailable."},{status:503})}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});const{id}=await params;if(!/^[a-f\d]{24}$/i.test(id))return NextResponse.json({error:"Appointment not found."},{status:404});if(Number(request.headers.get("content-length")||0)>8000)return NextResponse.json({error:"Request is too large."},{status:413});const body=await readJsonLimited(request,10000);if(body.kind==="too-large")return NextResponse.json({error:"Request is too large."},{status:413});const parsed=actionSchema.safeParse(body.kind==="ok"?body.value:null);if(!parsed.success)return NextResponse.json({error:"Choose a valid appointment action."},{status:400});
 const tenantId=access.scope.tenantId,session=await mongoose.startSession();let result:unknown;try{await session.withTransaction(async()=>{const appointment=await Appointment.findOne({_id:id,tenantId}).session(session);if(!appointment)throw new Error("NOT_FOUND");const before=appointment.status,now=new Date();let detail:Record<string,unknown>={};
  if(parsed.data.action==="confirm"){if(appointment.status!=="held"||!appointment.holdExpiresAt||appointment.holdExpiresAt<=now)throw new Error("INVALID_STATE");appointment.status="confirmed";appointment.set("holdExpiresAt",null);detail={from:before,to:"confirmed"}}
  else if(parsed.data.action==="cancel"){if(!["held","confirmed"].includes(appointment.status))throw new Error("INVALID_STATE");appointment.status="cancelled";appointment.set("holdExpiresAt",null);appointment.set("manageTokenHash",null);appointment.set("manageTokenExpiresAt",null);appointment.cancellationNote=parsed.data.note;detail={from:before,to:"cancelled",note:parsed.data.note}}
  else if(parsed.data.action==="complete"||parsed.data.action==="no_show"){if(appointment.status!=="confirmed")throw new Error("INVALID_STATE");appointment.status=parsed.data.action==="complete"?"completed":"no_show";appointment.set("manageTokenHash",null);appointment.set("manageTokenExpiresAt",null);detail={from:before,to:appointment.status}}
  else {if(!["held","confirmed"].includes(appointment.status))throw new Error("INVALID_STATE");const targetStart=new Date(parsed.data.startsAt),targetDay=localDateInZone(targetStart,appointment.businessTimezone);if(!isValidLocalDate(targetDay))throw new Error("INVALID_SLOT");const weekday=new Date(`${targetDay}T12:00:00.000Z`).getUTCDay(),tenant=await Tenant.findById(tenantId).select("appointmentHours appointmentClosures").session(session).lean(),hours=tenant?.appointmentHours.find(item=>item.weekday===weekday),resource=await ServiceResource.findOne({_id:parsed.data.resourceId,tenantId,active:true}).session(session).lean();if(!hours||!resource)throw new Error("INVALID_SLOT");const slot=slotsForLocalDate({date:targetDay,timeZone:appointment.businessTimezone,openMinute:hours.openMinute,closeMinute:hours.closeMinute,durationMinutes:appointment.serviceDurationMinutes,bufferBeforeMinutes:resource.bufferBeforeMinutes,bufferAfterMinutes:resource.bufferAfterMinutes}).find(item=>item.startsAt.getTime()===targetStart.getTime());if(!slot||tenant!.appointmentClosures.some(c=>slot.bufferedStartsAt<c.endsAt&&slot.bufferedEndsAt>c.startsAt))throw new Error("INVALID_SLOT");for(const resourceKey of [...new Set([String(appointment.resourceId),String(resource._id)])].sort())await ServiceResource.updateOne({_id:resourceKey,tenantId},{$inc:{version:1}},{session});const conflicts=await Appointment.find({_id:{$ne:appointment._id},tenantId,resourceId:resource._id,bufferedStartsAt:{$lt:slot.bufferedEndsAt},bufferedEndsAt:{$gt:slot.bufferedStartsAt},$or:[{status:"confirmed"},{status:"held",holdExpiresAt:{$gt:now}}]}).select("bufferedStartsAt bufferedEndsAt").session(session).lean();if(!hasIntervalCapacity({startAt:slot.bufferedStartsAt,endAt:slot.bufferedEndsAt},conflicts.map(a=>({startAt:a.bufferedStartsAt,endAt:a.bufferedEndsAt})),resource.capacity))throw new Error("SLOT_FULL");const old={resourceId:String(appointment.resourceId),startsAt:appointment.startsAt.toISOString()};appointment.resourceId=resource._id;appointment.resourceName=resource.name;appointment.startsAt=slot.startsAt;appointment.endsAt=slot.endsAt;appointment.bufferedStartsAt=slot.bufferedStartsAt;appointment.bufferedEndsAt=slot.bufferedEndsAt;appointment.version+=1;detail={from:old,to:{resourceId:String(resource._id),startsAt:slot.startsAt.toISOString()},reserveBeforeRelease:true}}
  await appointment.save({session});await AppointmentEvent.create([{tenantId,appointmentId:appointment._id,actorId:access!.scope.userId,action:parsed.data.action,details:detail}],{session});await AuditEvent.create([{tenantId,actorId:access!.scope.userId,action:`appointment.${parsed.data.action}`,entityType:"appointment",entityId:String(appointment._id),requestId:randomBytes(12).toString("hex"),metadata:detail}],{session});result=appointment.toObject()
 })}catch(error){if(error instanceof Error){if(error.message==="NOT_FOUND")return NextResponse.json({error:"Appointment not found."},{status:404});if(error.message==="SLOT_FULL")return NextResponse.json({error:"That time was just booked. Refresh availability and choose another slot."},{status:409});if(error.message==="INVALID_SLOT")return NextResponse.json({error:"That time is not an available appointment slot."},{status:409});if(error.message==="INVALID_STATE")return NextResponse.json({error:"This action is not available for the appointment’s current status."},{status:409})}return NextResponse.json({error:"Appointments are temporarily unavailable."},{status:503})}finally{await session.endSession()}return NextResponse.json({appointment:result},{headers:{"Cache-Control":"private, no-store"}})
}
