import {createHash} from "node:crypto";
import mongoose from "mongoose";
import {NextResponse} from "next/server";
import {z} from "zod";
import {isSameOrigin,readJsonLimited} from "@/server/request-security";
import {consumePublicCheckoutAttempt} from "@/server/rate-limit";
import {commerceEventQueue} from "@/server/queues";
import {calculateStorefrontTotals,storefrontPolicyVersion} from "@/server/domain/storefront-checkout";
import {initialStorefrontPaymentMinor} from "@/server/domain/storefront-payments";
import {Order} from "@/server/models/Order";
import {OrderCounter} from "@/server/models/OrderCounter";
import {CatalogueItem} from "@/server/models/CatalogueItem";
import {CatalogueVariant} from "@/server/models/CatalogueVariant";
import {Tenant} from "@/server/models/Tenant";
import {AuditEvent} from "@/server/models/AuditEvent";
import {decryptSecret,encryptSecret,hashSessionToken,newSessionToken} from "@/server/secrets";
export const dynamic="force-dynamic";
type Context={params:Promise<{slug:string}>};
const addressSchema=z.object({recipient:z.string().trim().min(2).max(160),line1:z.string().trim().min(2).max(200),line2:z.string().trim().max(200).default(""),city:z.string().trim().min(2).max(120),region:z.string().trim().max(120).default(""),postalCode:z.string().trim().min(1).max(32),countryCode:z.string().trim().toUpperCase().regex(/^[A-Z]{2}$/)}).strict();
const schema=z.object({customer:z.object({name:z.string().trim().min(2).max(160),email:z.string().trim().email().max(254),phone:z.string().trim().max(40).default("")}).strict(),lines:z.array(z.object({itemId:z.string().regex(/^[a-f\d]{24}$/i),variantId:z.string().regex(/^[a-f\d]{24}$/i).optional(),quantity:z.number().int().safe().min(1).max(100000)}).strict()).min(1).max(30),fulfilmentMethod:z.enum(["delivery","pickup"]),shippingAddress:addressSchema.nullable(),paymentMethod:z.enum(["bank_transfer","cash_on_pickup"]),acceptedTerms:z.literal(true),policyVersion:z.string().regex(/^[a-f\d]{64}$/i)}).strict().superRefine((value,context)=>{
 if(new Set(value.lines.map(line=>`${line.itemId}:${line.variantId||"base"}`)).size!==value.lines.length)context.addIssue({code:"custom",path:["lines"],message:"A product option may appear once in checkout; set its quantity instead."});
 if(value.fulfilmentMethod==="delivery"&&!value.shippingAddress)context.addIssue({code:"custom",path:["shippingAddress"],message:"A delivery address is required."});
 if(value.fulfilmentMethod==="pickup"&&value.shippingAddress)context.addIssue({code:"custom",path:["shippingAddress"],message:"Pickup orders do not accept a delivery address."});
 if(value.paymentMethod==="cash_on_pickup"&&value.fulfilmentMethod!=="pickup")context.addIssue({code:"custom",path:["paymentMethod"],message:"Cash payment is available for pickup only."});
});
function fail(){return NextResponse.json({error:"Checkout is temporarily unavailable. Please try again."},{status:503,headers:{"Cache-Control":"no-store"}})}

function responseFor(order:{orderNumber:string;receiptTokenEncrypted:string},replayed:boolean){return{orderNumber:order.orderNumber,receiptPath:`/order/${encodeURIComponent(decryptSecret(order.receiptTokenEncrypted))}`,replayed}}
function validKey(key:string|null):key is string{return Boolean(key&&key.length<=120&&/^[A-Za-z0-9._:-]+$/.test(key))}
export async function POST(request:Request,context:Context){
 if(!isSameOrigin(request))return NextResponse.json({error:"Request origin could not be verified."},{status:403});
 const key=request.headers.get("idempotency-key")?.trim()??null;if(!validKey(key))return NextResponse.json({error:"Checkout requires a valid request key. Please refresh and try again."},{status:400});
 const body=await readJsonLimited(request,24000);if(body.kind==="too-large")return NextResponse.json({error:"Checkout request is too large."},{status:413});const parsed=schema.safeParse(body.kind==="ok"?body.value:null);if(!parsed.success)return NextResponse.json({error:"Review the contact, delivery and checkout details.",issues:parsed.error.issues.map(issue=>({field:issue.path.join("."),message:issue.message}))},{status:400});const input=parsed.data;
 const{slug}=await context.params;if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)||slug.length>80)return NextResponse.json({error:"This storefront is unavailable."},{status:404});
 try{
  const tenant=await Tenant.findOne({slug,commerceMode:"native",storefrontEnabled:true}).lean();if(!tenant)return NextResponse.json({error:"This storefront is unavailable."},{status:404});
  const ip=request.headers.get("x-real-ip")||request.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||"unknown";const attempts=await consumePublicCheckoutAttempt(String(tenant._id),ip);if(attempts>12)return NextResponse.json({error:"Too many checkout attempts. Wait a little and try again."},{status:429,headers:{"Retry-After":"900","Cache-Control":"no-store"}});
  if(input.policyVersion!==storefrontPolicyVersion(tenant.storefrontTerms||"",tenant.storefrontPrivacy||""))return NextResponse.json({error:"The store policies changed. Review the latest terms and submit again."},{status:409});
  if(input.fulfilmentMethod==="delivery"&&!tenant.deliveryEnabled)return NextResponse.json({error:"Delivery is not available for this store."},{status:409});if(input.fulfilmentMethod==="pickup"&&!tenant.pickupEnabled)return NextResponse.json({error:"Pickup is not available for this store."},{status:409});
  if(input.paymentMethod==="bank_transfer"&&!tenant.bankTransferEnabled)return NextResponse.json({error:"Bank transfer is not available for this store."},{status:409});if(input.paymentMethod==="cash_on_pickup"&&(!tenant.cashOnPickupEnabled||input.fulfilmentMethod!=="pickup"||tenant.storefrontPaymentMode==="deposit"))return NextResponse.json({error:tenant.storefrontPaymentMode==="deposit"?"Cash on pickup cannot collect an advance deposit. Choose bank transfer.":"Cash on pickup is not available for this order."},{status:409});
  const fingerprint=createHash("sha256").update(JSON.stringify(input)).digest("hex");const prior=await Order.findOne({tenantId:tenant._id,idempotencyKey:key}).select("+requestFingerprint +receiptTokenEncrypted").lean();if(prior){if(prior.requestFingerprint!==fingerprint)return NextResponse.json({error:"This checkout key was used for a different order. Refresh the bag before retrying."},{status:409});if(!prior.receiptTokenEncrypted)return NextResponse.json({error:"This order was already placed. Contact the store if you need the receipt link again."},{status:409});return NextResponse.json(responseFor(prior as unknown as {orderNumber:string;receiptTokenEncrypted:string},true),{headers:{"Cache-Control":"no-store"}})}
  const session=await mongoose.startSession();let result:{orderId:string;orderNumber:string;receiptTokenEncrypted:string}|null=null;const receiptToken=newSessionToken(),receiptTokenEncrypted=encryptSecret(receiptToken),receiptTokenExpiresAt=new Date(Date.now()+365*24*60*60*1000),reservationExpiresAt=new Date(Date.now()+tenant.reservationMinutes*60*1000);
  try{await session.withTransaction(async()=>{
   const currentTenant=await Tenant.findOne({_id:tenant._id,slug,commerceMode:"native",storefrontEnabled:true}).session(session).lean();if(!currentTenant)throw new Error("STORE_CLOSED");if(input.policyVersion!==storefrontPolicyVersion(currentTenant.storefrontTerms||"",currentTenant.storefrontPrivacy||""))throw new Error("POLICY_UPDATED");
   const ids=[...new Set(input.lines.map(line=>line.itemId))].map(id=>new mongoose.Types.ObjectId(id)),items=await CatalogueItem.find({_id:{$in:ids},tenantId:tenant._id,kind:"physical",status:"active",storefrontPublished:true}).session(session).lean();if(items.length!==ids.length)throw new Error("ITEM_UNAVAILABLE");const variantRows=await CatalogueVariant.find({tenantId:tenant._id,itemId:{$in:items.map(item=>item._id)}}).session(session).lean(),variantsByItem=new Map<string,typeof variantRows>();for(const variant of variantRows){const key=String(variant.itemId),group=variantsByItem.get(key)||[];group.push(variant);variantsByItem.set(key,group)}const byId=new Map(items.map(item=>[String(item._id),item]));const orderLines:Record<string,unknown>[]=[];const priceInputs=[] as {unitPriceMinor:number;quantity:number;taxRateBps:number;taxMode:"inclusive"|"exclusive"}[];
   for(const requested of input.lines){const item=byId.get(requested.itemId);if(!item)throw new Error("ITEM_UNAVAILABLE");const options=variantsByItem.get(requested.itemId)||[];let variant:(typeof variantRows)[number]|undefined;if(options.length){if(!requested.variantId)throw new Error("VARIANT_REQUIRED");variant=options.find(candidate=>String(candidate._id)===requested.variantId&&candidate.active);if(!variant)throw new Error("ITEM_UNAVAILABLE")}else if(requested.variantId)throw new Error("ITEM_UNAVAILABLE");if(item.trackInventory){const update=variant?await CatalogueVariant.updateOne({_id:variant._id,itemId:item._id,tenantId:tenant._id,active:true,$expr:{$gte:[{$subtract:["$stockOnHand","$stockReserved"]},requested.quantity]}},{$inc:{stockReserved:requested.quantity,version:1}},{session}):await CatalogueItem.updateOne({_id:item._id,tenantId:tenant._id,status:"active",kind:"physical",storefrontPublished:true,trackInventory:true,$expr:{$gte:[{$subtract:["$stockOnHand","$stockReserved"]},requested.quantity]}},{$inc:{stockReserved:requested.quantity,version:1}},{session});if(!update.modifiedCount)throw new Error("STOCK_UNAVAILABLE")}
    const unitPriceMinor=variant?.unitPriceMinor??item.unitPriceMinor;priceInputs.push({unitPriceMinor,quantity:requested.quantity,taxRateBps:item.taxRateBps,taxMode:item.taxMode as "inclusive"|"exclusive"});orderLines.push({itemId:item._id,variantId:variant?._id||null,variantName:variant?.name||null,variantOptions:variant?.options||[],kind:item.kind,name:item.name,sku:variant?.sku||item.sku,quantity:requested.quantity,unitPriceMinor,taxRateBps:item.taxRateBps,taxMode:item.taxMode,tracksStock:item.trackInventory})
   }
   const deliveryInput=input.fulfilmentMethod==="delivery"?{unitPriceMinor:currentTenant.deliveryFlatFeeMinor,quantity:1,taxRateBps:currentTenant.deliveryTaxRateBps,taxMode:currentTenant.deliveryTaxMode as "inclusive"|"exclusive"}:null;const totals=calculateStorefrontTotals(priceInputs,tenant.baseCurrency,deliveryInput);for(let index=0;index<orderLines.length;index++){const amount=totals.lineAmounts[index];Object.assign(orderLines[index],{netMinor:amount.netMinor,taxMinor:amount.taxMinor,grossMinor:amount.grossMinor})}const{subtotalMinor,taxMinor,shippingFeeMinor,totalMinor}=totals;
   const counter=await OrderCounter.findOneAndUpdate({tenantId:tenant._id},{$inc:{nextNumber:1},$setOnInsert:{tenantId:tenant._id}},{new:true,upsert:true,session});const orderNumber=`ORD-${new Date().getUTCFullYear().toString().slice(-2)}-${String(counter.nextNumber).padStart(6,"0")}`;
   const depositDueMinor=initialStorefrontPaymentMinor(totalMinor,currentTenant.storefrontPaymentMode||"full",currentTenant.storefrontDepositPercentBps||3000);
   const[order]=await Order.create([{tenantId:tenant._id,orderNumber,customerId:null,customerSnapshot:{name:input.customer.name,email:input.customer.email.toLowerCase(),phone:input.customer.phone||null},lines:orderLines,currency:tenant.baseCurrency,subtotalMinor,taxMinor,shippingFeeMinor,totalMinor,depositDueMinor,source:"storefront",fulfilmentMethod:input.fulfilmentMethod,shippingAddress:input.shippingAddress,paymentMethod:input.paymentMethod,paymentInstructionsSnapshot:input.paymentMethod==="bank_transfer"?currentTenant.bankTransferInstructions:"Pay in cash when you collect your order.",storefrontTermsSnapshot:currentTenant.storefrontTerms,storefrontPrivacySnapshot:currentTenant.storefrontPrivacy,policyVersion:input.policyVersion,reservationExpiresAt,status:"pending_payment",paymentStatus:"pending",fulfilmentStatus:"unfulfilled",idempotencyKey:key,requestFingerprint:fingerprint,createdBy:null,receiptTokenHash:hashSessionToken(receiptToken),receiptTokenEncrypted,receiptTokenExpiresAt}],{session});
   await AuditEvent.create([{tenantId:tenant._id,actorId:null,action:"storefront.order_placed",entityType:"order",entityId:String(order._id),requestId:key,metadata:{orderNumber,totalMinor,currency:tenant.baseCurrency,lineCount:order.lines.length,fulfilmentMethod:order.fulfilmentMethod,paymentMethod:order.paymentMethod,policyVersion:order.policyVersion}}],{session});result={orderId:String(order._id),orderNumber,receiptTokenEncrypted};
  })}catch(error){if(error instanceof Error&&error.message==="STORE_CLOSED")return NextResponse.json({error:"This storefront has closed checkout. Refresh and try again."},{status:409});if(error instanceof Error&&error.message==="POLICY_UPDATED")return NextResponse.json({error:"The store policies changed. Review them and submit again."},{status:409});if(error instanceof Error&&error.message==="VARIANT_REQUIRED")return NextResponse.json({error:"Choose an option for each product with variants."},{status:400});if(error instanceof Error&&error.message==="ITEM_UNAVAILABLE")return NextResponse.json({error:"A product or option in your bag is no longer available. Refresh the store and try again."},{status:409});if(error instanceof Error&&error.message==="STOCK_UNAVAILABLE")return NextResponse.json({error:"There is not enough stock for one of the options. Reduce its quantity and try again."},{status:409});if((error as {code?:number})?.code===11000){const replay=await Order.findOne({tenantId:tenant._id,idempotencyKey:key}).select("+requestFingerprint +receiptTokenEncrypted").lean();if(replay&&replay.requestFingerprint===fingerprint&&replay.receiptTokenEncrypted)return NextResponse.json(responseFor(replay as unknown as {orderNumber:string;receiptTokenEncrypted:string},true),{headers:{"Cache-Control":"no-store"}});return NextResponse.json({error:"This checkout request was already processed."},{status:409})}if(error instanceof RangeError)return NextResponse.json({error:"The order total is outside the supported amount range."},{status:422});return fail()}finally{await session.endSession()}
  const completed=result as {orderId:string;orderNumber:string;receiptTokenEncrypted:string}|null;if(!completed)return fail();try{const holdDelay=reservationExpiresAt.getTime()-Date.now();const jobId=`hold-${createHash("sha256").update(`${tenant._id}:${key}`).digest("hex")}`;await commerceEventQueue().add("expire-store-order-hold",{tenantId:String(tenant._id),orderId:completed.orderId}, {jobId,delay:holdDelay,attempts:8,backoff:{type:"exponential",delay:30000},removeOnComplete:500,removeOnFail:1000})}catch(error){console.error(JSON.stringify({level:"error",event:"checkout_hold_job_schedule_failed",requestId:key,error:error instanceof Error?error.message:"QUEUE_ERROR"}))}
  return NextResponse.json(responseFor(completed,false),{status:201,headers:{"Cache-Control":"no-store"}})
 }catch{return fail()}
}



