import {randomBytes} from "node:crypto";
import {NextResponse} from "next/server";
import {z} from "zod";
import {requireTenantAccess} from "@/server/tenant-scope";
import {Tenant} from "@/server/models/Tenant";
import {AuditEvent} from "@/server/models/AuditEvent";
import {isSameOrigin,readJsonLimited} from "@/server/request-security";
export const dynamic="force-dynamic";
function fail(error:unknown){if(error instanceof Error&&error.message==="PERMISSION_DENIED")return NextResponse.json({error:"You do not have permission to change quote approval policy."},{status:403});return NextResponse.json({error:"Quote approval policy is temporarily unavailable."},{status:503})}
export async function GET(){let access;try{access=await requireTenantAccess("tenant:settings")}catch(error){return fail(error)}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});try{const tenant=await Tenant.findById(access.scope.tenantId).select("quoteDiscountApprovalThresholdBps").lean();if(!tenant)return NextResponse.json({error:"Workspace not found."},{status:404});return NextResponse.json({thresholdBps:tenant.quoteDiscountApprovalThresholdBps??0},{headers:{"Cache-Control":"private, no-store"}})}catch(error){return fail(error)}}
export async function PATCH(request:Request){if(!isSameOrigin(request))return NextResponse.json({error:"Request origin could not be verified."},{status:403});let access;try{access=await requireTenantAccess("tenant:settings")}catch(error){return fail(error)}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});const limited=await readJsonLimited(request,2048);if(limited.kind==="too-large")return NextResponse.json({error:"Request is too large."},{status:413});const parsed=z.object({thresholdBps:z.number().int().min(0).max(9999)}).strict().safeParse(limited.kind==="ok"?limited.value:null);if(!parsed.success)return NextResponse.json({error:"Enter a discount threshold from 0% to 99.99%."},{status:400});try{const tenant=await Tenant.findOneAndUpdate({_id:access.scope.tenantId},{$set:{quoteDiscountApprovalThresholdBps:parsed.data.thresholdBps}},{new:true,runValidators:true}).select("quoteDiscountApprovalThresholdBps").lean();if(!tenant)return NextResponse.json({error:"Workspace not found."},{status:404});await AuditEvent.create({tenantId:access.scope.tenantId,actorId:access.scope.userId,action:"quote.approval_policy_updated",entityType:"tenant",entityId:String(tenant._id),requestId:randomBytes(12).toString("hex"),metadata:{thresholdBps:tenant.quoteDiscountApprovalThresholdBps}});return NextResponse.json({thresholdBps:tenant.quoteDiscountApprovalThresholdBps},{headers:{"Cache-Control":"private, no-store"}})}catch(error){return fail(error)}}
