import {randomBytes} from "node:crypto";
import mongoose from "mongoose";
import {NextResponse} from "next/server";
import {z} from "zod";
import {requireTenantAccess} from "@/server/tenant-scope";
import {isSameOrigin,readJsonLimited} from "@/server/request-security";
import {Quote} from "@/server/models/Quote";
import {AuditEvent} from "@/server/models/AuditEvent";
import {quoteDiscountRequiresApproval} from "@/server/domain/quote-approval";
type Context={params:Promise<{id:string}>};
const decisionSchema=z.object({decision:z.enum(["approve","reject"]),note:z.string().trim().max(1200).optional()}).strict().superRefine((value,context)=>{if(value.decision==="reject"&&(value.note?.length??0)<2)context.addIssue({code:"custom",path:["note"],message:"Explain why the quote is being returned."})});
function fail(error:unknown){if(error instanceof Error&&error.message==="PERMISSION_DENIED")return NextResponse.json({error:"Quote approval permission is required."},{status:403});return NextResponse.json({error:"Quote approval could not be recorded."},{status:503})}
export async function POST(request:Request,context:Context){if(!isSameOrigin(request))return NextResponse.json({error:"Request origin could not be verified."},{status:403});let access;try{access=await requireTenantAccess("quotes:approve")}catch(error){return fail(error)}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});const{id}=await context.params;if(!mongoose.isValidObjectId(id))return NextResponse.json({error:"Quote not found."},{status:404});const limited=await readJsonLimited(request,4096);if(limited.kind==="too-large")return NextResponse.json({error:"Request is too large."},{status:413});const parsed=decisionSchema.safeParse(limited.kind==="ok"?limited.value:null);if(!parsed.success)return NextResponse.json({error:"Choose an approval decision and provide a reason when returning the quote."},{status:400});const session=await mongoose.startSession();let result:unknown;try{await session.withTransaction(async()=>{const quote=await Quote.findOne({_id:id,tenantId:access.scope.tenantId,status:"approval_pending"}).session(session);if(!quote)throw new Error("APPROVAL_NOT_PENDING");const threshold=Number(quote.approvalThresholdBps??0);if(!quoteDiscountRequiresApproval(quote.discountPercentBps,threshold))throw new Error("APPROVAL_NOT_REQUIRED");const now=new Date();quote.status=parsed.data.decision==="approve"?"approved":"draft";quote.approvalDecision=parsed.data.decision==="approve"?"approved":"rejected";quote.approvalDecidedBy=access.scope.userId as never;quote.approvalDecidedAt=now;quote.approvalDecisionNote=parsed.data.note||null as never;await quote.save({session});await AuditEvent.create([{tenantId:access.scope.tenantId,actorId:access.scope.userId,action:parsed.data.decision==="approve"?"quote.discount_approved":"quote.discount_rejected",entityType:"quote",entityId:String(quote._id),requestId:randomBytes(12).toString("hex"),metadata:{quoteNumber:quote.quoteNumber,discountPercentBps:quote.discountPercentBps,thresholdBps:threshold,note:parsed.data.note||null}}],{session});const safe=quote.toObject();delete (safe as {acceptTokenHash?:string}).acceptTokenHash;result=safe})}catch(error){if(error instanceof Error&&error.message==="APPROVAL_NOT_PENDING")return NextResponse.json({error:"This quote is no longer awaiting approval."},{status:409});if(error instanceof Error&&error.message==="APPROVAL_NOT_REQUIRED")return NextResponse.json({error:"The current quote discount no longer requires approval."},{status:409});return fail(error)}finally{await session.endSession()}return NextResponse.json({quote:result},{headers:{"Cache-Control":"private, no-store"}})}
