import {randomBytes} from "node:crypto";
import mongoose from "mongoose";
import {NextResponse} from "next/server";
import {z} from "zod";
import {requireTenantAccess} from "@/server/tenant-scope";
import {isSameOrigin,readJsonLimited} from "@/server/request-security";
import {Deal} from "@/server/models/Deal";
import {DealTask} from "@/server/models/DealTask";
import {DealEvent} from "@/server/models/DealEvent";
import {Membership} from "@/server/models/Membership";
import {User} from "@/server/models/User";
import {AuditEvent} from "@/server/models/AuditEvent";

export const dynamic="force-dynamic";
const schema=z.object({dealId:z.string().regex(/^[a-f\d]{24}$/i),title:z.string().trim().min(2).max(180),dueAt:z.string().datetime({offset:true}),assigneeId:z.string().regex(/^[a-f\d]{24}$/i).optional()}).strict();
function failure(error:unknown){if(error instanceof Error&&error.message==="PERMISSION_DENIED")return NextResponse.json({error:"You do not have permission to manage deal tasks."},{status:403});return NextResponse.json({error:"Deal tasks are temporarily unavailable."},{status:503})}
export async function GET(){let access;try{access=await requireTenantAccess("deals:write")}catch(error){return failure(error)}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});try{const dealFilter:Record<string,unknown>={tenantId:access.scope.tenantId};if(access.scope.role==="sales")dealFilter.ownerId=access.scope.userId;const deals=await Deal.find(dealFilter).select("_id").limit(500).lean(),dealIds=deals.map(deal=>deal._id),tasks=await DealTask.find({tenantId:access.scope.tenantId,dealId:{$in:dealIds}}).sort({status:1,dueAt:1}).limit(500).lean(),users=await User.find({_id:{$in:tasks.map(task=>task.assigneeId)}}).select("name").lean(),names=new Map(users.map(user=>[String(user._id),user.name]));return NextResponse.json({tasks:tasks.map(task=>({...task,_id:String(task._id),assigneeName:names.get(String(task.assigneeId))||"Former team member"}))},{headers:{"Cache-Control":"private, no-store"}})}catch(error){return failure(error)}}
export async function POST(request:Request){if(!isSameOrigin(request))return NextResponse.json({error:"Request origin could not be verified."},{status:403});let access;try{access=await requireTenantAccess("deals:write")}catch(error){return failure(error)}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});const body=await readJsonLimited(request,10000);if(body.kind==="too-large")return NextResponse.json({error:"Request is too large."},{status:413});const parsed=schema.safeParse(body.kind==="ok"?body.value:null);if(!parsed.success)return NextResponse.json({error:"Provide a deal, task title and due date."},{status:400});if(parsed.data.assigneeId&&access.scope.role!=="owner")return NextResponse.json({error:"Only an owner can assign a task to another teammate."},{status:403});const tenantId=access.scope.tenantId,session=await mongoose.startSession();let result:unknown;try{await session.withTransaction(async()=>{const dealFilter:Record<string,unknown>={_id:parsed.data.dealId,tenantId};if(access!.scope.role==="sales")dealFilter.ownerId=access!.scope.userId;const deal=await Deal.findOne(dealFilter).session(session);if(!deal)throw new Error("DEAL_NOT_FOUND");const assigneeId=parsed.data.assigneeId||access!.scope.userId, [membership,user]=await Promise.all([Membership.findOne({tenantId,userId:assigneeId,revokedAt:null}).session(session).lean(),User.findOne({_id:assigneeId,disabledAt:null}).select("_id").session(session).lean()]);if(!membership||!user)throw new Error("ASSIGNEE_NOT_FOUND");const[task]=await DealTask.create([{tenantId,dealId:deal._id,title:parsed.data.title,dueAt:new Date(parsed.data.dueAt),assigneeId,createdBy:access!.scope.userId,status:"open"}],{session});const details={taskId:String(task._id),title:task.title,dueAt:task.dueAt.toISOString(),assigneeId:String(task.assigneeId)};await DealEvent.create([{tenantId,dealId:deal._id,actorId:access!.scope.userId,action:"task_created",details}],{session});await AuditEvent.create([{tenantId,actorId:access!.scope.userId,action:"deal.task_created",entityType:"deal",entityId:String(deal._id),requestId:randomBytes(12).toString("hex"),metadata:details}],{session});result=task.toObject()})}catch(error){if(error instanceof Error&&error.message==="DEAL_NOT_FOUND")return NextResponse.json({error:"Deal not found."},{status:404});if(error instanceof Error&&error.message==="ASSIGNEE_NOT_FOUND")return NextResponse.json({error:"Choose an active workspace teammate."},{status:400});return failure(error)}finally{await session.endSession()}return NextResponse.json({task:result},{status:201,headers:{"Cache-Control":"private, no-store"}})}
