import {createHash,randomBytes} from "node:crypto";
import mongoose from "mongoose";
import {NextResponse} from "next/server";
import {requireTenantAccess} from "@/server/tenant-scope";
import {isSameOrigin} from "@/server/request-security";
import {Quote} from "@/server/models/Quote";
import {QuoteRevision} from "@/server/models/QuoteRevision";
import {Order} from "@/server/models/Order";
import {OrderCounter} from "@/server/models/OrderCounter";
import {CatalogueItem} from "@/server/models/CatalogueItem";
import {AuditEvent} from "@/server/models/AuditEvent";
import {ensureServiceWorkOrders} from "@/server/work-orders";
import {encryptSecret,decryptSecret,hashSessionToken,newSessionToken,hasValidEncryptionKey} from "@/server/secrets";
type Context={params:Promise<{id:string}>};
function fail(error:unknown){if(error instanceof Error&&error.message==="PERMISSION_DENIED")return NextResponse.json({error:"Quote approval permission is required to convert this quote."},{status:403});return NextResponse.json({error:"Quote conversion is temporarily unavailable."},{status:503})}
export async function POST(request:Request,context:Context){if(!isSameOrigin(request))return NextResponse.json({error:"Request origin could not be verified."},{status:403});let access;try{access=await requireTenantAccess("quotes:approve")}catch(error){return fail(error)}if(!access)return NextResponse.json({error:"Sign in is required."},{status:401});if(access.tenant.commerceMode!=="native")return NextResponse.json({error:"Order conversion is managed by the connected WooCommerce store."},{status:409});if(!hasValidEncryptionKey())return NextResponse.json({error:"Set a valid APP_ENCRYPTION_KEY before creating the private payment request."},{status:503});const{id}=await context.params;if(!mongoose.isValidObjectId(id))return NextResponse.json({error:"Quote not found."},{status:404});const session=await mongoose.startSession();let result:unknown,replayed=false,paymentPath="";try{await session.withTransaction(async()=>{
 const quote=await Quote.findOne({_id:id,tenantId:access.scope.tenantId}).session(session);if(!quote)throw new Error("QUOTE_NOT_FOUND");if(quote.status==="converted"&&quote.convertedOrderId){const prior=await Order.findOne({_id:quote.convertedOrderId,tenantId:access.scope.tenantId}).select("+receiptTokenEncrypted").session(session).lean();if(!prior)throw new Error("CONVERTED_ORDER_MISSING");if(prior.receiptTokenEncrypted&&prior.receiptTokenExpiresAt>new Date())paymentPath=`/order/${encodeURIComponent(decryptSecret(prior.receiptTokenEncrypted))}`;const safePrior={...prior} as Record<string,unknown>;delete safePrior.receiptTokenEncrypted;delete safePrior.receiptTokenHash;result=safePrior;replayed=true;return}if(quote.status!=="accepted"||quote.acceptedRevision!==quote.currentRevision)throw new Error("QUOTE_NOT_ACCEPTED");
 const revision=await QuoteRevision.findOne({tenantId:access.scope.tenantId,quoteId:quote._id,revision:quote.acceptedRevision}).session(session).lean();if(!revision)throw new Error("REVISION_MISSING");const currentItems=await CatalogueItem.find({_id:{$in:revision.lines.map((line)=>line.itemId)},tenantId:access.scope.tenantId}).session(session).lean();if(currentItems.length!==revision.lines.length)throw new Error("ITEM_MISSING");const byId=new Map(currentItems.map((item)=>[String(item._id),item]));const orderLines=[] as Record<string,unknown>[];
 for(const line of revision.lines){const item=byId.get(String(line.itemId));if(!item||item.kind!==line.kind)throw new Error("ITEM_MISSING");const tracksStock=item.kind==="physical"&&item.trackInventory;if(tracksStock){const reserved=await CatalogueItem.updateOne({_id:item._id,tenantId:access.scope.tenantId,trackInventory:true,$expr:{$gte:[{$subtract:["$stockOnHand","$stockReserved"]},line.quantity]}},{$inc:{stockReserved:line.quantity,version:1}},{session});if(!reserved.modifiedCount)throw new Error("STOCK_UNAVAILABLE")};orderLines.push({itemId:item._id,kind:line.kind,name:line.name,sku:line.sku,quantity:line.quantity,unitPriceMinor:line.unitPriceMinor,discountPercentBps:line.discountPercentBps||0,discountAmountMinor:line.discountAmountMinor||0,taxRateBps:line.taxRateBps,taxMode:line.taxMode,netMinor:line.netMinor,taxMinor:line.taxMinor,grossMinor:line.grossMinor,tracksStock})}
 const counter=await OrderCounter.findOneAndUpdate({tenantId:access.scope.tenantId},{$inc:{nextNumber:1},$setOnInsert:{tenantId:access.scope.tenantId}},{upsert:true,new:true,session});const orderNumber=`ORD-${new Date().getUTCFullYear().toString().slice(-2)}-${String(counter.nextNumber).padStart(6,"0")}`;const key=`quote:${quote._id}:r${revision.revision}`,fingerprint=createHash("sha256").update(`${quote._id}:${revision.revision}`).digest("hex"),receiptToken=newSessionToken(),receiptTokenEncrypted=encryptSecret(receiptToken),receiptTokenExpiresAt=new Date(Date.now()+365*24*60*60*1000);const[order]=await Order.create([{tenantId:access.scope.tenantId,orderNumber,customerId:quote.customerId,customerSnapshot:revision.customerSnapshot,lines:orderLines,source:"quote",currency:revision.currency,subtotalMinor:revision.subtotalMinor,taxMinor:revision.taxMinor,totalMinor:revision.totalMinor,depositDueMinor:revision.depositDueMinor||revision.totalMinor,status:"open",paymentStatus:"unpaid",fulfilmentStatus:"unfulfilled",sourceQuoteId:quote._id,sourceQuoteRevision:revision.revision,idempotencyKey:key,requestFingerprint:fingerprint,createdBy:access.scope.userId,receiptTokenHash:hashSessionToken(receiptToken),receiptTokenEncrypted,receiptTokenExpiresAt}],{session});await ensureServiceWorkOrders(order,session);paymentPath=`/order/${encodeURIComponent(receiptToken)}`;quote.status="converted";quote.convertedOrderId=order._id;quote.convertedAt=new Date();await quote.save({session});await AuditEvent.create([{tenantId:access.scope.tenantId,actorId:access.scope.userId,action:"quote.converted_to_order",entityType:"quote",entityId:String(quote._id),requestId:randomBytes(12).toString("hex"),metadata:{quoteNumber:quote.quoteNumber,revision:revision.revision,orderNumber,totalMinor:revision.totalMinor,currency:revision.currency,depositDueMinor:revision.depositDueMinor||revision.totalMinor}}],{session});const safeOrder=order.toObject() as Record<string,unknown>;delete safeOrder.receiptTokenHash;delete safeOrder.receiptTokenEncrypted;result=safeOrder;
 })}catch(error){if(error instanceof Error&&error.message==="QUOTE_NOT_FOUND")return NextResponse.json({error:"Quote not found."},{status:404});if(error instanceof Error&&error.message==="QUOTE_NOT_ACCEPTED")return NextResponse.json({error:"Only the accepted quote revision can be converted."},{status:409});if(error instanceof Error&&error.message==="REVISION_MISSING")return NextResponse.json({error:"The accepted quote revision is unavailable."},{status:409});if(error instanceof Error&&(error.message==="ITEM_MISSING"||error.message==="CONVERTED_ORDER_MISSING"))return NextResponse.json({error:"A quoted item or its converted order is unavailable. Review the workspace records."},{status:409});if(error instanceof Error&&error.message==="STOCK_UNAVAILABLE")return NextResponse.json({error:"There is not enough stock to convert this accepted quote. The quote remains accepted."},{status:409});if((error as {code?:number})?.code===11000){const existing=await Order.findOne({tenantId:access.scope.tenantId,sourceQuoteId:id}).select("+receiptTokenEncrypted").lean();if(existing){if(existing.receiptTokenEncrypted&&existing.receiptTokenExpiresAt>new Date())paymentPath=`/order/${encodeURIComponent(decryptSecret(existing.receiptTokenEncrypted))}`;const safeExisting={...existing} as Record<string,unknown>;delete safeExisting.receiptTokenEncrypted;delete safeExisting.receiptTokenHash;return NextResponse.json({order:safeExisting,replayed:true,paymentPath},{headers:{"Cache-Control":"private, no-store"}})}}return fail(error)}finally{await session.endSession()}return NextResponse.json({order:result,replayed,paymentPath},{status:replayed?200:201,headers:{"Cache-Control":"private, no-store"}})}

