import {randomBytes} from "node:crypto";
import mongoose from "mongoose";
import {NextResponse} from "next/server";
import {z} from "zod";
import {isSameOrigin,readJsonLimited} from "@/server/request-security";
import {hashPassword,hashSessionToken,newSessionToken,verifyPassword} from "@/server/secrets";
import {consumeLoginAttempt} from "@/server/rate-limit";
import {Invitation} from "@/server/models/Invitation";
import {User} from "@/server/models/User";
import {Membership} from "@/server/models/Membership";
import {Session} from "@/server/models/Session";
import {AuditEvent} from "@/server/models/AuditEvent";
import {setSessionCookie} from "@/server/auth";

const schema=z.object({name:z.string().trim().min(2).max(120),password:z.string().min(12).max(128)}).strict();
export async function POST(request:Request,{params}:{params:Promise<{token:string}>}){if(!isSameOrigin(request))return NextResponse.json({error:"Request origin could not be verified."},{status:403});const{token}=await params;if(!/^[A-Za-z0-9_-]{40,50}$/.test(token))return NextResponse.json({error:"This invitation is invalid or has expired."},{status:410});const body=await readJsonLimited(request,8000);if(body.kind==="too-large")return NextResponse.json({error:"Request is too large."},{status:413});const parsed=schema.safeParse(body.kind==="ok"?body.value:null);if(!parsed.success)return NextResponse.json({error:"Enter your name and a password with at least 12 characters."},{status:400});const tokenHash=hashSessionToken(token);try{if(await consumeLoginAttempt(tokenHash)>8)return NextResponse.json({error:"Too many attempts. Try again later."},{status:429})}catch{return NextResponse.json({error:"Invitation service is temporarily unavailable."},{status:503})}
 let invitation;try{invitation=await Invitation.findOne({tokenHash,status:"pending",expiresAt:{$gt:new Date()}}).select("+tokenHash").lean()}catch{return NextResponse.json({error:"Invitation service is temporarily unavailable."},{status:503})}if(!invitation)return NextResponse.json({error:"This invitation is invalid or has expired."},{status:410});let user=await User.findOne({email:invitation.email}).select("+passwordHash name email disabledAt").lean();if(user?.disabledAt)return NextResponse.json({error:"This account has been disabled. Ask the workspace owner for help."},{status:403});if(user){if(!await verifyPassword(parsed.data.password,user.passwordHash))return NextResponse.json({error:"This email already has an account. Enter its current password to accept the invitation."},{status:401})}else{const existing=await User.findOne({email:invitation.email}).select("_id").lean();if(existing)return NextResponse.json({error:"This account could not be accessed. Contact the workspace owner."},{status:409})}
 const passwordHash=user?undefined:await hashPassword(parsed.data.password),sessionToken=newSessionToken(),expiresAt=new Date(Date.now()+14*24*60*60*1000),dbSession=await mongoose.startSession();let userId="";try{await dbSession.withTransaction(async()=>{const current=await Invitation.findOne({_id:invitation!._id,status:"pending",expiresAt:{$gt:new Date()}}).session(dbSession);if(!current)throw new Error("INVITATION_USED");let target=user?await User.findOne({_id:user._id,disabledAt:null}).session(dbSession):null;if(user&&!target)throw new Error("ACCOUNT_UNAVAILABLE");if(!target){const[created]=await User.create([{name:parsed.data.name,email:invitation!.email,passwordHash}],{session:dbSession});target=created}const existingMembership=await Membership.findOne({tenantId:invitation!.tenantId,userId:target._id}).session(dbSession);if(existingMembership){if(!existingMembership.revokedAt)throw new Error("ALREADY_MEMBER");existingMembership.role=invitation!.role;existingMembership.permissions=[];existingMembership.set("revokedAt",null);await existingMembership.save({session:dbSession})}else await Membership.create([{tenantId:invitation!.tenantId,userId:target._id,role:invitation!.role}],{session:dbSession});current.status="accepted";current.acceptedAt=new Date();await current.save({session:dbSession});await Session.create([{userId:target._id,tenantId:invitation!.tenantId,tokenHash:hashSessionToken(sessionToken),expiresAt}],{session:dbSession});await AuditEvent.create([{tenantId:invitation!.tenantId,actorId:target._id,action:"member.invitation_accepted",entityType:"membership",entityId:String(target._id),requestId:randomBytes(12).toString("hex"),metadata:{role:invitation!.role}}],{session:dbSession});userId=String(target._id)})}catch(error){if(error instanceof Error&&error.message==="ALREADY_MEMBER")return NextResponse.json({error:"This account already has access to the workspace."},{status:409});if(error instanceof Error&&error.message==="INVITATION_USED")return NextResponse.json({error:"This invitation has already been used or expired."},{status:410});if(error instanceof Error&&error.message==="ACCOUNT_UNAVAILABLE")return NextResponse.json({error:"This account could not be accessed. Contact the workspace owner."},{status:409});if((error as {code?:number})?.code===11000)return NextResponse.json({error:"This email or invitation was already used. Sign in or ask the owner for a new invitation."},{status:409});return NextResponse.json({error:"Invitation acceptance failed. Try again."},{status:503})}finally{await dbSession.endSession()}const response=NextResponse.json({ok:true,userId});setSessionCookie(response,sessionToken);return response
}
